### ISSUE TITLE
Thank you for the update!! but......il2cpp build error

### ISSUE THREAD

**Issue by ybb95** [suriyun-production/turnbase-rpg-docs#10]
Thank you for the update
However, when building il2cpp
It doesn't work on my phone

**Comment by insthync** [comment]
Which device, iOS or Android? 

It can build or not? if not there are any error logs in Console?

**Comment by ybb95** [comment]
using android ...
log : NotSupportedException ,  System.Reflection.Emit is not supported

**Comment by insthync** [comment]
Try set Scripting Runtime Version to .NET 4.x
![Screenshot_262](https://user-images.githubusercontent.com/2697550/71297415-0ac62800-23b6-11ea-8e1e-8b0da6526aaf.png)

Then find and remove System.Data.dll in `Project` tab

Then import this plugins update package 
[TBRPG_Plugins_Update.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/3990602/TBRPG_Plugins_Update.zip)

**Comment by ybb95** [comment]
Will build and work well thank you
