### ISSUE TITLE
PHP Hosting

### ISSUE THREAD

**Issue by DoctorDevMan** [suriyun-production/turnbase-rpg-docs#102]
Can you provide advice on a preferred PHP host for the RPG PHP service? Hopefully the is cheap and  quick to setup for testing. 

Or even better would it be possible to provide temporary access to an environment you currently have setup. Just for some very low bandwidth testing/demonstration for maybe a week or two. There are just a few interested parties that I'd like to show your template to in WebGL.

Thank you for developing this template and any assistance you can give with this request.

**Comment by dclgamingtr** [comment]
You can use localhost by installing Xampp or Appserv. This is for development use only. It will then be sufficient to install it on any php server. No need for a Vps host, at least for a start.

**Comment by DoctorDevMan** [comment]
Thank you for the reply, for your great work and for supporting this product!
