### ISSUE TITLE
Equipment container problem

### ISSUE THREAD

**Issue by bma42** [suriyun-production/turnbase-rpg-docs#103]
I have a problem with the model container equipment system. My character appears dead when he has an item equipped.

```
UnityException: Transform child out of bounds
BaseCharacterEntity.UpdateEquipModels () (at Assets/RPGGame/Core/Scripts/GamePlay/BaseCharacterEntity.cs:401)
BaseCharacterEntity.set_Item (PlayerItem value) (at Assets/RPGGame/Core/Scripts/GamePlay/BaseCharacterEntity.cs:51)
BaseGamePlayFormation.SetCharacter (System.Int32 position, PlayerItem item) (at Assets/RPGGame/Core/Scripts/GamePlay/BaseGamePlayFormation.cs:70)
GamePlayFormation.SetCharacter (System.Int32 position, PlayerItem item) (at Assets/RPGGame/Turnbase/Scripts/GamePlay/GamePlayFormation.cs:21)
BaseGamePlayFormation.SetFormationCharacters (EBattleType battleType) (at Assets/RPGGame/Core/Scripts/GamePlay/BaseGamePlayFormation.cs:26)
GamePlayFormation.Start () (at Assets/RPGGame/Turnbase/Scripts/GamePlay/GamePlayFormation.cs:16)
```
![1](https://user-images.githubusercontent.com/19147694/102710109-556fce00-42b0-11eb-9f52-9a7a912fbbd2.png)
![2](https://user-images.githubusercontent.com/19147694/102710113-5acd1880-42b0-11eb-8816-8801ca7293ce.png)

**Comment by bma42** [comment]
![3](https://user-images.githubusercontent.com/19147694/102710150-af709380-42b0-11eb-9b27-2668ca6ee919.png)

**Comment by bma42** [comment]
Anyone have a solution?

**Comment by insthync** [comment]
In `BaseCharacterEntity.cs`  line `399`
Change from
`for (int i = container.transform.childCount; i >= 0; --i)`
To
`for (int i = container.transform.childCount - 1; i >= 0; --i)`

**Comment by bma42** [comment]
Works now ! thank you
