### ISSUE TITLE
Character problem in mobile game.

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#105]
This problem happens when I open the game on the phone.There is no problem when I open it on the computer. I was surprised what to do. There was no such problem before. I haven't edited any files. It started to be a problem on its own. Please help me with this. Only mobile version has this problem. 
![d157875a-e2fc-40a7-8298-ab6a4afbc8ad](https://user-images.githubusercontent.com/61230304/103458830-d3a28a80-4d1c-11eb-91b2-e938fc2ac436.jpg)

It happens like this when starting the game. Only after attacking, it returns to its intended position.

**Comment by insthync** [comment]
Check your `Follow Camera` -> `Target` and `Target Offset` settings (Check `Y` position/offsets)

![Screenshot_267](https://user-images.githubusercontent.com/2697550/103460750-6e19c280-4d4b-11eb-98b9-7228d024585d.png)

**Comment by dclgamingtr** [comment]
![sorun2](https://user-images.githubusercontent.com/61230304/103461897-b8427a00-4d32-11eb-991d-b61f2237641e.png)
The settings you have already given are the same. There is no problem with the computer, but when I throw it into the phone, the game is problematic. This problem started when I updated the game to 1.15. This was not an issue before.

**Comment by dclgamingtr** [comment]
![a275443a-3af9-4079-ac47-a1666c8defda](https://user-images.githubusercontent.com/61230304/103462058-bcbb6280-4d33-11eb-8e01-45150263f2c4.jpg)
After attacking, they leave their hiding places and enter their positions one by one.

**Comment by insthync** [comment]
Okay, now I fixing it.

**Comment by insthync** [comment]
You can fix it by add codes in `GamePlayManager` -> find for `IEnumerator StartGame()` -> add `yield return new WaitForEndOfFrame();`

like this
```
    IEnumerator StartGame()
    {
        yield return new WaitForEndOfFrame();
```

**Comment by dclgamingtr** [comment]
The same problem exists in the arena. Where should I add this code for Arena?

**Comment by dclgamingtr** [comment]
else if (BattleType == EBattleType.Arena)
        {
			yield return new WaitForEndOfFrame();

**Comment by dclgamingtr** [comment]
When I applied the same code there, the problem in the arena disappeared. It works great.  Thank you for your help.
