### ISSUE TITLE
No Hud

### ISSUE THREAD

**Issue by eppak** [suriyun-production/turnbase-rpg-docs#108]
Hello, just downloaded the assets, followed the getting started. Running after build or in the editor the result is the same, it ask for login, i enter as guest, i can see three chars moving but no hud, cannot interact with any element.
What i0m doing wrong?
Thanks

**Comment by insthync** [comment]
Please attach screen shot when there is no hud

**Comment by eppak** [comment]
![image](https://user-images.githubusercontent.com/1262964/103549566-e4cbd280-4ea7-11eb-93d7-53f16f41e608.png)

**Comment by insthync** [comment]
No error?

**Comment by eppak** [comment]
Yes (sorry), on file UILanguageText here:

void OnValidate() {
         var textComponent = GetComponent<Text>();
         textComponent.text = defaultText;
    }

NullReferenceException: Object reference not set to an instance of an object
UILanguageText.OnValidate () (at Assets/RPGGame/Core/Scripts/UI/Language/UILanguageText.cs:32)

**Comment by insthync** [comment]
How about `ManageSceneManager`?, is it deactivated when enter lobby scene?

![Screenshot_281](https://user-images.githubusercontent.com/2697550/103745884-d52cc500-5032-11eb-8820-f7b812eb5e24.png)

**Comment by eppak** [comment]
Some script appare missing, is this right?
![image](https://user-images.githubusercontent.com/1262964/103930584-43e74c80-511f-11eb-81d0-d25986fa57e9.png)

**Comment by insthync** [comment]
No, it's not, seems like you have to setup Unity's UI via package manager (`Window` -> `Package Manager`), find for `Unity UI` and setup it.

![Screenshot_283](https://user-images.githubusercontent.com/2697550/103972180-0d511680-519f-11eb-888a-9402f697c49f.png)

Or maybe that components just missing, try click on `Missing (Mono script)` and set components like this
![Screenshot_284](https://user-images.githubusercontent.com/2697550/103972267-396c9780-519f-11eb-9232-78edd897bcea.png)

**Comment by eppak** [comment]
Opened with last lts and works perfectly, now need to give you 5 stars rating!
Thanks a lot
