### ISSUE TITLE
Many mistakes!

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#109]
Hello SURIYUN! 
I'm tired of struggling with a network error in MMORPG and switched to Turnbase.
Found many bugs ...
1. When clicking on a clan - an error "405 Method Not Allowed"
![1](https://user-images.githubusercontent.com/16080577/103812579-60c04900-5067-11eb-8fb2-3ffc79ec3d10.jpg)
2. I create a clan - 405 again!
![2](https://user-images.githubusercontent.com/16080577/103812768-af6de300-5067-11eb-9a3e-2d80b33e0746.jpg)
 3. I press "pending" - also an error ...
![3](https://user-images.githubusercontent.com/16080577/103813106-39b64700-5068-11eb-9332-dcd620036cd8.jpg)
4. On mobile, my team is behind the scenes ...
https://youtu.be/CiwsQMVg5IQ
5. There is a LanguageManager, but there are no scripts for choosing a language in the game ...
P.S. : Apache 2.4, Php 7.4, MySQL 8.0...

**Comment by insthync** [comment]
Okay, all were fixed 1.15b, I will upload it, I actually planned to include them in 1.16 but these problems seem to be affected most customers. So I will make an update.

**Comment by brabaris** [comment]
Ok!

**Comment by brabaris** [comment]
When to wait for the update?

**Comment by insthync** [comment]
I can send it to you immediately via email

**Comment by brabaris** [comment]
Thanks you! Good jobs!
