### ISSUE TITLE
The new Version bug, please help me

### ISSUE THREAD

**Issue by fangyoufu88** [suriyun-production/turnbase-rpg-docs#110]
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <9577ac7a62ef43179789031239ba8798>:0)
GameInstance.ShowProfileNameInputDialog (UnityEngine.Events.UnityAction`1[T0] onSuccess, UnityEngine.Events.UnityAction`1[T0] onError) (at Assets/RPGGame/Core/Scripts/Game/GameInstance.cs:672)
GameInstance.SetProfileName () (at Assets/RPGGame/Core/Scripts/Game/GameInstance.cs:346)
GameInstance.OnGameServiceLogin (PlayerResult result) (at Assets/RPGGame/Core/Scripts/Game/GameInstance.cs:129)
LoginSceneManager.OnValidateLoginTokenSuccess (PlayerResult result) (at Assets/RPGGame/Core/Scripts/Scene/LoginSceneManager.cs:34)
BaseGameService.HandleResult[T] (T result, UnityEngine.Events.UnityAction`1[T0] onSuccess, UnityEngine.Events.UnityAction`1[T0] onError) (at Assets/RPGGame/Core/Scripts/GameService/BaseGameService.cs:78)
BaseGameService+<>c__DisplayClass26_0.<ValidateLoginToken>b__0 (PlayerResult finishResult) (at Assets/RPGGame/Core/Scripts/GameService/BaseGameService.cs:154)
SQLiteGameService.DoValidateLoginToken (System.String playerId, System.String loginToken, System.Boolean refreshToken, UnityEngine.Events.UnityAction`1[T0] onFinish) (at Assets/RPGGame/Core/Scripts/GameService/Implement/SQLite/SQLiteGameServiceAuth.cs:74)
BaseGameService.ValidateLoginToken (System.Boolean refreshToken, UnityEngine.Events.UnityAction`1[T0] onSuccess, UnityEngine.Events.UnityAction`1[T0] onError) (at Assets/RPGGame/Core/Scripts/GameService/BaseGameService.cs:154)

**Comment by insthync** [comment]
Oh, I've fixed it, seems like I've forget to upload it, send me your invoice ID to ittipon.bay@gmail.com then I will send update package immediately
