### ISSUE TITLE
Iap Error Please help me ?

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#112]
![iaperror](https://user-images.githubusercontent.com/61230304/104434262-1a557780-559c-11eb-9f87-bde6c3d7784b.png)
I entered a key, deleted it so that it would not appear in the picture.

Hello, my problem is not solved I am having the same problem. After you exited from the remote connection, I started getting the same error. I'll be releasing my game soon so help please. According to my research, IStoreListener unity was disabled after the 2017 release. I understand the codes need to be updated, to work in Unity 2019 Release.

**Comment by insthync** [comment]
Fixed by downgrade IAP package to 2.06
![Screenshot_169](https://user-images.githubusercontent.com/2697550/104814406-434a6680-5841-11eb-8726-d071c7813f1c.png)
