### ISSUE TITLE
Level up and evolve 

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#114]
hey @insthync is it possible to already have the materials selected for the level and evolve so all the player has to do is press the level up or evolve button and if set player is out of the material the item will be grayed out the example below
![Screenshot_20210119_235230_com bikedamowang gg](https://user-images.githubusercontent.com/52991546/105254064-bcea9900-5b4e-11eb-9b7e-4a3e8625adf6.jpg)

**Comment by Ragingsura** [comment]
@insthync ???

**Comment by insthync** [comment]
For now it cannot, Have to add codes to calculate amount of item and exp to make it works.
