### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#116]
Hello Suriyun!
When attacking with a skill, on a character on which this skill is already in effect, the effect remains, even after completion turns...
And another question, when is the next update, what will it contain?

**Comment by insthync** [comment]
It will includes
- Clan chat
- Clan level/exp
- Clan donation
- Raid boss

It may be published before 15 Feb

**Comment by dclgamingtr** [comment]
Can you add the leaderboard in the next update.

**Comment by brabaris** [comment]
A leaderboard would be awesome, and also a password and email confirmation at registration ... Thanks!

**Comment by brabaris** [comment]
There is also a bug, when after a loss you press "GIVE UP", but there is not enough stamina, an empty field in the window with an error.

![1](https://user-images.githubusercontent.com/16080577/105878366-a4282a80-6009-11eb-827f-17384f2633c3.jpg)
