### ISSUE TITLE
Big bug!

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#117]
It is impossible to "Give Up" when there is no stamina left, but at the same time you can "Revive" without writing off the stamina! In general, "Revive" is a very cheating thing, it turns out it needs to be limited somehow!
Attached video...
https://youtu.be/CkF4c6D0gcI

**Comment by insthync** [comment]
It can consume hard currency when reviving, but  I'm okay to add the option to consume stamina when reviving.

**Comment by brabaris** [comment]
Better hard currency, so that you can enter the amount of hard currency per revival in the GameDatabase ...

**Comment by insthync** [comment]
You can set it at Game Database -> Revive Price 

![Screenshot_182](https://user-images.githubusercontent.com/2697550/106015461-1889c900-60f1-11eb-94d8-e442afb36280.png)

**Comment by brabaris** [comment]
Wow! How I missed it! Thank you! And what about Restart when stamina is not enough (Empty window with error )?

**Comment by insthync** [comment]
I will fix it later.

**Comment by brabaris** [comment]
ok!
