### ISSUE TITLE
I connect advertising for a reward ... 

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#118]
Hi, I'm trying to connect advertising for a reward (after watching a commercial, + 1 stamina is added), but I don't understand ... 

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GoogleMobileAds.Api;
using System;

public class GoogleRewardAD : MonoBehaviour
{
    private RewardedAd rewardedAd;

    public void Start()
    {

        string adUnitId = "ca-app-pub-3940256099942544/5224354917";
        this.rewardedAd = new RewardedAd(adUnitId);

        // Called when an ad request has successfully loaded.
        this.rewardedAd.OnAdLoaded += HandleRewardedAdLoaded;
        // Called when an ad request failed to load.
        this.rewardedAd.OnAdFailedToLoad += HandleRewardedAdFailedToLoad;
        // Called when an ad is shown.
        this.rewardedAd.OnAdOpening += HandleRewardedAdOpening;
        // Called when an ad request failed to show.
        this.rewardedAd.OnAdFailedToShow += HandleRewardedAdFailedToShow;
        // Called when the user should be rewarded for interacting with the ad.
        this.rewardedAd.OnUserEarnedReward += HandleUserEarnedReward;
        // Called when the ad is closed.
        this.rewardedAd.OnAdClosed += HandleRewardedAdClosed;

        // Create an empty ad request.
        AdRequest request = new AdRequest.Builder().Build();
        // Load the rewarded ad with the request.
        this.rewardedAd.LoadAd(request);
        
    }

    public void HandleRewardedAdLoaded(object sender, EventArgs args)
    {
        MonoBehaviour.print("HandleRewardedAdLoaded event received");
    }

    public void HandleRewardedAdFailedToLoad(object sender, AdErrorEventArgs args)
    {
        MonoBehaviour.print(
            "HandleRewardedAdFailedToLoad event received with message: "
                             + args.Message);
    }

    public void HandleRewardedAdOpening(object sender, EventArgs args)
    {
        MonoBehaviour.print("HandleRewardedAdOpening event received");
    }

    public void HandleRewardedAdFailedToShow(object sender, AdErrorEventArgs args)
    {
        MonoBehaviour.print(
            "HandleRewardedAdFailedToShow event received with message: "
                             + args.Message);
    }

    public void HandleRewardedAdClosed(object sender, EventArgs args)
    {
        MonoBehaviour.print("HandleRewardedAdClosed event received");
    }

    public void HandleUserEarnedReward(object sender, Reward args)
    {
        // +1 Stamina REWARD
    }

    public void ViewRewardClip()
    {
        if (this.rewardedAd.IsLoaded())
        {
            this.rewardedAd.Show();
        }
    }

}`

**Comment by dclgamingtr** [comment]
You did not write the reward codes.

**Comment by brabaris** [comment]
I don’t understand this ... Need help!
public void HandleUserEarnedReward(object sender, Reward args)
{
    // +1 Stamina REWARD
}

**Comment by dclgamingtr** [comment]
At the same time, code must be added in the php section. So it's a little bit not easy. We are working on it, but Suriyun may help.

**Comment by brabaris** [comment]
That's right, but Mr. Suriyun is silent ...

**Comment by insthync** [comment]
Are you using Php service ?

**Comment by brabaris** [comment]
Of course!

**Comment by insthync** [comment]
You will have to connect to PHP service to tell it to add rewards, so you will have to add new function for PHP service to add player's rewards too.

**Comment by brabaris** [comment]
This is understandable, but no one knows how to implement it ... It will be very good if you do this for a small reward $

**Comment by insthync** [comment]
So if no one knows PHP codes, let's me do it later, you actually can see codes which relates to stamina refilling in `functions/Item.php` -> `RefillStamina` function.

When you are going to add new functions for the service, you have to to it in `index.php`, find for functions name such as `'enter-chat-message'` to find out how to do it.

**Comment by brabaris** [comment]
Greetings! I still don't understand what to write in function RewardStamina ($ staminaDataId) (Item.php)
I try through $ playerStamina-> amount ++; Shows error OnGameServiceError: ERROR_UNKNOW
