### ISSUE TITLE
need help with online

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#119]
Hello good I would like to know if someone could help me better understand how to put the online with the php

**Comment by dclgamingtr** [comment]
Hello, contact me on discord. My account name has changed.  " TrDippeR#0550 " Discord name.

**Comment by surycr** [comment]
https://discord.gg/RHe2cN9k6V  i make a chanel bc i dont have u with friend

**Comment by dclgamingtr** [comment]
PHP has been installed. There was a database import problem.
The problem disappeared when it was reinstalled. Please install using sql-importer.php.
Otherwise, if you manually install mysql, it will fail. Use the setup tool. :) 
The problem has disappeared. The topic may be closed.

**Comment by insthync** [comment]
@surycr Are you able to host web-service on PHP web-hosting?
