### ISSUE TITLE
Reward for viewing ads.

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#121]
Hello Suriyun! You need to make a reward for viewing ads. I tried, I couldn't get +1 to stamina (via the web service) ... How much will the money cost and what are the terms? I am attaching the GoogleRewardedAD.cs script itself. 
[GoogleRewardedAD.txt](https://github.com/suriyun-production/turnbase-rpg-docs/files/5950035/GoogleRewardedAD.txt)

**Comment by insthync** [comment]
Okay, I will help you develop it as open source extension, so if you want to pay me you can do it via my ko-fi (https://ko-fi.com/insthync). About amount, as you wish :).

**Comment by brabaris** [comment]
Thank you! When will the plugin be ready? (roughly ...)

**Comment by insthync** [comment]
Can you wait in this weekend, I am working on new update for the turnbase project

**Comment by brabaris** [comment]
Ok!

**Comment by brabaris** [comment]
Don't forget about the error (blank window when trying to give up but lacking stamina) that I showed in the video.

**Comment by dclgamingtr** [comment]
Hello, I have added the feature of watching ads and earning diamonds you want. You can set a certain time period and watch ads. 
I shared it on Discord, you can check it if you want to take a look.

**Comment by brabaris** [comment]
Hey! Well, that's not quite right ... And where in discord can you download it? Something I don't see ...

**Comment by dclgamingtr** [comment]
Send me your email address.

**Comment by brabaris** [comment]
medik.evgeniy@gmail.com

**Comment by HajiyevEl** [comment]
> 
> 
> Send me your email address.

Hi dclgamingtr! Can you give me discord so that i can download it too, please?

**Comment by brabaris** [comment]
Hello Suriyun! How are things going with the update?

**Comment by insthync** [comment]
Update to [latest version (1.16)](https://www.suriyun.com/tbrpg/) then setup https://github.com/insthync/unity-tbrpg-google-ads and https://github.com/insthync/rpg-php-service-google-ads

**Comment by brabaris** [comment]
Suriyun, here you need an invoice number ... (for download)

**Comment by brabaris** [comment]
Understood, the invoice from assetstore ...

**Comment by brabaris** [comment]
Loading does not work, empty page and that's it!
![1](https://user-images.githubusercontent.com/16080577/107920236-45edc800-6f75-11eb-8398-7d2bd35ec74e.jpg)

**Comment by brabaris** [comment]
In Google Chrome:
![2](https://user-images.githubusercontent.com/16080577/107921724-97975200-6f77-11eb-86ad-03b39ebb5924.jpg)

**Comment by insthync** [comment]
Okay, I will fix it.

**Comment by insthync** [comment]
Done.

**Comment by brabaris** [comment]
I downloaded it, I will try, I will write! Thank!

**Comment by brabaris** [comment]
If the balance of coins is zero, there will be an empty window with an error.
![Uploading 1.jpg…]()

**Comment by brabaris** [comment]
How to join a clan?
![2](https://user-images.githubusercontent.com/16080577/107965406-2aa1ad80-6fb3-11eb-98ab-1ede42543020.jpg)

**Comment by insthync** [comment]
> 

Whats error ?

**Comment by insthync** [comment]
> How to join a clan?
> ![2](https://user-images.githubusercontent.com/16080577/107965406-2aa1ad80-6fb3-11eb-98ab-1ede42543020.jpg)

Change condition in `UIClan.cs` -> `UpdateData` function
```

    public override void UpdateData()
    {
        SetupInfo(data);
        if (buttonJoinRequest != null)
        {
            buttonJoinRequest.onClick.RemoveListener(OnClickJoinRequest);
            buttonJoinRequest.onClick.AddListener(OnClickJoinRequest);
            buttonJoinRequest.interactable = !IsEmpty() && !Player.CurrentPlayer.JoinedClan;
        }
        if (buttonJoinRequestDelete != null)
        {
            buttonJoinRequestDelete.onClick.RemoveListener(OnClickJoinRequestDelete);
            buttonJoinRequestDelete.onClick.AddListener(OnClickJoinRequestDelete);
            buttonJoinRequestDelete.interactable = !IsEmpty() && !Player.CurrentPlayer.JoinedClan;
        }
```

**Comment by brabaris** [comment]
Suriyun, Need help!

**Comment by brabaris** [comment]
I'm going to record a video ...

**Comment by brabaris** [comment]
I had a problem (I don’t understand what it’s connected with), everything is fine in the editor, but on the phone it does not switch to ManageScene, and that's it!
The problem is still on version 1.15c

**Comment by brabaris** [comment]
Understood ... the problem was in StoreID ...

**Comment by insthync** [comment]
Yeah, I know you need help, but I don't know what is happened.

**Comment by brabaris** [comment]
Hello Suriyun! Everything is fine, today I will add ads.
Question: Why should a clan increase experience for resources (hard, soft currency)? Will there be any clan battles?

**Comment by insthync** [comment]
Follow these requests: https://github.com/suriyun-production/turnbase-rpg-docs/issues/99

No plan for clan battle yet, but it will have a clan raid boss.

**Comment by brabaris** [comment]
The UpdateData function should look something like this: (UIClan.cs) 

  public override void UpdateData()
    {
        SetupInfo(data);
        if (buttonJoinRequest != null)
        {
            buttonJoinRequest.onClick.RemoveListener(OnClickJoinRequest);
            buttonJoinRequest.onClick.AddListener(OnClickJoinRequest);
            buttonJoinRequest.interactable = !IsEmpty() && !Player.CurrentPlayer.JoinedClan;
        }
        if (buttonJoinRequestDelete != null)
        {
            buttonJoinRequestDelete.onClick.RemoveListener(OnClickJoinRequestDelete);
            buttonJoinRequestDelete.onClick.AddListener(OnClickJoinRequestDelete);
            buttonJoinRequestDelete.interactable = !IsEmpty() && !Player.CurrentPlayer.JoinedClan;
        }
        if (buttonTerminate != null)
        {
            buttonTerminate.onClick.RemoveListener(OnClickTerminate);
            buttonTerminate.onClick.AddListener(OnClickTerminate);
            buttonTerminate.interactable = !IsEmpty() && Player.CurrentPlayer.IsClanLeader && Player.CurrentPlayer.ClanId.Equals(data.Id);
        }
        if (buttonExit != null)
        {
            buttonExit.onClick.RemoveListener(OnClickExit);
            buttonExit.onClick.AddListener(OnClickExit);
            buttonExit.interactable = !IsEmpty() && !Player.CurrentPlayer.IsClanLeader && Player.CurrentPlayer.ClanId.Equals(data.Id);
        }
    }
Otherwise the "Exit", "Terminate" buttons will not work.

**Comment by brabaris** [comment]
Suriyun, Need help!
The reward does not work ... I did everything according to your readme ... I am attaching screenshots.
GameData.json exported ...

![1](https://user-images.githubusercontent.com/16080577/108088747-7d499b00-7081-11eb-9ebe-77943596ef39.jpg)
![2](https://user-images.githubusercontent.com/16080577/108088756-7f135e80-7081-11eb-9041-5ccb316a4e58.jpg)
![3](https://user-images.githubusercontent.com/16080577/108088762-8175b880-7081-11eb-80f0-8f6501e73eef.jpg)
![4](https://user-images.githubusercontent.com/16080577/108088768-82a6e580-7081-11eb-8432-74b7f96a9f0f.jpg)
![5](https://user-images.githubusercontent.com/16080577/108088773-8470a900-7081-11eb-8797-dfc716d17a9d.jpg)
![6](https://user-images.githubusercontent.com/16080577/108088779-863a6c80-7081-11eb-8cf2-4717f76a7a3a.jpg)
![7](https://user-images.githubusercontent.com/16080577/108088787-876b9980-7081-11eb-8c8f-182b2299e1e4.jpg)
![8](https://user-images.githubusercontent.com/16080577/108088798-89355d00-7081-11eb-8b8c-ff2fc1fe9093.jpg)

**Comment by insthync** [comment]
Try re-download and import this https://github.com/insthync/unity-tbrpg-google-ads, I just fix missing login token.

**Comment by brabaris** [comment]
It still doesn't work! (Adds NOTHING after watching ads)
Maybe you still need to register ID in the script ?!
![5](https://user-images.githubusercontent.com/16080577/108254282-7b580880-7163-11eb-94af-fe70ce7fd91d.jpg)

**Comment by insthync** [comment]
ID must be this value (from abmob dashboard)
![Screenshot_209](https://user-images.githubusercontent.com/2697550/108291196-69f31880-71c4-11eb-96fb-670fdda314c8.png)
So yours must be `Reward`

And you have to export game data to your back end

**Comment by brabaris** [comment]
Does not work! I did everything according to the instructions ... I exported GameData.json.
ID: Reward and amount: 10 - DOES NOT CHANGE! (I have ID: stamina / amount: 1)
No connection with GameDatabase? 
![1](https://user-images.githubusercontent.com/16080577/108319332-e9371b00-71c9-11eb-8125-58b0345b31ba.jpg)
![2](https://user-images.githubusercontent.com/16080577/108319338-eb00de80-71c9-11eb-94d9-367d2a4cf755.jpg)
![3](https://user-images.githubusercontent.com/16080577/108319341-ec320b80-71c9-11eb-835a-1ef609cdbcd0.jpg)
![4](https://user-images.githubusercontent.com/16080577/108319345-ed633880-71c9-11eb-835e-b31daf6fc0d1.jpg)

**Comment by insthync** [comment]
I don't know why its type is `Reward`, codes when it got reward type is in `GoogleRewardedAd.cs` -> `RewardedAd_OnUserEarnedReward`, I won't touch Google's stuff, you may try to hack it by set reward Id to `Reward`.

**Comment by insthync** [comment]
Not sure that GoogleAd still working as test mode or not then it still uses testing ads unit which returning type is `Reward`.

**Comment by brabaris** [comment]
Maybe TeamViewer?

**Comment by insthync** [comment]
This weekend, Okay ?

**Comment by brabaris** [comment]
And it won't work before?

**Comment by insthync** [comment]
I actually didn't test it yet.

**Comment by brabaris** [comment]
Ok! I'll wait!

**Comment by brabaris** [comment]
You are a cool programmer! Thank you so much!
