### ISSUE TITLE
What is AuthList and FakePlayers?

### ISSUE THREAD

**Issue by HajiyevEl** [suriyun-production/turnbase-rpg-docs#124]
?

**Comment by insthync** [comment]
Auth list is social platform account list for authentication, for example, if player Id: `001` logged in or linked with facebook and twitter, this list will contains `[{"playerId":"001", "type":"{facebookType}", "username":"{facebookId}"}, {"playerId":"001", "type":"{twitterType}", "username":"{twitterId}"}]

FakePlayer is a mockup player for helper list when entering stage and for an opponent when entering arena, it is useful for an offline game which no real players and an online game that just launched and not have a lot of players.

**Comment by HajiyevEl** [comment]
> 
> 
> Auth list is social platform account list for authentication, for example, if player Id: `001` logged in or linked with facebook and twitter, this list will contains `[{"playerId":"001", "type":"{facebookType}", "username":"{facebookId}"}, {"playerId":"001", "type":"{twitterType}", "username":"{twitterId}"}]
> 
> FakePlayer is a mockup player for helper list when entering stage and for an opponent when entering arena, it is useful for an offline game which no real players and an online game that just launched and not have a lot of players.

Nice! Is there a  difference between bots in arena and fake player? By the way, what is "helper list"?

**Comment by insthync** [comment]
Helper list is other player's character which will join your team when enter battle

**Comment by HajiyevEl** [comment]
> 
> 
> Helper list is other player's character which will join your team when enter battle

Didn't quite get it but thanks for answer. I will look into it later.
