### ISSUE TITLE
Can you please comment your scripts in next update?

### ISSUE THREAD

**Issue by HajiyevEl** [suriyun-production/turnbase-rpg-docs#125]
I have very, VERY hard time digging your scripts trying to understand what part does what. It's so pain in the ass to follow every unknown variable to root and go through all project trying to find if it's being used somewhere else.

By the way, to see you updating UI elements in "void Update" (UILevel.cs) was mindblowing experience. Hadn't seen this approach since the time i was newbie looking through beginner tutorials.

I can't understand what do you mean when you write something like "CollectExp - IncreasingExp". What does mean "CollectExp"? Or "IncreasingExp"?

I understand that english maybe not your native, but at least write comments on your native language so we can just google translate it. It's still better than to just guess what the hell does this variables do. 

Sorry if i'm being rude, but as buyer i cannot help but express my dissatisfaction with the product which I paid for.

Can you comment something please?

**Comment by insthync** [comment]
`CollectExp` is collected exp before level up to next level. 
For example: if you see: 15/20, `CollectExp` is `15`, `NextExp` is `20`, 
If you are going to consume item to increase 3 exp, then `IncreasingExp` is `3`. `CollectExp` is `18`

I don't usually write code's comment if it's understandable (to me and my team) by variable name, function name. 
You can tell me where I should add comment. I'm good to do follows your request.
