### ISSUE TITLE
improving the quality of the model viewer

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#126]
I've tried to adjust the models so many times but it still looks pixelated even the regular model looks pixelated.
![Unity_UjKF3km62w](https://user-images.githubusercontent.com/52991546/107921262-46b63800-6f3c-11eb-964a-44e203edae4d.png)
![Unity_6lyQq6Uams](https://user-images.githubusercontent.com/52991546/107921268-487ffb80-6f3c-11eb-8996-e95a72fab620.png)

**Comment by insthync** [comment]
IF you are modifying from demo, try change `CharacterViewer` render texture settings

![Screenshot_205](https://user-images.githubusercontent.com/2697550/107923710-726d0880-6fa4-11eb-87a1-a165a3a67441.png)

![Screenshot_206](https://user-images.githubusercontent.com/2697550/107923716-7567f900-6fa4-11eb-9cc8-3ac06d80f243.png)

**Comment by Ragingsura** [comment]
thank you
