### ISSUE TITLE
Can't access TMPro namespace from project scripts.

### ISSUE THREAD

**Issue by HajiyevEl** [suriyun-production/turnbase-rpg-docs#127]
Like i said, somehow i can't access TMPro namespace from scripts of your project. What could be the problem?

P.S. I have bought GUI asset from assetstore which uses TMPro for your template, that's when i run into this problem.  TMPro namespace can be accessed from GUI package scripts tho.

Tried uninstalling => installing again TMPro package, didn't worked.

**Comment by HajiyevEl** [comment]
Solved. Included "Unity.TextMeshPro.asmdef" and "Unity.TextMeshPro.Editor.asmdef" into "BaseRPG.asmdef" Assembly Definition References.

**Comment by Muphet** [comment]
i had literaly the same problem when i tried to replace GUI with one that uses tmpro and suddenly tmpro couldn't be accessed in scripts like ui level. i was pulling my hairs but this is exactly the help i needed <3
