### ISSUE TITLE
Suggestion/Question

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/turnbase-rpg-docs#129]
Did you plan add somethink like endless tower? Will be good if this possible =)

**Comment by Ragingsura** [comment]
already asked him for this feature and more but their team focus is in mmorpg-Kit so we will most likely get out next update in 6 months with 2 add features.

**Comment by insthync** [comment]
@Ragingsura Do you think after I read your complaining like this I will want to do it for you ?
No it is not, it's very annoying.
I just uploaded new update 3 days ago, and going to add raid boss battle which you can see progress in https://github.com/insthync/rpg-php-service -> commit history.
And for endless tower you actually can use stage system with custom stamina setting and first clear reward settings do to it.

**Comment by insthync** [comment]
And I have no team, I do it all alone, that's why it is slow, and your irony will make it slower. 
I use MMORPG KIT to develop my game that's why it's faster but nowadays it didn't have a new feature update yet, there is just bug fixing.

**Comment by Ragingsura** [comment]
> @Ragingsura Do you think after I read your complaining like this I will want to do it for you ?
> No it is not, it's very annoying.
> I just uploaded new update 3 days ago, and going to add raid boss battle which you can see progress in https://github.com/insthync/rpg-php-service -> commit history.
> And for endless tower you actually can use stage system with custom stamina setting and first clear reward settings do to it.

my comment is not meant as me not been grateful for the update what i did was answer his question because I already asked you for most of the necessary features. What i said is true because i own all your asset and see what gets updated and what doesn't and every week MMORPG-kit gets 1 major update with bug fixes and added features sometimes every 2-3 update a week so what I said is not me been rude and not been grateful for the update but just sad that you put more effort into one asset that's in a state where you can actually make a game from it at this point.

**Comment by Ragingsura** [comment]
> And I have no team, I do it all alone, that's why it is slow, and your irony will make it slower.
> I use MMORPG KIT to develop my game that's why it's faster but nowadays it didn't have a new feature update yet, there is just bug fixing.

from what someone told me in the discord community they said you're working with a team so i didn't know you work alone.

**Comment by insthync** [comment]
Okay, nevermind, let's do it, I will add the tower system to the demo.

**Comment by insthync** [comment]
Added the tower to 1.16b, if you want it now you can download it at: https://www.suriyun.com/tbrpg/
Sorry if today I may rude to you guys.
Okay, get back to working on raid-boss.
