### ISSUE TITLE
Test payments in Google fail! 

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#130]
Test payments in Google fail! Although in the Unity Dashboard, purchases allegedly go through. Messages come to the mail: Test purchase canceled due to lack of confirmation. You must confirm all purchases. If this is not done, the funds will be returned to customers. More details: https://developer.android.com/google/play/billing/integrate#process.
How to confirm purchases ?! What the hell is going on ?!
The game is in internal testing at Google...
What am I doing wrong?!
![1](https://user-images.githubusercontent.com/16080577/108212027-1639ee00-7136-11eb-9e74-41844181bed7.jpg)
![2](https://user-images.githubusercontent.com/16080577/108212037-189c4800-7136-11eb-982e-f16e9a9fcd08.jpg)
![3](https://user-images.githubusercontent.com/16080577/108212040-1a660b80-7136-11eb-9b54-e4d834c62091.jpg)

I attach a video from the phone: 
https://youtu.be/8baVlh0wKhU

**Comment by insthync** [comment]
Did you export new game data to the web-service?

**Comment by brabaris** [comment]
Of course, 300 times already!

**Comment by insthync** [comment]
You don't have to tell me how many times you did.

**Comment by insthync** [comment]
You may try debugging by add data to web-service response

in `functions/Billing.php` -> function `AndroidBuyGoods` you may change output like this
```
    // Use product id to find package in game data
    if (empty($packageData))
    {
        $output['error'] = 'ERROR_INVALID_IAP_PACKAGE_DATA';
        $output['error_'] = '0 '.$packageData['googlePlayId'].' '.$productId;
    }
    else if ($packageData['googlePlayId'] != $productId)
    {
        $output['error'] = 'ERROR_INVALID_IAP_PACKAGE_DATA';
        $output['error_'] = '1 '.$packageData['googlePlayId'].' '.$productId;
    }
```

Then see which `error_` value is, then find a way to fix it later.

**Comment by brabaris** [comment]
There is no error value, everything is the same, after payment an error appears, and 2 messages in the mail. First message:
"You made a purchase from a FastCore Independent Game Developer retailer on Google Play."
And the second message: "Test purchase canceled due to lack of confirmation. You must confirm all purchases. If you do not, the funds will be refunded to customers. More details: https://developer.android.com/google/play/billing/integrate# process. "

![Screenshot_2021-02-18-11-09-55-276_com fastcore squadofheroes](https://user-images.githubusercontent.com/16080577/108334446-9e71cf00-71da-11eb-88ea-ef46a9a33166.jpg)

**Comment by brabaris** [comment]
You are a cool programmer!  Thank you so much!
