### ISSUE TITLE
event category 

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#131]
can you add a category to the event system?  so i will be able to put a set of events of different ui.

**Comment by insthync** [comment]
Yes, you can uses `Stage` -> `tag` setting then when changing category (maybe by using `Toggle` UIs) you can change `UIStageList` -> `stageTags` and call `Show()` function to refresh stage list.

**Comment by Ragingsura** [comment]
> Yes, you can uses `Stage` -> `tag` setting then when changing category (maybe by using `Toggle` UIs) you can change `UIStageList` -> `stageTags` and call `Show()` function to refresh stage list.

thanks you

**Comment by Ragingsura** [comment]
one more thing I see custom currency but don't know how to make use of it
