### ISSUE TITLE
How to show UIAttributes in Equipment?

### ISSUE THREAD

**Issue by xcygame** [suriyun-production/turnbase-rpg-docs#132]
Hello suriyun, 

Now, we can view the equipment attributes only in the inventory, but this is not convenient.

Maybe we can see the equipment attributes while wearing the equipment. 
![0](https://user-images.githubusercontent.com/41316408/108745587-3aeaf700-7576-11eb-968e-125bd1492c53.jpg)

Or you have any good suggestions?

Thanks.

**Comment by insthync** [comment]
Like showing popup after selected item?

**Comment by xcygame** [comment]
Yes, you're right. Is there any way to do it?

**Comment by xcygame** [comment]
> Like showing popup after selected item?

Yes, you're right. Is there any way to do it?

**Comment by insthync** [comment]
- Create the popup which attached `UIItem` component, then set an settings

![Screenshot_227](https://user-images.githubusercontent.com/2697550/108798644-df922680-75c0-11eb-918e-ee76c0fdaa12.png)

- Then in `UIItemList` component, set `EventSelect` and `EventDelesect` to set the popup data and show it

![Screenshot_228](https://user-images.githubusercontent.com/2697550/108798655-e5880780-75c0-11eb-8d19-0e0137a585ee.png)

**Comment by xcygame** [comment]
I want to display the item information in "uiequipment manager". Here are my steps. But it doesn't show. Did I miss something?
1.I create a text to display item information
![1](https://user-images.githubusercontent.com/41316408/108800331-c5ab1080-75cd-11eb-9382-3e25eb8d85cd.jpg)
2.Setting Event
![2](https://user-images.githubusercontent.com/41316408/108800338-ca6fc480-75cd-11eb-89be-2772b1a80812.jpg)
3.But it doesn't show
![3](https://user-images.githubusercontent.com/41316408/108800346-ce9be200-75cd-11eb-8392-c93ae5fb5c69.jpg)

**Comment by insthync** [comment]
Did you set the text to UIItem?

**Comment by xcygame** [comment]
Yes ,i did it. Just like in the screenshot.

**Comment by insthync** [comment]
I mean you set `Text` to `UIItem` -> `TextTitle` or something?

**Comment by xcygame** [comment]
My text just add UIitem Script, then drag and drop to UIItemList event

**Comment by insthync** [comment]
Try set text to this 
![Screenshot_229](https://user-images.githubusercontent.com/2697550/108801538-91812100-75c8-11eb-969d-5a24caf24a36.png) 

(In UIItem)

**Comment by xcygame** [comment]
I put "myText" to myText's UIitem,it not work.
![11](https://user-images.githubusercontent.com/41316408/108803590-09097d00-75d6-11eb-8a42-f93fec3a36da.jpg)

and try to put "myText "  to UIInfo's UIitem,it not work too.
![22](https://user-images.githubusercontent.com/41316408/108803597-10308b00-75d6-11eb-8864-2ab63c8f6dfd.jpg)

It's strange

**Comment by insthync** [comment]
Okay, try replace codes in `UIDataItem.cs` to 
```
using UnityEngine;
using UnityEngine.Events;

public enum UIDataItemClickMode
{
    Default,
    Selection,
    Disable,
}

[System.Serializable]
public class UIDataItemEvent : UnityEvent<UIDataItem> { }

public abstract class UIDataItem : UIBase
{
    // Decoration
    public bool selected;
    protected bool dirtySelected;
    public GameObject selectedObject;
    public GameObject emptyInfoObject;
    // Events
    public UIDataItemClickMode clickMode = UIDataItemClickMode.Default;
    public UIDataItemEvent eventClick;
    public UIDataItemEvent eventSelect;
    public UIDataItemEvent eventDeselect;
    public UIDataItemEvent eventUpdate;
    public abstract object GetData();
    public abstract void SetData(object data);
    public abstract void ForceUpdate();
    [HideInInspector]
    public UIList list;

    public virtual bool Selected
    {
        get { return selected; }
        set { selected = value; }
    }
}

public abstract class UIDataItem<T> : UIDataItem
{
    // Data
    public T data;
    protected T dirtyData;

    public bool IsDirty()
    {
        if (typeof(T).IsClass)
        {
            if ((data == null && dirtyData != null) || (data != null && dirtyData == null))
                return true;
            return data != null && !data.Equals(dirtyData);
        }
        return !data.Equals(dirtyData);
    }

    protected override void Awake()
    {
        base.Awake();
        if (selectedObject != null)
            selectedObject.SetActive(false);
        if (emptyInfoObject != null)
            emptyInfoObject.SetActive(false);
    }

    protected virtual void Update()
    {
        if (IsDirty())
            UpdateLogic();

        if (Selected != dirtySelected)
        {
            if (selectedObject != null)
                selectedObject.SetActive(Selected);
            dirtySelected = Selected;
        }

        if (emptyInfoObject != null)
            emptyInfoObject.SetActive(IsEmpty());
    }

    private void UpdateLogic()
    {
        Clear();
        UpdateData();
        dirtyData = data;
        eventUpdate.Invoke(this);
    }

    public override sealed void ForceUpdate()
    {
        UpdateLogic();
    }

    public virtual void OnClick()
    {
        switch (clickMode)
        {
            case UIDataItemClickMode.Selection:
                if (list == null ||
                    list.limitSelection <= 0 ||
                    list.SelectedAmount < list.limitSelection ||
                    Selected)
                {
                    Selected = !Selected;
                    if (Selected)
                        Select();
                    else
                        Deselect();
                }
                break;
            case UIDataItemClickMode.Default:
                Click();
                break;
        }
    }

    public virtual void Select(bool invokeEvent = true)
    {
        Selected = true;
        if (invokeEvent)
            eventSelect.Invoke(this);
    }

    public virtual void Deselect(bool invokeEvent = true)
    {
        Selected = false;
        if (invokeEvent)
            eventDeselect.Invoke(this);
    }

    public virtual void Click(bool invokeEvent = true)
    {
        Selected = false;
        if (invokeEvent)
            eventClick.Invoke(this);
    }

    public override object GetData()
    {
        return data;
    }

    public override void SetData(object newData)
    {
        data = (T)newData;
        ForceUpdate();
    }

    public void CopyDataFromUI(UIDataItem ui)
    {
        SetData(ui.GetData());
    }

    public abstract void UpdateData();
    public abstract void Clear();
    public abstract bool IsEmpty();
}
```

Then in `Event Select` change `UIItem.SetData` to `UIItem.CopyDataFromUI`

**Comment by xcygame** [comment]
wow ! It worked. Thank you for your help.
