### ISSUE TITLE
List of modified scripts in new updates, please?

### ISSUE THREAD

**Issue by HajiyevEl** [suriyun-production/turnbase-rpg-docs#133]
Hi Suriyun!

I have modified most of scripts in project, so if possible, can you make list of scripts (names) which you modified in new updates? Just don't want my project to break when you release new update. Simple list of modified scripts for each new update is enough, i will know which scripts i should update in my project. Thanks!

**Comment by insthync** [comment]
From which package version?, you should use git because after you imported new version files it can tell you which files have changed

**Comment by HajiyevEl** [comment]
> 
> 
> From which package version?, you should use git because after you imported new version files it can tell you which files have changed

Yeah, this seems the only solution...
