### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by HajiyevEl** [suriyun-production/turnbase-rpg-docs#134]
Why i can see only "Weekend Event" in events list? Do i miss something? How to set events?

**Comment by insthync** [comment]
Stage event data is the same as `Stage` data but it has an availabilities setting 

![Screenshot_245](https://user-images.githubusercontent.com/2697550/109407281-22ce0a00-79b2-11eb-88e6-36b7862f0483.png)

and tag

![Screenshot_246](https://user-images.githubusercontent.com/2697550/109407283-26619100-79b2-11eb-964f-6c84e562f492.png)

Then in ManageScene -> ManageSceneManager -> UIEvents there is a attached component: `UIStageList` which uses tag for listing filtering

![Screenshot_247](https://user-images.githubusercontent.com/2697550/109407310-704a7700-79b2-11eb-81e2-62e88b5d87b3.png)

You may be not set `tag`

**Comment by HajiyevEl** [comment]
> 
> 
> Stage event data is the same as `Stage` data but it has an availabilities setting
> 
> ![Screenshot_245](https://user-images.githubusercontent.com/2697550/109407281-22ce0a00-79b2-11eb-88e6-36b7862f0483.png)
> 
> and tag
> 
> ![Screenshot_246](https://user-images.githubusercontent.com/2697550/109407283-26619100-79b2-11eb-964f-6c84e562f492.png)
> 
> Then in ManageScene -> ManageSceneManager -> UIEvents there is a attached component: `UIStageList` which uses tag for listing filtering
> 
> ![Screenshot_247](https://user-images.githubusercontent.com/2697550/109407310-704a7700-79b2-11eb-81e2-62e88b5d87b3.png)
> 
> You may be not set `tag`

So that's how it works, thanks!
