### ISSUE TITLE
Rarity, Roles and Rating 

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#135]
can you change how the rarity of items and character work especially the rarity icon and item/character icon it would be nice if they get separated so it will make it easy instead of having 1 icon for every rarity?
![BlackKnight](https://user-images.githubusercontent.com/52991546/109389962-dd8bd880-78dc-11eb-83f4-002e0e97f9cd.png)
![BlackKnight](https://user-images.githubusercontent.com/52991546/109389972-e54b7d00-78dc-11eb-81f1-8d7d8761b65b.png)

can you add roles to the characters to differentiate them from each other like a rock, paper scissor system 
ex- tank, damage, support, or even element  fire, earth, water, and air
![da75a602efac5d602ae1b1adf1921bedcc02d4c9r1-882-509v2_uhq](https://user-images.githubusercontent.com/52991546/109390222-4f185680-78de-11eb-906e-a8f551f370de.jpg)

and lastly, can you add a rating system for the  characters
ex either in the form of stars that goes up as you evolve or this rating system UR, SSS, SR, R  OR SSS, SS, S, A, B, 
![langrisser](https://user-images.githubusercontent.com/52991546/109390549-593b5480-78e0-11eb-8024-13b8b5788e42.jpg)
![maxresdefault](https://user-images.githubusercontent.com/52991546/109390553-5b9dae80-78e0-11eb-93c1-84232fed3e08.jpg)

**Comment by insthync** [comment]
There is a thing which works the same as `Role` it is `Elemental`

![Screenshot_248](https://user-images.githubusercontent.com/2697550/109407411-24e49880-79b3-11eb-90b1-62182124407f.png)

which can be created by ScriptableObject menu

![Screenshot_249](https://user-images.githubusercontent.com/2697550/109407464-99b7d280-79b3-11eb-9dfb-3207f928986a.png)

**Comment by insthync** [comment]
About the icon's frame, in the next version, you may set the frame to `ItemTier` -> `Icon`

![Screenshot_250](https://user-images.githubusercontent.com/2697550/109407716-96bde180-79b5-11eb-9bd2-8308ffd987f8.png)

And in `UIItem`  component, it will have the `imageTierIcon` setting which you can set frame image component

![Screenshot_251](https://user-images.githubusercontent.com/2697550/109407729-de446d80-79b5-11eb-9122-ff150eb7eb69.png)

**Comment by Ragingsura** [comment]
@insthync could not find the tier option shown in the image on the UIItem component and yes am using the latest version 
![Unity_6ca4vQbpaN](https://user-images.githubusercontent.com/52991546/109413188-2ba2e980-797a-11eb-8864-658ee75970df.png)

**Comment by insthync** [comment]
I said "In the next version"

**Comment by Ragingsura** [comment]
> I said "In the next version"

sorry did not read that part
