### ISSUE TITLE
Version 1.16c BUG \ Suggestions \ Questions

### ISSUE THREAD

**Issue by xcygame** [suriyun-production/turnbase-rpg-docs#136]
Hi Suriyun,

**Bug**:

I found a bug in version 1.16c ,player can't equip item.

**Suggestions**:

But I think it's an opportunity to add "Equip" and "Unequip" buttons.
When select item ,can show them.
![0](https://user-images.githubusercontent.com/41316408/109517067-d71b7d80-7ae3-11eb-8f76-4b96cfe97a08.jpg)

**Questions**:

I'm not sure the current version can add these two button methods. Please let me know if it can already.

Thank you.

**Comment by insthync** [comment]
[TBRPG_Fix_DontDeactivateIcons.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/6062689/TBRPG_Fix_DontDeactivateIcons.zip)

Import this package to fix the issue

**Comment by xcygame** [comment]
> [TBRPG_Fix_DontDeactivateIcons.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/6062689/TBRPG_Fix_DontDeactivateIcons.zip)
> 
> Import this package to fix the issue

Thanks. It worked.

But I also want to know, if I add the above two buttons, is there any way to do it in the current version?
