### ISSUE TITLE
icon tier

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#137]
i don't know if am using the new tier icon wrong but it's not working for me

**Comment by insthync** [comment]
For some checklist
- Did you set icon sprite to ItemTier
- Did you set `Image` component to `UIItem` -> `Image Tier Icon`

**Comment by Ragingsura** [comment]
@insthync I've tried several times to put an image in the UIItem but can't do it and for the item tier am able to put the icon sprite but am not sure what purpose icon 2, 3 serve.

**Comment by insthync** [comment]
I already wrote its purpose in the changelog, just in case you want different icons for different locations. I don't know how you do it, screenshots please.

**Comment by Ragingsura** [comment]
![Unity_6ca4vQbpaN](https://user-images.githubusercontent.com/52991546/109718525-7472c200-7b75-11eb-9c26-f829d6113350.png)
![Unity_pcjG8VNGr7](https://user-images.githubusercontent.com/52991546/109718532-76d51c00-7b75-11eb-8566-de19bd7bec40.png)

**Comment by Ragingsura** [comment]
![7dv3aeQvh6](https://user-images.githubusercontent.com/52991546/109720648-5bb7db80-7b78-11eb-99b2-f369b10e44e6.png)
![6Zn5rTPku2](https://user-images.githubusercontent.com/52991546/109720651-5ce90880-7b78-11eb-87c4-d3b9c41c3eb5.png)
![Unity_VEDfPGZWNP](https://user-images.githubusercontent.com/52991546/109720666-5fe3f900-7b78-11eb-9267-6e519dd1b6af.png)
the border is not showing up

**Comment by insthync** [comment]
Try delete `UIItem.cs` (if you have made changes, backup it first) and re-import. it should have settings like this

![Screenshot_272](https://user-images.githubusercontent.com/2697550/109760830-f6b8c000-7c21-11eb-89fc-21dba7176768.png)

**Comment by Ragingsura** [comment]
> UIItem.cs

already had those setting the first time I update to the newest version but still  not showing the border
tired your suggestion fix  but that did not fix it either.

**Comment by insthync** [comment]
I saw in your screenshot there is no `ImageTierIcon`,  `ImageTierIcon2` and  `ImageTierIcon3`

**Comment by Ragingsura** [comment]
![Unity_qJQ4g7JruB](https://user-images.githubusercontent.com/52991546/109776336-76b63a00-7bd0-11eb-8ce0-aed8fc79115c.png)

**Comment by insthync** [comment]
Yeah, then set `Image` component to `ImageTierIcon`

**Comment by Ragingsura** [comment]
> Yeah, then set `Image` component to `ImageTierIcon`

that's the issue i can't set image to the component ImageTierIcon
