### ISSUE TITLE
How to hide the equipped items and In Team characters?

### ISSUE THREAD

**Issue by xcygame** [suriyun-production/turnbase-rpg-docs#139]
Hi Suriyun,

Especially when a character is equipped with many items, the item list will be crowded and unsightly. Is there a way to hide it?
![0](https://user-images.githubusercontent.com/41316408/109902766-e06c3c00-7cd5-11eb-87e7-01cf1ce96858.jpg)
![1](https://user-images.githubusercontent.com/41316408/109902835-eeba5800-7cd5-11eb-9a04-47a12e308b11.jpg)

I want the item and character to show up in the inventory when I take them off.

Thank you.

**Comment by insthync** [comment]
If you can coding, you have to add a condition in `UIFormationManager` -> line 121 to filter the list as you wish, I will add component config variables in next version

**Comment by xcygame** [comment]
> If you can coding, you have to add a condition in `UIFormationManager` -> line 121 to filter the list as you wish, I will add component config variables in next version

That's good news. Thank you.
