### ISSUE TITLE
here my game data

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#14]
[GAME_DATA.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/4006221/GAME_DATA.zip)

**Comment by surycr** [comment]
Save error: "script" in /~scripts/modules_GAME_DATA line:1 missing : after property id (#1)

that is the error

**Comment by insthync** [comment]
Weird, why decimal number output are `,` not `.` 

I will export patch package for you to try.

**Comment by surycr** [comment]
but i use unity for export

**Comment by insthync** [comment]
I know, I means I will export source codes from Unity as patch package.

**Comment by insthync** [comment]
[TBRPG_FixInvalidJsonFormat.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/4006268/TBRPG_FixInvalidJsonFormat.zip)
Try import the package inside the zip file then export game data to your service again.

**Comment by surycr** [comment]
arigatooo thx :)
