### ISSUE TITLE
Battle Points

### ISSUE THREAD

**Issue by HajiyevEl** [suriyun-production/turnbase-rpg-docs#140]
Hi again, Suriyun.
Where can i see BP calculation system and where i can set it?

**Comment by insthync** [comment]
In `BaseGameplayRule.cs`  there is a `GetBattlePoint` function, you actually can create custom gameplay rule by create a class  which extend from  `BaseGameplayRule.cs`. Then you can create your gameplay rule by scriptable object creation menu and set it to your game instance.

**Comment by HajiyevEl** [comment]
> 
> 
> In `BaseGameplayRule.cs` there is a `GetBattlePoint` function, you actually can create custom gameplay rule by create a class which extend from `BaseGameplayRule.cs`. Then you can create your gameplay rule by scriptable object creation menu and set it to your game instance.

Okay, Thanks!
