### ISSUE TITLE
"Rate" parameters of attributes

### ISSUE THREAD

**Issue by HajiyevEl** [suriyun-production/turnbase-rpg-docs#141]
I don't quite understand how it works, can someone explain it please?
Tooltip says : "This will be multiplied by min level *** then set to max level ***, when using context menu 'Set Max Attributes By Rates".
What is the use of it?

**Comment by insthync** [comment]
It's from `set max attributes tool` section, which will be used when using
 context menu to set max attributes by that values

![Screenshot_282](https://user-images.githubusercontent.com/2697550/110218559-f3a52480-7eec-11eb-9728-412dd97c9ecf.png)

For example, if I set `Min Hp` to `10` and I want to set the value at max level to `20`, I will set `hpRateToSetMax` to `2` 
Then when using the context menu it will set `Max Hp` to `20`.

**Comment by insthync** [comment]
My intention to use it is actually not to set value to expected value, I just use it to set max value which can be any but must be `Min Value` * `Rate To Set Max`.

**Comment by HajiyevEl** [comment]
> 
> 
> My intention to use it is actually not to set value to expected value, I just use it to set max value which can be any but must be `Min Value` * `Rate To Set Max`.

So, Max HP (or any other) depends on "Rate To Set Max" value, not other way around?
Example: If i have min hp value 10, and want want to set Max HP value to 220, than i should set hpRateToSetMax to 22, is it how it works? What if i don't want to set Max Value of attribute, just want to it increase without upper limit? Shall i set it to 0?

**Comment by HajiyevEl** [comment]
By the way, don't want to create new issue, so i will ask here, how does evolve work with tiers? I mean, when i evolve character, (from Common to Rare for example) does project delete current Common instance of character and creates new one with Rare tier? Cuz i can see you created several scriptable objects of same character with different tiers. So i wanted to ask if i correctly understood how it works or has missed something.

**Comment by insthync** [comment]
For player's save/database when it evolved it will change data id to new character's data id which has a higher tier.

For evolve character creation tool, it will create new character game data which copying data from the source and increase some attributes by values which set in the tool.

**Comment by HajiyevEl** [comment]
> 
> 
> For player's save/database when it evolved it will change data id to new character's data id which has a higher tier.
> 
> For evolve character creation tool, it will create new character game data which copying data from the source and increase some attributes by values which set in the tool.

Alright, thanks for answer. I still have some questions about sync client data with web-server, but that's for later. =) I still have too many things to do in project before thinking about data sync..
