### ISSUE TITLE
IAP Error ? Please Help Me ?

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#143]
Hello, I posted my game, this error pops up whenever I want to buy a diamond. I receive the money, the payment is successful, but the player does not receive diamonds and encounters this error. And when he/she wants to buy the same item again, it says he/she already has it. This is not just a one-off, as he buys diamonds Couldn't figure out why I am getting such an error. Please help me, I don't know what to do.

![310da4d5-4977-4a2d-a15a-025614109b23](https://user-images.githubusercontent.com/61230304/110186251-af9b1c80-7e25-11eb-9e6b-4b842cd5882e.jpg)
![08aa7e35-8a7d-4400-a857-36ec278fcb2c](https://user-images.githubusercontent.com/61230304/110186256-b0cc4980-7e25-11eb-97ef-0550a2b667fd.jpg)

**Comment by dclgamingtr** [comment]
The ids I wrote are correct ids coming from google play. I am using the latest up-to-date files you provided.

![İAPCATELOG](https://user-images.githubusercontent.com/61230304/110210200-9afc6a00-7ea1-11eb-91f5-30db21b7f979.png)
![CURRENC](https://user-images.githubusercontent.com/61230304/110210201-9b950080-7ea1-11eb-856c-a71d2ed141cb.png)

**Comment by dclgamingtr** [comment]
I am using the latest up-to-date files you provided. The IDs I got from Google console are correct. I can't find where the problem is.

![İAPCATELOG](https://user-images.githubusercontent.com/61230304/110210266-e4e55000-7ea1-11eb-8b63-3b62a1ad5ba1.png)
![CURRENC](https://user-images.githubusercontent.com/61230304/110210267-e57de680-7ea1-11eb-8104-9dcd29debcd3.png)

**Comment by insthync** [comment]
Did you set `play_public_key` config in your web-service config file?

**Comment by dclgamingtr** [comment]
Are you talking about the code I pasted in the iap section of unity?

**Comment by dclgamingtr** [comment]
I did not write anything in config.ini.

**Comment by insthync** [comment]
I mean this
![Screenshot_283](https://user-images.githubusercontent.com/2697550/110218685-a7a6af80-7eed-11eb-9564-3cc1ff0e951e.png)

**Comment by dclgamingtr** [comment]
Yes, I filled it there too, I wrote the key I got from google.

**Comment by dclgamingtr** [comment]
Could you connect remotely and browse please.

**Comment by insthync** [comment]
I am going to sleep, I will tell you later when I am ready.

**Comment by dclgamingtr** [comment]
Okay, I'll be glad if you let me know when you are available.

**Comment by dclgamingtr** [comment]
Hello, are you available?

**Comment by insthync** [comment]
Not yet :P

**Comment by insthync** [comment]
Did you publish your game to internal test?

**Comment by dclgamingtr** [comment]
The game is now published on google play.  I adjusted it as you show in the picture. The same problem continues.

**Comment by insthync** [comment]
I don't know what is this meaning ![](https://user-images.githubusercontent.com/61230304/110186256-b0cc4980-7e25-11eb-97ef-0550a2b667fd.jpg)

**Comment by dclgamingtr** [comment]
Error ,

You already have this item.


These are the ones that write in the picture.

**Comment by dclgamingtr** [comment]
Can you please connect and check

**Comment by insthync** [comment]
Are you available in next 3 hours?

**Comment by dclgamingtr** [comment]
Just write when you are available. I am available :)

**Comment by dclgamingtr** [comment]
Hello, please help. I am waiting for you.

**Comment by insthync** [comment]
Email your team viewer info, link for internal test to my email: ittipon.bay@gmail.com

**Comment by dclgamingtr** [comment]
Thank You :)
