### ISSUE TITLE
Info for development.

### ISSUE THREAD

**Issue by FleksisLV** [suriyun-production/turnbase-rpg-docs#145]
Hello, what's is the best way to get getting the inventory list from the player ?

**Comment by FleksisLV** [comment]
> Hello, what's is the best way to get getting the inventory list from the player ?

In what script i can see some example, that may help me to code my own battle pass system.
Thanks.

**Comment by insthync** [comment]
There are 2 parts, backend, and frontend, for PHP backend you can see codes in `/functions/Listing.php` find `GetItemList()` function.

**Comment by FleksisLV** [comment]
Hello, how can i change exp and profile name columns ?

**Comment by FleksisLV** [comment]
> There are 2 parts, backend, and frontend, for PHP backend you can see codes in `/functions/Listing.php` find `GetItemList()` function.

**Comment by FleksisLV** [comment]
> There are 2 parts, backend, and frontend, for PHP backend you can see codes in `/functions/Listing.php` find `GetItemList()` function.
How can i add like exp and profile name columns ? Because i added in all places where i need to add column but The error log is coming out when you login.
SqliteException: SQLite error
no such column: json

**Comment by insthync** [comment]
Where you added it? PHP Backend?
