### ISSUE TITLE
New Level up and Evolve 

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#148]
instead of having to select the materials to level up or evolve, it would be nice if the materials would already be available and all you need to do is level up or evolve if you have enough of said materials  example below 
![Bluestacks_qqmn5YlhIo](https://user-images.githubusercontent.com/52991546/111947129-38b38400-8ab3-11eb-8954-2e42f484a99c.png)

can you also make it so players can't level up pass the account level

**Comment by Ragingsura** [comment]
can you please implement this @insthync

**Comment by insthync** [comment]
Isn't it already there?, how this is different from the one in the asset package?

**Comment by Ragingsura** [comment]
@insthync yes there is a level up and evolve system is in the package but it's outdated and new games don't use this system of level and evolve anymore so I was hoping you could change it so that the materials will be available for the players to just tap it and level or evolve the characters instead of  having to select 5 materials  but rather this way as shown in the VIDEO BELOW 
[https://streamable.com/aj2mb7](url)

**Comment by Ragingsura** [comment]
@insthync  still no reply or update  can you please change or add this as a feature
