### ISSUE TITLE
About the clan boss.

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#149]
Hello, when will you finish the clan boss? You said you would give it with an update 2 months ago. But still waiting, did not add. Please at least complete this. Yours sincerely.

**Comment by insthync** [comment]
I did not create raid boss system for only clans yet, now there is only global raid boss which all players in the game can fight.

**Comment by dclgamingtr** [comment]
When will you add the clan boss? I told my gamers that this would come because you told me. We've been waiting for you to finish this for months. Please do something about it.

**Comment by insthync** [comment]
Yes, but because you so hassle so I am not in a mood to do it in the past 2 months ago, And you actually requested without telling me how it works. Now I will assume that it is working like a raid boss event, but only clan members can enter the dungeon. Then how to do ranking stuff?

**Comment by dclgamingtr** [comment]
Likewise, only clan members will have the right to attack once a day. It will be like Donation.

**Comment by insthync** [comment]
How about ranking and rewarding?

**Comment by dclgamingtr** [comment]
Clan activity is more important now. Because people have to do something in the clan. And the clan is not doing much work right now.

**Comment by insthync** [comment]
I asked for how ranking and rewarding work for clan boss, your complaint about how important it does not help me.

**Comment by dclgamingtr** [comment]
Raid will be the same as the boss. It will be exclusive to the clan only. It will open automatically every day and anyone will attack.

**Comment by insthync** [comment]
How about ranking and rewarding?

**Comment by Ragingsura** [comment]
> How about ranking and rewarding?

there needs to be a ranking and rewards base
another clan feature would be clan dungeon 
clan quest that gives clan exp and clan currency  
and lastly clan crafting 

apart from the clan stuff a add custom currency shop would be nice 
so we can add arena shop, clan shop etc etc

**Comment by insthync** [comment]
ranking will be based on clan members or all game players?

**Comment by Ragingsura** [comment]
for the clan boss rewards, it will only be for the clan, while the boss raid everyone has it own separate rankings something to the extent and rewards will be set for being in those rankings. Exp below this addon was created by a community member of the turnbase rpg

![unknown](https://user-images.githubusercontent.com/52991546/118408426-94356480-b653-11eb-9008-04c6ff5cf15c.png)

**Comment by dclgamingtr** [comment]
The leaderboard is not important right now. There is nothing to do in the clan. So players only log in. clan war can be added. Or the clan boss.

**Comment by insthync** [comment]
@dclgamingtr Why we fight with clan boss if it has no leaderboard and ranking?, Just increase clan score? No reward for clan member?

**Comment by dclgamingtr** [comment]
As with the raid boss, 1 monster is attacked by the whole clan team. When the monster runs out of health, it dies. When the attack is over, she gets her reward. No need to leaderboard. Can earn clan-specific currency. In this way, she can get items from the store.

**Comment by insthync** [comment]
All clan members get rewards after the boss died?

**Comment by dclgamingtr** [comment]
Yes

**Comment by insthync** [comment]
Next time, please describe it like this when you request a new feature, don't just tell me how important it is. It's not helpful.
