### ISSUE TITLE
why i can launcher the stage if i have stamina

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#15]
![image](https://user-images.githubusercontent.com/43394702/71553586-c18a5f80-29d7-11ea-9d5e-11cc723dd30a.png)

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/71553602-e979c300-29d7-11ea-9d6e-f4f60c09b664.png)

**Comment by insthync** [comment]
Are you sure that exported game data is the same data at client ?, try export game data to backend service and try again.

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/71553680-46c24400-29d9-11ea-99c1-b2c3f87d93a7.png)

**Comment by surycr** [comment]
and if a try give up the game dont loading

**Comment by insthync** [comment]
Let's make an appointment for the time I will access to your PC via TeamViewer to see your issues. How about next 2 hours?

**Comment by insthync** [comment]
Oh, about give up bugs, I just updates backend codes. You also have to update it too.  (https://github.com/insthync/CloudCode-GS-TBRPG/releases/tag/1.2b)

**Comment by surycr** [comment]
thx
