### ISSUE TITLE
No 3D view of your own models

### ISSUE THREAD

**Issue by Fighterone666** [suriyun-production/turnbase-rpg-docs#150]
Hi,

Unfortunately, only a gray window appears when my own models (e.g. when leveling up) should be displayed.

The model is displayed in the Unity menu under Camera. Who can give me a hint?

**Comment by insthync** [comment]
I don't get what is happen?

**Comment by Fighterone666** [comment]
![turnbase_error](https://user-images.githubusercontent.com/83428152/118352776-899ba200-b563-11eb-822d-cf56f8cb2dda.jpg)


I hope you can better see what I mean here. The view is empty in the game. In the upper right window you can see the character in the camera

**Comment by insthync** [comment]
Is it empty in render texture?
![Screenshot_418](https://user-images.githubusercontent.com/2697550/118372125-1f721400-b5da-11eb-865f-1d32a009783a.png)

Is render texture set to image component correctly 
![Screenshot_420](https://user-images.githubusercontent.com/2697550/118372139-3b75b580-b5da-11eb-8c54-937d808bf6b9.png)

**Comment by Fighterone666** [comment]
![characterviewer2](https://user-images.githubusercontent.com/83428152/118377442-8f2dd200-b5cd-11eb-9b8d-5cd8e364bb06.jpg)

With the Render Texture it is displayed correctly.

"Is render texture set to image component correctly"
this option i dont found

**Comment by insthync** [comment]
Sorry, wrong image

![Screenshot_419](https://user-images.githubusercontent.com/2697550/118378287-fdd65400-b5fc-11eb-8542-672fc6ed8b2f.png)

**Comment by Fighterone666** [comment]
![characterviewer3](https://user-images.githubusercontent.com/83428152/118378809-63631a00-b5d6-11eb-90a5-6434e05d4917.jpg)

**Comment by insthync** [comment]
Hmm weird, this problem occurring for only the custom character or all characters?

**Comment by Fighterone666** [comment]
When viewing the main screen or in the stages, the characters are displayed correctly.

The problem only occurs with certain characters
