### ISSUE TITLE
PHP Service Problem. Check it out please

### ISSUE THREAD

**Issue by HajiyevEl** [suriyun-production/turnbase-rpg-docs#153]
Hi Suriyun! After installing php-services i get this error.
I'm using openserver for testing. Project of TBRPG is clear one of latest version. What can be wrong?
@insthync 
![Screenshot 2021-05-04 223429](https://user-images.githubusercontent.com/70325881/117067502-27f55f80-ad3b-11eb-917c-6cbdb682fc08.png)
![Screenshot 2021-05-04 223557](https://user-images.githubusercontent.com/70325881/117067504-29268c80-ad3b-11eb-94c5-1f21adb37881.png)
![Screenshot 2021-05-04 223646](https://user-images.githubusercontent.com/70325881/117067506-29bf2300-ad3b-11eb-9771-1cd76cbb37d5.png)

**Comment by insthync** [comment]
Try change `use_request_query_action` config in `config.ini` to `TRUE`

![Screenshot_411](https://user-images.githubusercontent.com/2697550/117103929-763f4880-ada5-11eb-9f91-88e8a98d4318.png)

And change these configs:

![Screenshot_412](https://user-images.githubusercontent.com/2697550/117104016-9bcc5200-ada5-11eb-92f9-4e05d81932b7.png)

**Comment by HajiyevEl** [comment]
> 
> 
> Try change `use_request_query_action` config in `config.ini` to `TRUE`
> 
> ![Screenshot_411](https://user-images.githubusercontent.com/2697550/117103929-763f4880-ada5-11eb-9f91-88e8a98d4318.png)
> 
> And change these configs:
> 
> ![Screenshot_412](https://user-images.githubusercontent.com/2697550/117104016-9bcc5200-ada5-11eb-92f9-4e05d81932b7.png)

Okey it works now, thank you!
