### ISSUE TITLE
The reward item is not shown.

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#154]
![unknown](https://user-images.githubusercontent.com/61230304/117571175-fe8b5980-b0d5-11eb-8406-adcd37922540.png)

When you try to open single reward, the reward does not appear. I am having this error after the last update.

**Comment by dclgamingtr** [comment]
Doesn't show up when I use WebService.

**Comment by insthync** [comment]
Fixed, update `rpg php service`
