### ISSUE TITLE
Features from MMORpg kit

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#155]
it would be nice if we got some of the features from the mmorpg kit 

Add Game Database editor which you can open from menu MMORPG KIT -> Game Database, hope it helps customer to manage game data easier.

Add Character Model Cloner (3D) which you can open from menu MMORPG KIT -> Character Model Cloner (3D), which helps customers to clone settings to another character model.

Allow to set impactEffects while damageType is Melee.

i can keep going down the list but it would be nice to have a lot of the features from the MMORPG kit @insthync

**Comment by insthync** [comment]
Yeah, I will do it.
