### ISSUE TITLE
"Dont Show In Team Character" need improvement

### ISSUE THREAD

**Issue by xcygame** [suriyun-production/turnbase-rpg-docs#156]
Hello,I settings UIFormationManager "Dont Show In Team Character",it only work after I click "Back" button.
If I don't click  "Back" button ,It does not display correctly.
![01](https://user-images.githubusercontent.com/41316408/118439779-3703e680-b719-11eb-96ca-9d72ded26873.jpg)

**Comment by insthync** [comment]
Okay, I will fix it.

**Comment by xcygame** [comment]
OK, look forward to the next update，thanks.
