### ISSUE TITLE
Upgrade 

### ISSUE THREAD

**Issue by FleksisLV** [suriyun-production/turnbase-rpg-docs#157]
Hi, i updated  from  update-1.16b to update-1.17 because i got lot of custom scripts and i done it manually,i got fixed all errors, updated all scripts, but the raid events wont show and in the database  raid_event_creation, in table event where should be data about event, it's show only this two symbols [], can you help me please. 
![image](https://user-images.githubusercontent.com/45308506/118543153-d510a480-b74b-11eb-92bc-b2c7f9117727.png)
![image](https://user-images.githubusercontent.com/45308506/118543384-202ab780-b74c-11eb-8ea7-1c77d3c03ec1.png)
![image](https://user-images.githubusercontent.com/45308506/118543444-2e78d380-b74c-11eb-878f-f82c0703acba.png)

**Comment by insthync** [comment]
You've exported game data correctly from Unity?

**Comment by FleksisLV** [comment]
> You've exported game data correctly from Unity?

I will take look, when i get home, normaly data is exported correct, and when you check true json checker, it show that the gamedata.json is valid, and you can see that there is information about the raid..

**Comment by FleksisLV** [comment]
Hey @insthync , i fixed the problem, but i got one strange error, when i press enter the raid, it's don't do anything wrong in game but nobody like's errors you know, the line 44 is about title, title show's but it's keep saying that is missing, do you know why it's saying that  ?
![image](https://user-images.githubusercontent.com/45308506/119040718-abef4e80-b9ad-11eb-8dd8-79e4b05dbf51.png)

**Comment by FleksisLV** [comment]
@insthync  Also do you do private work, i will pay good, Is any chance you can make real time multiplayer battle for arena in this kit ? Is there any chance i can contact you private so we can speak more about this, and how much this will cost. :)  Thanks.
