### ISSUE TITLE
Errorservice-time HTTP/1.1 403 Forbidden 

### ISSUE THREAD

**Issue by Fighterone666** [suriyun-production/turnbase-rpg-docs#158]
I want to switch to a new web server. The data has been copied and the database has been set up and imported. Like website brings no mistakes. When I try to access the game, the following error occurs.

[GET->Error] service-time HTTP/1.1 403 Forbidden <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

UnityEngine.Debug:LogError(Object)
<GetRoutine>d__7:MoveNext() (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:100)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by insthync** [comment]
Do following this:

https://github.com/suriyun-production/turnbase-rpg-docs/issues/153

**Comment by Fighterone666** [comment]
Same Error, after i change the config


[GET->Error] ?action=service-time HTTP/1.1 403 Forbidden <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

UnityEngine.Debug:LogError(Object)
<GetRoutine>d__7:MoveNext() (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:100)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)


[POST->Error] ?action=validate-login-token&logintoken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwicHJvZmlsZU5hbWUiOiJnYXN0In0.qhVrd43SAJ5queKTmWwAPBykRGJiMvO907lhnVW2hcw HTTP/1.1 403 Forbidden <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

UnityEngine.Debug:LogError(Object)
<PostRoutine>d__10:MoveNext() (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:174)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by insthync** [comment]
Whats you have made changes ?

**Comment by Fighterone666** [comment]
use_request_query_action config in config.ini to TRUE

and
Set " Send Login Token Via Request Query, Send Action Target Via Request Query)

**Comment by insthync** [comment]
You may try change nginx config (see `Sample Nginx Configuration` section)
https://fatfreeframework.com/3.7/routing-engine

**Comment by insthync** [comment]
I will close this, if you still cannot fix the issue, tell me later.
