### ISSUE TITLE
Ui Manager

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#159]
Hey @insthync Please improve the ui manager am not able to create UI that link together am trying to make something that works like this Characte> Character List > Character improvement screen but it doesn't work properly 
![Unity_6lyQq6Uams](https://user-images.githubusercontent.com/52991546/121124714-5dd2ab80-c7f3-11eb-84c3-7e1400c0035c.png)
if I select a character on the left then try to level up nothing shows up on the level up or evolve screen

**Comment by insthync** [comment]
What happens when you click level up or evolve button? Did you set button events correctly?

**Comment by Ragingsura** [comment]
> What happens when you click the level up or evolve button? Did you set button events correctly?

they work as they should but while being in the level up tab and I select a different character nothing happens  and the material is empty  and since I duplicate the level up and evolve for the equipment  the same thing happens

**Comment by Ragingsura** [comment]
a character list would be nice under the character button it will look like the codex but no information is shared about the character  it shows you the character you have unlock and the ones you've yet to unlock and from that screen it will take you to the level up, evolve, equipment and gear level up and evolve screen
![Bluestacks_EOk9y0uPSN](https://user-images.githubusercontent.com/52991546/121268490-13e9d400-c88c-11eb-8017-7a375155461c.png)

**Comment by Ragingsura** [comment]
update to the codex is needed for it to show the character you own and the ones you don't own and also for it to display information not just the 3d model

**Comment by Ragingsura** [comment]
can we get the option to create items that give energy, currency, or items and  chest/ box that contain several items which open or used.
![Bluestacks_V6agfJShZJ](https://user-images.githubusercontent.com/52991546/121268687-688d4f00-c88c-11eb-9550-47021f1fb58b.png)

**Comment by Ragingsura** [comment]
option to summon/loot box to use custom currency and  if you already own the character it will give you an item that you can use to star up the character

Star features use an item to star up a character each star ups the character current stat by certain %
![Bluestacks_WCbY9FL0ff](https://user-images.githubusercontent.com/52991546/121269258-83ac8e80-c88d-11eb-8f3f-a72979a8333c.jpg)

**Comment by Ragingsura** [comment]
a shop with a custom currency would be nice and the database ui from the MMORPG kit

**Comment by Ragingsura** [comment]
lastly skill level up, gems  and pet with skills
![Bluestacks_WCbY9FL0ff](https://user-images.githubusercontent.com/52991546/121269467-e3a33500-c88d-11eb-8598-069fa621b6f5.jpg)

**Comment by insthync** [comment]
You requested like you paid me 1000 USD per month -_-"

**Comment by Ragingsura** [comment]
> You requested like you paid me 1000 USD per month -_-"

I don't and I hope it doesn't come off that way

**Comment by Ragingsura** [comment]
but i would like to make something and support you.
