### ISSUE TITLE
can i buy for Updates?

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#16]
i think u codes is so good and i want add Ideas but i dont know how change u code and u can help me i can play u, i want Legion, and boss and another ideas plz

**Comment by insthync** [comment]
I afraid that I would not have time to do that.

**Comment by surycr** [comment]
aa ok ok 
I understand I was saying it because I don't know how I can do to add the reward for seven days and if it is necessary to link with the gamesSpark, or I would like to be able to buy items with gold but not with the loots if not a store that will start for hours and certain things like that .. and the truth is that I feel you do a great job for that I would pay
