### ISSUE TITLE
Equipment Slot 

### ISSUE THREAD

**Issue by CreativePixel101** [suriyun-production/turnbase-rpg-docs#160]
Hello guy how do i go about creating equipment slot for new type of gear

**Comment by insthync** [comment]
https://suriyun-production.github.io/turnbase-rpg-docs/#/pages/021-how-to-add-new-equip-position

**Comment by CreativePixel101** [comment]
> https://suriyun-production.github.io/turnbase-rpg-docs/#/pages/021-how-to-add-new-equip-position

thank you for adding that to the doc
