### ISSUE TITLE
Tier Icon

### ISSUE THREAD

**Issue by CreativePixel101** [suriyun-production/turnbase-rpg-docs#161]
Hello again, question how do i go about using the tier icon. I've placed outer boundary icon on my tier date but it doesn't show on items or character.

**Comment by CreativePixel101** [comment]
@insthync sorry to bother you but can you assist me

**Comment by insthync** [comment]
Whats have you done?

Try do like this:

- Create new game object and attach Image component

![Screenshot_4](https://user-images.githubusercontent.com/2697550/124571448-a4202800-ddfc-11eb-9b9c-a2953eee92fd.png)

- Set the component to UIItem -> imageTierIcon

![Screenshot_5](https://user-images.githubusercontent.com/2697550/124571524-b732f800-ddfc-11eb-94ef-de402cea7e86.png)

**Comment by CreativePixel101** [comment]
> Whats have you done?
> 
> Try do like this:
> 
> * Create new game object and attach Image component
> 
> ![Screenshot_4](https://user-images.githubusercontent.com/2697550/124571448-a4202800-ddfc-11eb-9b9c-a2953eee92fd.png)
> 
> * Set the component to UIItem -> imageTierIcon
> 
> ![Screenshot_5](https://user-images.githubusercontent.com/2697550/124571524-b732f800-ddfc-11eb-94ef-de402cea7e86.png)

thank you it works
