### ISSUE TITLE
Character debuff and buff issue.

### ISSUE THREAD

**Issue by Adlorem** [suriyun-production/turnbase-rpg-docs#162]
Fist thank you for this great asset. I have two issues or I can't figure it out.
1. If character has one debuf, the second debuff cancels first one. Is there a possibility to stack debuffs? Example if character is stunned and decrease defence is placed then the stun is canceled. 
2. If you cast buffs on allies and you select all allies. The buff is placed only on allies that were not selected as buff target. So If you choose one ally to cast buff on all, the one you have chosen does not receive buff, Only not selected.
Thank you for help in advance.

**Comment by Adlorem** [comment]
My fault. After some debugging the problem was in line:

```
`            // Buff cannot stack so remove old buff
            if (Buffs.ContainsKey(buff.Id))
            {
                buff.BuffRemove();
                Buffs.Remove(buff.Id);
            }` 
```

buff Id is name of buff. I have just copied data with the same name to different characters folders. **You must use unique names for each file to make this work properly.** Would be easier to use file unique id instead of naming, but I imagine that can cause another problems with server side backend. I will leave this issue for people that had the same ideas as me in data structure.

To fix the buff not being applied to all allies you have to change this line in method ApplyBuffsRoutine

                      `  allies.Remove(ActionTarget);`
to 

```
                    if (buff.buffScope != BuffScope.AllAllies)
                    {
                        allies.Remove(ActionTarget);
                    }
```

**Comment by insthync** [comment]
If using file unique id it will have a problem when you want to delete old data then create a new one with the same ID, because it can't set ID as user wish, In next version I decide to add ID field to game data in-case you wanted to set ID in game data not game data file name.

![Screenshot_6](https://user-images.githubusercontent.com/2697550/124579459-f9136c80-de03-11eb-9f0c-ec7dc90f67e8.png)
