### ISSUE TITLE
Version 1.18 doesn't work (for me)

### ISSUE THREAD

**Issue by chribravo** [suriyun-production/turnbase-rpg-docs#163]
Importing the asset into a clean and fresh project (Unity 2020.3) results in:

**Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. ([]/Library/PackageCache/com.unity.nuget.newtonsoft-json@2.0.0/Runtime/Newtonsoft.Json.dll)**

Removing this multiple reference and starting the battle demo leads to:

**NullReferenceException: Object reference not set to an instance of an object
BaseGamePlayFormation.SetFormationCharacters (EBattleType battleType) (at Assets/RPGGame/Core/Scripts/GamePlay/BaseGamePlayFormation.cs:14)
GamePlayManager.Awake () (at Assets/RPGGame/Turnbase/Scripts/GamePlay/GamePlayManager.cs:56)**

**NullReferenceException: Object reference not set to an instance of an object
GamePlayFormation.Start () (at Assets/RPGGame/Turnbase/Scripts/GamePlay/GamePlayFormation.cs:15)**

**NullReferenceException: Object reference not set to an instance of an object
GamePlayFormation.Start () (at Assets/RPGGame/Turnbase/Scripts/GamePlay/GamePlayFormation.cs:15)**

Any idea? Thanks!

**Comment by insthync** [comment]
Delete `NewtonSoft.Json` files

![Screenshot_24](https://user-images.githubusercontent.com/2697550/125160939-55dc9300-e134-11eb-9e60-182407f37101.png)

When start game you have to start from 
`LoginScene` (Offline, uses LiteDB for data storing) or `LoginSceneSQLite` (Offline, uses SQLite for data storing) or `LoginSceneWebService` (Online, have to setup web-service)

**Comment by insthync** [comment]
No answer, so I will close this.
