### ISSUE TITLE
What is skill Hit Count used for ?

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/turnbase-rpg-docs#165]
In skills, there is a setting for Hit count which implies as if the damage values will be shown this number of times.
However, in actual testing that is not the case and skill usage still shows only 1 damage text.

So what is this value for ?

<img width="521" alt="Unity_TAag1B65dm" src="https://user-images.githubusercontent.com/3790163/125854738-3117cd32-d51a-44ac-9ee7-05c37f26fe28.png">

**Comment by insthync** [comment]
It's a bug, I will fix it.

**Comment by shubhank008** [comment]
Thank you
