### ISSUE TITLE
Can 2 people play online?

### ISSUE THREAD

**Issue by mcdeimon** [suriyun-production/turnbase-rpg-docs#166]
Can 2 people play online?

**Comment by insthync** [comment]
No real-time online, but you can meet other players in arena, guild, and so on.

**Comment by mcdeimon** [comment]
Would it be very difficult to add Proton to play in real time online with another player?

**Comment by insthync** [comment]
Maybe, it is up to how your game mechanic was planed too.

**Comment by mcdeimon** [comment]
I'd like to make a turn-based combat game. And instead of the AI ​​managing the adversary be a real player.

**Comment by insthync** [comment]
For PVP?

**Comment by mcdeimon** [comment]
Yes. Player vs player

**Comment by insthync** [comment]
So it is realtime arena battle, right?

You still have to re-implement battle mechanic and may have to add some mechanic such as player decision duration which if player not choose to attack or use skill it will do something. Other than game mechanic you have to think about who should be able to calculate damage, only master client or any clients can calculate damage.

**Comment by mcdeimon** [comment]
Yes.

It may be difficult for me. Is this option planned in the future?

Thank you!

**Comment by insthync** [comment]
No plan to do it

**Comment by mcdeimon** [comment]
Ok. Thank you. I am going to think about it.

**Comment by shubhank008** [comment]
> Ok. Thank you. I am going to think about it.

I am planning to add Photon for PvP too but it's a bit hard to do it alone so there are 2 routes I have thought of doing it:  
- Create a public git repo for this feature/addon so any dev can contribute to it and work, so its easier and faster to implement  
-  Above approach has a drawback of needing a few devs interested in doing it, and seeing as how most community programmers have moved to MMORPGKIT, the other way would be 3-5 users like us do a group/community funding and hire a few more programmers to work on this.  

I was talking to a community dev who is making addons to see if he was interested in approach #1 but seems he is not due to sheer amount of work for 1 person.  

You can add me on discord for further discussion (discord id) - 464017942607298560

**Comment by insthync** [comment]
If I start a donation campaign, and I will start to develop it as an open-source plugin project when there is 100 USD donated, would you interest?

**Comment by shubhank008** [comment]
> If I start a donation campaign, and I will start to develop it as an open-source plugin project when there is 100 USD donated, would you interest?

You doing it would be the most ideal scenario and I am pretty sure we can reach $100 for multiplayer easily, heck you can even release it on assetstore as a separate paid addon/plugin. The kit is already way value for money for it's price.  

If it's open source repo, I will try to help out speed the development work on it as much as I can.

Please go for it.

**Comment by mcdeimon** [comment]
I am interested in it

**Comment by Ragingsura** [comment]
> If I start a donation campaign, and I will start to develop it as an open-source plugin project when there is 100 USD donated, would you interest?

if it $100 USD to get multiplayer then i will pay for it, Setup the campaign.

**Comment by Ragingsura** [comment]
if you need support to add features to the kit i'll gladly support you.

**Comment by CreativePixel101** [comment]
this would be amazing if it was implemented.

**Comment by insthync** [comment]
If you like the idea, I've set up a fundraising campaign, you can donate here https://ko-fi.com/insthync

**Comment by Ragingsura** [comment]
> If you like the idea, I've set up a fundraising campaign, you can donate here https://ko-fi.com/insthync

campaign complete if you want more support please  just say so, because we really need more features.

**Comment by insthync** [comment]
Thank you, I will start develop it tomorrow

**Comment by shubhank008** [comment]
Suriyun can you perhaps create some kind of idea board where users who are interested in particular feature and can fund/donate to speed up its development put ideas and vote them to priority or maybe even a Patreon where we can do monthly continuous donations, even if smaller amount, to keep development of new features active by the donators.  

Also, if you decide to make the multiplayer repo open source, let me know. Do not know how much I can chip in with my knowledge, but would love to help any bit.  

@Ragingsura thanks for the one man army donation, I will still chip in my part at start of month when my card limit resets.

**Comment by Ragingsura** [comment]
> Suriyun can you perhaps create some kind of idea board where users who are interested in particular feature and can fund/donate to speed up its development put ideas and vote them to priority or maybe even a Patreon where we can do monthly continuous donations, even if smaller amount, to keep development of new features active by the donators.
> 
> Also, if you decide to make the multiplayer repo open source, let me know. Do not know how much I can chip in with my knowledge, but would love to help any bit.
> 
> @Ragingsura thanks for the one man army donation, I will still chip in my part at start of month when my card limit resets.

no problem

**Comment by Ragingsura** [comment]
> Thank you, I will start develop it tomorrow

not a problem any support i can offer i will offer it so you can develop more feature for the turn base kit

**Comment by Maltech9** [comment]
Do you have a timeline for when this will be ready? I'm super excited to hear about it being in the works

**Comment by insthync** [comment]
No ETA yet, but you can follow the development
- https://github.com/insthync/unity-tbrpg-realtime-arena
- https://github.com/insthync/tbrpg-realtime-arena-server

**Comment by insthync** [comment]
Some progress https://youtu.be/yP_KcmtrbxU

**Comment by shubhank008** [comment]
> Some progress https://youtu.be/yP_KcmtrbxU

Looking great already, question though. 
Any particular reason why you did not use PhotonPUN (colyseus seems similar service but for matchmaking) or your own multiplayer solution which you use in most of your kits (litenetlib) ?  If I am not wrong, have you created another of your own multiplayer system using nodejs instead ? Asking out of curiosity.

This kit having both a offline areana/PvP battle system (old one) and the new multiplayer arean/pvp system has just opened so many options for devs now, superb work suriyun.

**Comment by insthync** [comment]
I want to try new things and Colyseus is suited for this project, it is not fast pace real-time multiplayer and it requires room/matchmaking. It is also easy to set up, not have to pay for CCU (but have to pay for server renting)

**Comment by Maltech9** [comment]
Any updates on this?

**Comment by insthync** [comment]
It can be finished in this weekend

**Comment by Maltech9** [comment]
Looking foreword to this!

**Comment by insthync** [comment]
In the latest update, it has
- Decision waiting duration, if a player takes too long time to make a decision it will random action.
- Disconnect player handling, if a player exit from the game then that player's characters will random action.
- Winner/Loser result, will tell the battle result to all players when the battle ends.

Now it has PUN2 version too https://github.com/insthync/unity-tbrpg-pun-arena

**Comment by Maltech9** [comment]
Looking into the Photon project, the Team A formation and Team B formation part of the PUNArenaGamePlayManager arent working. Are they supposed to be ironed out in a future update? How can I get this to work for testing?

**Comment by Maltech9** [comment]
Having issues with the StartDuelButton not doing anything on the PUN version [=>
![ErrorOnButton](https://user-images.githubusercontent.com/10693635/135814776-5c58422d-eca9-47d6-ba01-f19de4dfbd7b.PNG)
]

**Comment by shubhank008** [comment]
> In the latest update, it has
> 
> * Decision waiting duration, if a player takes too long time to make a decision it will random action.
> * Disconnect player handling, if a player exit from the game then that player's characters will random action.
> * Winner/Loser result, will tell the battle result to all players when the battle ends.
> 
> Now it has PUN2 version too https://github.com/insthync/unity-tbrpg-pun-arena

@insthync although its good to have pun version too, but for a proper server authorative approach/version, we use should the other Colossus one right ?

**Comment by insthync** [comment]
@Maltech9 Oh, please wait, I have to upload the new version

**Comment by insthync** [comment]
@shubhank008 The Colyseus version is a bit more secure, the server can change the manager client, the client which calculates and syncs data. And when the game ends, the server will store records and do rewarding stuff, not clients like the PUN2 version.

**Comment by Maltech9** [comment]
Also noticed that the pun battle scene does nothing lol. Noticed that the StartDuelButton just needed the scene loading script which mustve been forgotten, with this I got to the battle screen but.... was bet with a blank scene lol

**Comment by insthync** [comment]
The new version is published

**Comment by insthync** [comment]
> Also noticed that the pun battle scene does nothing lol. Noticed that the StartDuelButton just needed the scene loading script which mustve been forgotten, with this I got to the battle screen but.... was bet with a blank scene lol

Not sure what you want to tell me? The Battle scene is not does nothing, it send messages to another client to tell whats player decided to do, you can see the codes in `PunArenaGameplayManager` .About the start duel button in manage scene, when you click it then it will load lobby scene, that is it, nothing special or complicate why it must have been forgotten?

**Comment by Maltech9** [comment]
> StartDuelButton

I was getting a missing script error on the button, so it literally had no logic attached. I pulled in the script you made for that button from the colossus project and got it to work though. Thank you for the swift update!

**Comment by Maltech9** [comment]
> The new version is published

Sorry to bug, but the photon version is sending this error: on the Override NewTurn() there is a method called "UpdateActivatingCharacter" which does not exist

**Comment by insthync** [comment]
Oh, I see, I've add the scripts to PUNArena repo, and update the manage scene, thank you :)

**Comment by insthync** [comment]
> > The new version is published
> 
> Sorry to bug, but the photon version is sending this error: on the Override NewTurn() there is a method called "UpdateActivatingCharacter" which does not exist

You also have to update the PUNArena too.

**Comment by Maltech9** [comment]
I'm

> > > The new version is published
> > 
> > 
> > Sorry to bug, but the photon version is sending this error: on the Override NewTurn() there is a method called "UpdateActivatingCharacter" which does not exist
> 
> You also have to update the PUNArena too.

I'm sorry but I thought I did. Was any other code modified or am I forgetting something? I just pulled the while zip from the github and incorporated it with my project

**Comment by Maltech9** [comment]
> > > The new version is published
> > 
> > 
> > Sorry to bug, but the photon version is sending this error: on the Override NewTurn() there is a method called "UpdateActivatingCharacter" which does not exist
> 
> You also have to update the PUNArena too.

Is that new function in the new version of the asset? Will I have to wait for Unity to upload it?

**Comment by Maltech9** [comment]
> > > > The new version is published
> > > 
> > > 
> > > Sorry to bug, but the photon version is sending this error: on the Override NewTurn() there is a method called "UpdateActivatingCharacter" which does not exist
> > 
> > 
> > You also have to update the PUNArena too.
> 
> Is that new function in the new version of the asset? Will I have to wait for Unity to upload it?

Got the new version and I'll test it out! Thanks!
