### ISSUE TITLE
How is the game server connected?

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#167]
I've installed Apache, PHP, MySQL. How is the game server connected? Hope you can make a simple video tutorials.

**Comment by insthync** [comment]
If you actually want to know how it connects you have to learn about web-service.

The https://github.com/insthync/rpg-php-service project is a REST web-service for the game client and the https://github.com/insthync/rpg-web-service-client is a client-side implementation that will send requests to the web-service to do something as the request and response back data to the client.

Example:
Client (Sell items) --- [REQUEST to the web-service address with selling items data] ---> Web-Service  (Remove item from inventory and give money) --- [RESPONSE with inventory data and amount of money] ---> Client (Update inventory and money)

I won't make a video that teaches you how it connects.

**Comment by shubhank008** [comment]
I made a in-depth newbie friendly video on this here - https://www.youtube.com/watch?v=txUS7VZRYfo
If you want a shorter and direct step-by-step version, you can follow the blog post - https://gamerzdan.com/setting-up-a-server-backend-for-your-unity3d-game-using-lemp-linux-nginx-mysql-php/  

PS: Once everything is setup, enter your game service URL in unity as shown in the Git link above and make sure there is no slash (/) at end of your url in Unity

**Comment by insthync** [comment]
@shubhank008 Oh, thank you :)

**Comment by TankLin2017** [comment]
Oh! It is great helpful, thanks a lot!@shubhank008.

**Comment by TankLin2017** [comment]
Now I have used Ubuntu and LNMP to set up a server . If I have any service-related questions in the future, I will ask you questions again, thank you!@insthync
