### ISSUE TITLE
i can upgrade for online i buy a hosting and domain

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#169]
![image](https://user-images.githubusercontent.com/43394702/126916054-6cecf4a3-efc8-4314-b4f5-bbf0dca26d1c.png)

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/126916122-0acee5f1-471b-4753-8e8a-166cf4d60403.png)

**Comment by insthync** [comment]
I try to access https://www.tiquiciafreak.com/ , it's not a web-service page, you may upload it to other location, if you upload files to htdocs/service/rpg, the URL must be https://www.tiquiciafreak.com/service/rpg

**Comment by surycr** [comment]
I managed to fix that change the route and it works I managed to make an account but I can't get past putting the name does not enter

**Comment by insthync** [comment]
How it is when putting the name?
