### ISSUE TITLE
Game hosting

### ISSUE THREAD

**Issue by bma42** [suriyun-production/turnbase-rpg-docs#17]
Is it possible to host game with SQLite ? do you have a tutorial? I am having problems with php webservice.

**Comment by bma42** [comment]
Can you advise me on web hosting, compatible with php web service?  mine seems to be incompatible.

**Comment by ekasjanov** [comment]
Hello Koodetat,

can you describe what problems you have with the php webservice? yout need a MySQL Server (5.7) and PHP 7.1+

**Comment by bma42** [comment]
I have several errors in the unity console, I cannot connect or create an account, but the database is correctly installed.  I will give you more details when I get back!  Maybe an .htaccess problem.

**Comment by bma42** [comment]
[PHP 7.3.6 - phpinfo().zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/4038890/PHP.7.3.6.-.phpinfo.zip)
My PHP Infos

**Comment by bma42** [comment]
![Sans titre](https://user-images.githubusercontent.com/19147694/72043427-61d26500-32b1-11ea-81c9-994a3477a4f1.png)
Dababase install

**Comment by bma42** [comment]
.htaccess: (defaut file)

SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0

RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-l

RewriteRule .* index.php [L,QSA]

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

**Comment by bma42** [comment]
Unity error:
[POST->Error]/validate-login-token HTTP/1.1 500 Internal Server Error <!DOCTYPE html>
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<h1>Internal Server Error</h1>
<p>Wrong number of segments [/srv/data/web/vhosts/ab7fcd304a95404e988232a27135859a.testmyurl.ws/htdocs/rpg-php-service-master/jwt/JWT.php:78]</p>
<pre>[rpg-php-service-master/functions/Helpers.php:11] Firebase\JWT\JWT::decode('7fabfe51-b4ed-4df7-9d4a-1d200375f79d','jwtSecret1234',['HS256'])
[rpg-php-service-master/functions/Helpers.php:85] DecodeJwt('7fabfe51-b4ed-4df7-9d4a-1d200375f79d')
[rpg-php-service-master/functions/Auth.php:72] GetPlayer()
[rpg-php-service-master/index.php:64] ValidateLoginToken(true)
[rpg-php-service-master/fatfree/lib/base.php:1873] {closure}(Base::__set_state(['hive'=>['HEADERS'=>['X-Forwarded-For'=>'176.190.89.172','Gandi-Rp'=>'429203','Host'=>'ab7fcd304a95404e988232a27135859a.testmyurl.ws','X-Country-Code'=>'FR','X-Forwarded-Proto'=>'http','Content-Length'=>'31','X-Unity-Version'=>'2019.2.12f1','Content-Type'=>'application/json','Accept'=>'application/json','User-Agent'=>'UnityPlayer/2019.2.12f1 (UnityWebRequest/1.0, libcurl/7.52.0-DEV)','Authorization'=>'Bearer 7fabfe51-b4ed-4df7-9d4a-1d200375f79d'],'AGENT'=>'UnityPlayer/2019.2.12f1 (UnityWebRequest/1.0, libcurl/7.52.0-DEV)','AJAX'=>false,'ALIAS'=>NULL,'ALIASES'=>[],'AUTOLOAD'=>'databases/|enums/','BASE'=>'/rpg-php-service-master','BITMASK'=>2,'BODY'=>'%7b%22refreshToken%22%3atrue%7d','CACHE'=>false,'CASELESS'=>true,'CLI'=>false,'CORS'=>['headers'=>'','origin'=>false,'credentials'=>false,'expose'=>false,'ttl'=>0],'DEBUG'=>3,'DIACRITICS'=>[],'DNSBL'=>'','EMOJI'=>[],'ENCODING'=>'UTF-8','ERROR'=>NULL,'ESCAPE'=>true,'EXCEPTION'=>UnexpectedValueException::__set_state([]),'EXEMPT'=>NULL,'FALLBACK'=>'en','FORMATS'=>[],'FRAGMENT'=>'','HALT'=>true,'HIGHLIGHT'=>false,'HOST'=>'ab7fcd304a95404e988232a27135859a.testmyurl.ws','IP'=>'176.190.89.172','JAR'=>['expire'=>0,'lifetime'=>0,'path'=>'/rpg-php-service-master','domain'=>'ab7fcd304a95404e988232a27135859a.testmyurl.ws','secure'=>false,'httponly'=>true],'LANGUAGE'=>'en','LOCALES'=>'./','LOGGABLE'=>'*','LOGS'=>'./','MB'=>true,'ONERROR'=>NULL,'ONREROUTE'=>NULL,'PACKAGE'=>'Fat-Free Framework','PARAMS'=>['/validate-login-token'],'PATH'=>'/validate-login-token','PATTERN'=>'/validate-login-token','PLUGINS'=>'/srv/data/web/vhosts/ab7fcd304a95404e988232a27135859a.testmyurl.ws/htdocs/rpg-php-service-master/fatfree/lib/','PORT'=>'80','PREFIX'=>NULL,'PREMAP'=>'','QUERY'=>'','QUIET'=>false,'RAW'=>false,'REALM'=>'http://ab7fcd304a95404e988232a27135859a.testmyurl.ws/rpg-php-service-master/validate-login-token','RESPONSE'=>'','ROOT'=>'/srv/data/web/vhosts/ab7fcd304a95404e988232a27135859a.testmyurl.ws/htdocs','ROUTES'=>['/validate-login-token'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/unlock-items'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/unequip-item'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/start-stage'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/start-duel'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/staminas'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/set-profile-name'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/set-formation'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/service-time'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/sell-items'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/select-formation'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/revive-characters'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/register'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/opponents'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/open-lootbox'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/login'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/levelup-item'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/items'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/ios-buy-goods'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/helpers'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/guest-login'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/google-play-buy-goods'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/friends'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/friend-requests'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/friend-request'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/friend-delete'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/friend-decline'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/friend-accept'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/formations'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/finish-stage'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/finish-duel'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/find-player'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/evolve-item'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/equip-item'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/earn-achievement-reward'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/currencies'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/clear-stages'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/available-lootboxes'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/available-iap-packages'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/achievements'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]]],'SCHEME'=>'http','SEED'=>'4xnl5h65qry5','SERIALIZER'=>'php','TEMP'=>'tmp/','TIME'=>1578551363.43256,'TZ'=>'UTC','UI'=>'./','UNLOAD'=>NULL,'UPLOADS'=>'./','URI'=>'/rpg-php-service-master/validate-login-token','VERB'=>'POST','VERSION'=>'3.6.5-Release','XFRAME'=>'SAMEORIGIN','GET'=>[],'POST'=>[],'COOKIE'=>[],'REQUEST'=>[],'SESSION'=>NULL,'FILES'=>[],'SERVER'=>['LC_ALL'=>'C','LD_LIBRARY_PATH'=>'/opt/mysql-5.7/lib/x86_64-linux-gnu','_'=>'/sbin/capsh','LANG'=>'C','OLDPWD'=>'/','DB_VERSION'=>'5.7','CUSTOMER_DIR'=>'/srv/data','container_ttys'=>'/dev/pts/0 /dev/pts/1 /dev/pts/2 /dev/pts/3','MAX_MEM'=>'512','DB_USER'=>'hosting-db','PREFIX'=>'/','container'=>'lxc','LOCAL_DIR'=>'/srv/run','WWW_ENGINE'=>'php','PWD'=>'/home/hosting-user','HOME'=>'/home/hosting-user','SYS_USER'=>'hosting-admin','TMPDIR'=>'/srv/data/tmp','DB_ENGINE'=>'mysql','PAAS'=>'lamp0','APP_USER'=>'hosting-app0','PAAS_USER'=>'hosting-user','SHLVL'=>'2','WWW_VERSION'=>'7.3','NO_MOUNT'=>'yes','LOGROTATE_CONF'=>'/srv/data/var/admin/logrotate.conf','PHP_USER'=>'hosting-user','PATH'=>'/usr/sbin:/usr/bin:/sbin/:/bin:/opt/php-7.3/bin:/opt/php-7.3/sbin:/opt/php-7.3/usr/bin:/opt/php-7.3/usr/sbin:/opt/mysql-5.7/bin:/opt/mysql-5.7/sbin:/opt/mysql-5.7/usr/bin:/opt/mysql-5.7/usr/sbin:/opt/sqlite-3/bin','GITWEB_USER'=>'hosting-user','LD_PRELOAD'=>' /usr/local/lib/gandi/gandi-preload.so','DISTRIB'=>'jessie','USER'=>'hosting-user','SCRIPT_NAME'=>'/rpg-php-service-master/index.php','REQUEST_URI'=>'/rpg-php-service-master/validate-login-token','QUERY_STRING'=>'','REQUEST_METHOD'=>'POST','SERVER_PROTOCOL'=>'HTTP/1.1','GATEWAY_INTERFACE'=>'CGI/1.1','REDIRECT_URL'=>'/rpg-php-service-master/validate-login-token','REMOTE_PORT'=>'24580','SCRIPT_FILENAME'=>'/srv/data/web/vhosts/ab7fcd304a95404e988232a27135859a.testmyurl.ws/htdocs/rpg-php-service-master/index.php','SERVER_ADMIN'=>'[no address given]','CONTEXT_DOCUMENT_ROOT'=>'/srv/data/web/vhosts/ab7fcd304a95404e988232a27135859a.testmyurl.ws/htdocs','CONTEXT_PREFIX'=>'','REQUEST_SCHEME'=>'http','DOCUMENT_ROOT'=>'/srv/data/web/vhosts/ab7fcd304a95404e988232a27135859a.testmyurl.ws/htdocs','REMOTE_ADDR'=>'176.190.89.172','SERVER_PORT'=>'80','SERVER_ADDR'=>'172.22.18.44','SERVER_NAME'=>'ab7fcd304a95404e988232a27135859a.testmyurl.ws','SERVER_SOFTWARE'=>'Apache','SERVER_SIGNATURE'=>'','HTTP_X_FORWARDED_FOR'=>'176.190.89.172','HTTP_GANDI_RP'=>'429203','HTTP_HOST'=>'ab7fcd304a95404e988232a27135859a.testmyurl.ws','HTTP_X_COUNTRY_CODE'=>'FR','HTTP_X_FORWARDED_PROTO'=>'http','CONTENT_LENGTH'=>'31','HTTP_X_UNITY_VERSION'=>'2019.2.12f1','CONTENT_TYPE'=>'application/json','HTTP_ACCEPT'=>'application/json','HTTP_USER_AGENT'=>'UnityPlayer/2019.2.12f1 (UnityWebRequest/1.0, libcurl/7.52.0-DEV)','proxy-nokeepalive'=>'1','HTTP_AUTHORIZATION'=>'Bearer 7fabfe51-b4ed-4df7-9d4a-1d200375f79d','REDIRECT_STATUS'=>'200','REDIRECT_HTTP_AUTHORIZATION'=>'Bearer 7fabfe51-b4ed-4df7-9d4a-1d200375f79d','FCGI_ROLE'=>'RESPONDER','PHP_SELF'=>'/rpg-php-service-master/index.php','REQUEST_TIME_FLOAT'=>1578551363.43256,'REQUEST_TIME'=>1578551363],'ENV'=>[],'db_prefix'=>'xp_','db_host'=>'localhost','db_port'=>3306,'db_name'=>'tbrg','db_user'=>'root','db_pass'=>NULL,'db_freeze'=>false,'timezone'=>'Asia/Jakarta','jwt_secret'=>'jwtSecret1234','password_salt'=>'lSALTlMUSTlATlLEASTl22','appstore_is_sandbox'=>true,'play_public_key'=>NULL,'GameData'=>['achievements'=>['2EvolveCharacters'=>['type'=>4,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'2EvolveEquipments'=>['type'=>5,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'2Helpers'=>['type'=>7,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'2Revives'=>['type'=>6,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'2UpgradeCharacters'=>['type'=>2,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'2UpgradeEquipments'=>['type'=>3,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'Clear2Stages'=>['type'=>0,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'Clear5Stages'=>['type'=>0,'targetAmount'=>5,'rewardSoftCurrency'=>1000,'rewardHardCurrency'=>5,'rewardPlayerExp'=>100,'rewardItems'=>[]],'Clear10Stages'=>['type'=>0,'targetAmount'=>10,'rewardSoftCurrency'=>1000,'rewardHardCurrency'=>5,'rewardPlayerExp'=>100,'rewardItems'=>[['id'=>'RedMushroom','amount'=>1]]],'Collect6Stars'=>['type'=>1,'targetAmount'=>6,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'Collect15Stars'=>['type'=>1,'targetAmount'=>15,'rewardSoftCurrency'=>1000,'rewardHardCurrency'=>5,'rewardPlayerExp'=>100,'rewardItems'=>[]],'Collect30Stars'=>['type'=>1,'targetAmount'=>30,'rewardSoftCurrency'=>1000,'rewardHardCurrency'=>5,'rewardPlayerExp'=>100,'rewardItems'=>[['id'=>'RedMushroom','amount'=>1]]]],'items'=>['BlackKnight'=>['id'=>'BlackKnight','category'=>'','itemTier'=>['id'=>'0-White','maxLevel'=>20,'expTable'=>['minValue'=>10,'maxValue'=>2206,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>2000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>1000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>1544,'growth'=>2.5],'evolvePrice'=>1000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>0,'fixSellPrice'=>0,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>0,'fixRewardExp'=>0,'evolveInfo'=>['requiredMaterials'=>[['id'=>'RedMushroom','amount'=>1]],'evolveItem'=>'BlackKnight 1']],'Shaman'=>['id'=>'Shaman','category'=>'','itemTier'=>['id'=>'0-White','maxLevel'=>20,'expTable'=>['minValue'=>10,'maxValue'=>2206,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>2000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>1000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>1544,'growth'=>2.5],'evolvePrice'=>1000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>0,'fixSellPrice'=>0,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>0,'fixRewardExp'=>0,'evolveInfo'=>['requiredMaterials'=>[['id'=>'RedMushroom','amount'=>1]],'evolveItem'=>'Shaman 1']],'Thief'=>['id'=>'Thief','category'=>'','itemTier'=>['id'=>'0-White','maxLevel'=>20,'expTable'=>['minValue'=>10,'maxValue'=>2206,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>2000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>1000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>1544,'growth'=>2.5],'evolvePrice'=>1000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>0,'fixSellPrice'=>0,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>0,'fixRewardExp'=>0,'evolveInfo'=>['requiredMaterials'=>[['id'=>'RedMushroom','amount'=>1]],'evolveItem'=>'Thief 1']],'RedMushroom'=>['id'=>'RedMushroom','category'=>'','itemTier'=>['id'=>'0-White','maxLevel'=>20,'expTable'=>['minValue'=>10,'maxValue'=>2206,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>2000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>1000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>1544,'growth'=>2.5],'evolvePrice'=>1000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>1,'fixSellPrice'=>1000000,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>1,'fixRewardExp'=>1000000,'evolveInfo'=>['requiredMaterials'=>[],'evolveItem'=>'']],'BlackKnight 1'=>['id'=>'BlackKnight 1','category'=>'','itemTier'=>['id'=>'1-Green','maxLevel'=>40,'expTable'=>['minValue'=>10,'maxValue'=>6364,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>4000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>2000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>4455,'growth'=>2.5],'evolvePrice'=>5000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>0,'fixSellPrice'=>0,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>0,'fixRewardExp'=>0,'evolveInfo'=>['requiredMaterials'=>[['id'=>'RedMushroom','amount'=>1]],'evolveItem'=>'BlackKnight 2']],'BlackKnight 2'=>['id'=>'BlackKnight 2','category'=>'','itemTier'=>['id'=>'2-Blue','maxLevel'=>60,'expTable'=>['minValue'=>10,'maxValue'=>11766,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>6000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>3000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>8236,'growth'=>2.5],'evolvePrice'=>10000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>0,'fixSellPrice'=>0,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>0,'fixRewardExp'=>0,'evolveInfo'=>['requiredMaterials'=>[['id'=>'RedMushroom','amount'=>1]],'evolveItem'=>'BlackKnight 3']],'BlackKnight 3'=>['id'=>'BlackKnight 3','category'=>'','itemTier'=>['id'=>'3-Purple','maxLevel'=>80,'expTable'=>['minValue'=>10,'maxValue'=>18172,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>8000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>4000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>12720,'growth'=>2.5],'evolvePrice'=>25000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>0,'fixSellPrice'=>0,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>0,'fixRewardExp'=>0,'evolveInfo'=>['requiredMaterials'=>[['id'=>'RedMushroom','amount'=>1]],'evolveItem'=>'']],'Shaman 1'=>['id'=>'Shaman 1','category'=>'','itemTier'=>['id'=>'1-Green','maxLevel'=>40,'expTable'=>['minValue'=>10,'maxValue'=>6364,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>4000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>2000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>4455,'growth'=>2.5],'evolvePrice'=>5000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>0,'fixSellPrice'=>0,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>0,'fixRewardExp'=>0,'evolveInfo'=>['requiredMaterials'=>[['id'=>'RedMushroom','amount'=>1]],'evolveItem'=>'Shaman 2']],'Shaman 2'=>['id'=>'Shaman 2','category'=>'','itemTier'=>['id'=>'2-Blue','maxLevel'=>60,'expTable'=>['minValue'=>10,'maxValue'=>11766,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>6000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>3000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>8236,'growth'=>2.5],'evolvePrice'=>10000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>0,'fixSellPrice'=>0,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>0,'fixRewardExp'=>0,'evolveInfo'=>['requiredMaterials'=>[['id'=>'RedMushroom','amount'=>1]],'evolveItem'=>'Shaman 3']],'Shaman 3'=<message truncated>.....

**Comment by bma42** [comment]
![Sans titre2](https://user-images.githubusercontent.com/19147694/72043630-f341d700-32b1-11ea-90e6-cea74890768d.png)

Server adress is: http://ab7fcd304a95404e988232a27135859a.testmyurl.ws/rpg-php-service-master

**Comment by ekasjanov** [comment]
What is the MySQL version? (phpMyAdmin main page)

**Comment by bma42** [comment]
It’s mysql 5.7

**Comment by ekasjanov** [comment]
I tried your Server address and got the following error: 
`[POST->Error]/guest-login HTTP/1.1 500 Internal Server Error <!DOCTYPE html>
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<h1>Internal Server Error</h1>
<p>PDOStatement: Field 'profileName' doesn't have a default value</p>`

I got this error on my server only if i used mariadb, with mysql 5.7 it worked. Possible wrong MySQL settings?

**Comment by bma42** [comment]
I don't know if my server uses mariadb, do you know a compatible host?

**Comment by ekasjanov** [comment]
For testing just create a local docker with mysql 5.7

**Comment by insthync** [comment]
It should work for both MySQL and MariaDB. I will check it.

**Comment by insthync** [comment]
As I see an error, it seems like it's because of database field doesn't have default values, for some database settings may require it. I will set default values for all fields, then I will tell you later when it has done.

**Comment by bma42** [comment]
Great !  thank you !

**Comment by insthync** [comment]
Okay, done, update it (https://github.com/insthync/rpg-php-service) then browse sql-importer.php?update=1.10b to update tables, and try to register / login later.

**Comment by bma42** [comment]
I think it works now on the server side. On the other hand the import of my GameData.json on my database causes errors. I
![Sans titre3](https://user-images.githubusercontent.com/19147694/72139934-d4197700-338f-11ea-8aba-a0095fd94075.png)
is there a specific parameter, or other to do with the import?

**Comment by bma42** [comment]
should we convert the json file into another format to import it into the database?

**Comment by insthync** [comment]
Paste the exported JSON file to the service root . where it is contains index.php, replace the GameData.json.

**Comment by bma42** [comment]
thank you i didn't think about it !!
