### ISSUE TITLE
Problem with equip model container

### ISSUE THREAD

**Issue by bma42** [suriyun-production/turnbase-rpg-docs#170]
Hello,
There is a problem with equipped objects (equip model prefab). CharacterActStandContainer is not updated when equipping or un-equipping an item. It is necessary to modify the formation of the characters to display the equipment or remove it (visually).

**Comment by bma42** [comment]
any news about this bug? has anyone noticed it?

**Comment by insthync** [comment]
I will tell you how to fix it later, now I am outside of my home.

**Comment by bma42** [comment]
OK, thanks

**Comment by insthync** [comment]
It has to refresh the formation
In next version I will add these functions to `BaseGamePlayFormation` class
```
    public void SetFormationCharactersForStage()
    {
        SetFormationCharacters(EBattleType.Stage);
    }

    public void SetFormationCharactersForArena()
    {
        SetFormationCharacters(EBattleType.Arena);
    }

    public void SetFormationCharactersForRaidBoss()
    {
        SetFormationCharacters(EBattleType.RaidBoss);
    }

    public void SetFormationCharactersForClanBoss()
    {
        SetFormationCharacters(EBattleType.ClanBoss);
    }
```

![Screenshot_567](https://user-images.githubusercontent.com/2697550/127398659-19634926-61be-4d25-a638-0ffa0c047194.png)

* * *
 
Then you can set event when enter menu to reload the formation like this

![Screenshot_568](https://user-images.githubusercontent.com/2697550/127398910-18874ef0-9965-4456-88b5-2df0646f3894.png)

**Comment by bma42** [comment]
Great thank you, i will try
