### ISSUE TITLE
New ideas and systems 

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#171]
i've created a trello for everyone to  use and past new ideas that we can fund and insthync  will create
https://trello.com/invite/b/gXaxQf4O/54a2e4c2fef9c336e2160d540d08237b/turnbase-rpg-kitroadmap

**Comment by insthync** [comment]
Joined :)

**Comment by Ragingsura** [comment]
> Joined :)

gave you admin so you will be able to move things around if you're going to pick it up
