### ISSUE TITLE
how can use IAP

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#172]
hi hello i fixed my problem and i can play and all good but i can use IAP 
![image](https://user-images.githubusercontent.com/43394702/128426255-4db8b63f-5148-4807-af3e-a7cd8d207a3d.png)

**Comment by surycr** [comment]
i was install Unity Purchasing but don change red tex

**Comment by insthync** [comment]
![Screenshot_591](https://user-images.githubusercontent.com/2697550/128436724-d8e34488-021a-432c-8e92-bfd3a947ac59.png)

Did you turn this on?

Then you may try add `UNITY_PURCHASING` to scripting define symbols

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/128438303-c10f707a-f1de-4a81-b80f-ef0ca1cc4d55.png)

**Comment by surycr** [comment]
i test with UNITY_PURCHASIN  and nothing , but if a use UNITY_PURCHASIN i cant use ENABLE_PURCHASIN

**Comment by insthync** [comment]
> i test with UNITY_PURCHASIN and nothing , but if a use UNITY_PURCHASIN i cant use ENABLE_PURCHASIN

I don't understand this, did you try googling when you got any error?

**Comment by surycr** [comment]
the IAP package of the asset store says that it was obsolete this month and they would add it to manager and I installed it from there but I don't know if it is because they changed it

**Comment by insthync** [comment]
[UpdateAsmdef.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/6942587/UpdateAsmdef.zip)

Try this

**Comment by surycr** [comment]
dont fixed

**Comment by insthync** [comment]
Why?

**Comment by surycr** [comment]
i am was import u new packga but dont change i dont know why

**Comment by insthync** [comment]
Is there any error in the console log?

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/128472460-9fff088f-395c-4a79-af8b-daf1e73ca444.png)

**Comment by TankLin2017** [comment]
Er...Now I met the same problem as the same as you, the UIIapPackages can't load the UIIAPPackage.
 @insthync Everything seems to be OK , I don't get any mistakes, so can you help us?
The UIInGamePackages is OK
![image](https://user-images.githubusercontent.com/24680678/129484603-3d3f5a53-cf0f-4a0a-a78a-0ffaf5833c99.png)
But the UIIapPackages  can't load the UIIAPPackage.
![image](https://user-images.githubusercontent.com/24680678/129484630-3f6f2640-3945-44cf-ae02-799aa8aa0a84.png)
Don't have any mistake.
![image](https://user-images.githubusercontent.com/24680678/129484670-c923cc0f-c0f6-428c-9660-de9b0a552844.png)
The DemoGameData's lap Packages are OK
![image](https://user-images.githubusercontent.com/24680678/129484779-70928e00-ad29-4a24-a585-4044d5d3751f.png)

![image](https://user-images.githubusercontent.com/24680678/129484723-f0ef94d6-c461-48d5-b46b-53adab252a91.png)

**Comment by insthync** [comment]
Did you export game data to the web-service?

**Comment by TankLin2017** [comment]
> Did you export game data to the web-service?

How to export game data to the web-service?
Like this?
![image](https://user-images.githubusercontent.com/24680678/129484967-0d6b6b5d-0b09-4621-b90e-d9fe3edef04f.png)

**Comment by insthync** [comment]
No, I mean this https://github.com/insthync/rpg-php-service#client-side-implemented-project, `play_public_key` is a key which you can copy from Android dashboard.

**Comment by TankLin2017** [comment]
> No, I mean this https://github.com/insthync/rpg-php-service#client-side-implemented-project, `play_public_key` is a key which you can copy from Android dashboard.

Oh! I forgot, Thank you. I will try it right now . You are really my best teacher.

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/129485508-45f87c5a-8ff3-4a2d-8a60-3596ec1e4c4b.png)
It works! Thank you @insthync
