### ISSUE TITLE
About the 404 Not Found, Unity can't connet server( fatfree )

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#174]
Now I can successfully deploy the LNMP server runtime environment. When the first installation was completed, the sql-importer. PHP file was ":) Done".
However, when I run The LoginScenWebService of Unity, the error "404 Not Found" is reported. Then I open the sql-importer file, the same problem occurs. How should I solve it?
![0](https://user-images.githubusercontent.com/24680678/128595282-4c8ac3da-1248-4f22-8293-c8b716b717b5.png)
![1](https://user-images.githubusercontent.com/24680678/128595286-8588cf83-9df9-4cc5-a027-1cae677bbabd.png)
![2](https://user-images.githubusercontent.com/24680678/128595293-19b8194a-7f09-4f22-b5da-3a0893df05ea.png)
![3](https://user-images.githubusercontent.com/24680678/128595298-d2880108-cf86-48d6-8178-787194008a12.png)

**Comment by insthync** [comment]
For Nginx user, try do this:

- Set `use_request_query_action` setting in `config.ini` to `TRUE`
- Set setting at client project -> `WebServiceClient` -> `SendActionTargetViaRequestQuery` to `TRUE`.

Or

https://fatfreeframework.com/3.7/routing-engine#SampleNginxConfiguration

**Comment by TankLin2017** [comment]
@insthync It works,thanks! Now I will test the Unity In-App Purchasing , hoping everything is fine。
