### ISSUE TITLE
Help ,I can't use the IAP 

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#175]
I follow the document"https://suriyun-production.github.io/turnbase-rpg-docs/#/pages/012-in-app-purchasing" ,and imported the package of UDP、UnityChannel、UnityIAP，and set the In-App Purchasing On, and add the "ENABLE_PURCHASING" to the Scripting Define Symbols. 
Then I build the Android APK ,Unity console some errors:
![IAP_5](https://user-images.githubusercontent.com/24680678/128669778-bafaead8-ae78-4401-9e26-799023b45793.png)
Can you help me to fix them?
![IAP_1](https://user-images.githubusercontent.com/24680678/128669814-64a957ba-c0b0-4a3e-a908-d255f5fb49ea.png)
![IAP_2](https://user-images.githubusercontent.com/24680678/128669840-a29b4673-1a75-45e1-afe9-89a5383cfa19.png)
I don't have Google Play Developer Account, because my bank card of mastercard has not been sent to me, 
Is it because of this problem? Don't have Google Public Key?
![IAP_3](https://user-images.githubusercontent.com/24680678/128670255-f720d9ea-baaa-49b2-ba36-a41a1f7584f5.png)
![IAP_4](https://user-images.githubusercontent.com/24680678/128670263-985c4a7f-04d4-4ad9-8821-86f3c12c6585.png)
![IAP_6](https://user-images.githubusercontent.com/24680678/128670272-df02c9a0-71e8-4e36-a023-92a04f40776c.png)

**Comment by surycr** [comment]
I have the same problem,

**Comment by insthync** [comment]
Try import this package 
https://github.com/suriyun-production/turnbase-rpg-docs/issues/172#issuecomment-893953801

**Comment by surycr** [comment]
im was  import  that  #172 (comment)  but dont fixed the bug

**Comment by insthync** [comment]
If I try on your PC, it will work immediately

**Comment by surycr** [comment]
mmm=?

**Comment by surycr** [comment]
how would you prove it

**Comment by insthync** [comment]
Send your teamviewer info to my email: ittipon.bay@gmail.com, but now I am not available yet. (Having lunch)

**Comment by insthync** [comment]
Don't get why you ask for the prove, what I will earn if I prove it?

**Comment by TankLin2017** [comment]
@insthync Don't be angry, he may be too anxious, I will try to import the package.

**Comment by insthync** [comment]
I usually help customer to fix issues by TeamViewer for free, just ask me to help, don't ask for the prove.

**Comment by surycr** [comment]
I did not ask for tests I just wanted to know how he was going to be able to help me.

**Comment by surycr** [comment]
'm just from Costa Rica right now it's 12:46 am and I don't speak much English, I use a translator

**Comment by TankLin2017** [comment]
Oh! I can build it, you are amazing! @insthync Thanks. Come on ,it is OK @surycr .
But it talk me to provide passwords, where can I provide?
![QQ截图20210810144537](https://user-images.githubusercontent.com/24680678/128821141-0724c0b0-afd4-44bc-86c0-1d8bab6fff53.png)

**Comment by surycr** [comment]
that is u key u can make a new key

**Comment by TankLin2017** [comment]
I use translator, too. It is OK , just try more methods. And let insthync help us , insthync is very professional.

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/128821670-ffacd167-95df-41a9-bfd4-28601a450e60.png)

**Comment by surycr** [comment]
> I use translator, too. It is OK , just try more methods. And let insthync help us , insthync is very professional.

yes i know he is so profesional

**Comment by surycr** [comment]
> Oh! I can build it, you are amazing! @insthync Thanks. Come on ,it is OK @surycr .
> But it talk me to provide passwords, where can I provide?
> ![QQ截图20210810144537](https://user-images.githubusercontent.com/24680678/128821141-0724c0b0-afd4-44bc-86c0-1d8bab6fff53.png)
can u fix IAP?

**Comment by TankLin2017** [comment]
I'm building my game without fixing the IAP ,I don't have Google Public Key,because my bank card of master card is sending to me. @surycr 
![QQ截图20210810151235](https://user-images.githubusercontent.com/24680678/128824300-bc66579e-484b-4a60-aa44-f96c1472c7c9.png)

**Comment by surycr** [comment]
i have a google play key and set at unity

**Comment by TankLin2017** [comment]
> i have a google play key and set at unity
When my bank card arrives, I will try to build my game with the GooglePlay Key again. If your mistake also occurs, I will try to solve it. In addition,I believe insthync can help us.

**Comment by insthync** [comment]
Oh, sorry for my angriness too, I'm ready, send me your TeamViewer Info
