### ISSUE TITLE
About the Formation, I want to make a little changes... 

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#177]
![42AD24C0-ED81-4f31-9543-4484A475665B](https://user-images.githubusercontent.com/24680678/128993542-a54ea019-ae88-44bf-be10-e1d3964d9346.png)
I want to change the Formation ...

I hope that when the character avatars in the formation interface are in battle, the characters in the 3D scene can also be updated immediately.

Now I need to click the back button ，then the characters on the scene can be updated.

Can you help me? Do you have discord? I want to follow you.

**Comment by insthync** [comment]
I don't use Discord.

You can add codes like this https://github.com/suriyun-production/turnbase-rpg-docs/issues/170#issuecomment-888635507

or wait for the next version.

**Comment by TankLin2017** [comment]
Thanks!I will try it. @insthync

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/129154554-ac9a5343-d186-4b0f-b4cd-dcb6ece0c7b0.png)
@insthync 
I have tried that method, but it didn't work, and found new problem, hope to fix it.
And hope when I equip the hero in UIFormationManager, The 3D hero in the 3D scene can also refresh immediately.
If you can tell me how to fix it that will be fine. Or I can wait for the next version.

**Comment by insthync** [comment]
This was fixed long time ago.
