### ISSUE TITLE
I can't upgrade my hero to the full level

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#178]
![image](https://user-images.githubusercontent.com/24680678/129162146-4b16b3f4-38bf-478a-baee-f8db215602a9.png)
I want to upgrade my hero to th full level , then test the Evolve System.
But I try many times , it can't upgrade to th full level, help.

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/129163073-4fa47b3d-07bc-4d9b-88b7-63e3587f7ac1.png)
And even the hero will be full level, I can still add the Materials....
![image](https://user-images.githubusercontent.com/24680678/129163346-29a06d8f-6952-4f9a-b987-69bde77ac79a.png)

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/129164577-6e2a0a82-0877-4f8c-948c-1dfcd818e01e.png)
I found if I change the growth value, the hero's level can become full. Why?

**Comment by insthync** [comment]
1. Not sure that it actually can't levelup to max level or rewarding EXP from selected materials not reaching max level. It's limit 5 materials selection in the demo.
2. It's up to players to manage their material if it's reaching max level, players actually can just deselect the material. And if it reached max level, the level up button will be interactable.
3. Growth is a growth factor that affects the required EXP for each level, so when you set growth, it will changes amount of required level for all levels except first level and last level. So it can reduce total required EXP to max level. You can see how it works here: https://docs.google.com/spreadsheets/d/11ydlhPLLZ6eGkwDQxqmJ4lUFePmxQqEIoiJ3o5NG6xI/edit?usp=sharing (Select `Required EXP to Levelup` cells to see formula)

**Comment by TankLin2017** [comment]
OK , thanks, I get it.
