### ISSUE TITLE
Random/Dynamic Equipment Attributes

### ISSUE THREAD

**Issue by ekasjanov** [suriyun-production/turnbase-rpg-docs#18]
Hello,

is it possible to create random/dynamic attributes for equipment items? Like Raid/Summoners War System? 
Random main attribute and random sub attributes?

Thanks

**Comment by surycr** [comment]
one question all basic atack is for P.A?
Or we can use M.A

**Comment by ekasjanov** [comment]
Any Idee how i can realise this ? I think that all attributes for equipment must be loaded from the database.

**Comment by insthync** [comment]
I will implement this part.

**Comment by insthync** [comment]
@surycr You can use M.ATK as basic attack it's up to you

**Comment by ekasjanov** [comment]
> I will implement this part.

Thanks, you are the best! :)

**Comment by insthync** [comment]
Is it okay if you have to set presets, then the system will random which preset will be applied to an items ?

![Screenshot_12](https://user-images.githubusercontent.com/2697550/73118301-e47f4380-3f84-11ea-83cd-e8a91ef8ed2b.png)

**Comment by ekasjanov** [comment]
No, that wouldn't help me much. I would have to generate so many presets. Is it possible to get the attributes from the database? Otherwise, I'd have to generate every possible variant in the json. file.

Example calculation: 7 different equipment types (weapon, armor ..), each of them has the possibility to get one of the 16 different attributes(attack plain, attack %, def plain, def % ...) as main attribute. And depending on the type(normal, rare, epic ...) there are 1 or more secondary attributes. There are 5 different types.

7 * 16 * 5 * x (x would be over 1000 if all possible variants will be count) 

to many presets :)

**Comment by ekasjanov** [comment]
And for the future one could also think about updates of the secondary attributes, that would only be possible if the attributes are in the database.

**Comment by insthync** [comment]
I see, what if there are following configs:

- Random range of attribute kinds 
- Random range of each attribute

It will works as: 
if `Random range of attribute kinds` = 2
- `HP range` = 20 to 30
- `MP range` = 20 to 30
- `P Atk` = 2 to 5
- `P Def` = 2 to 5

Then it can random attributes to:
- Hp = 20 to 30
- Mp = 20 to 30
or
- Mp = 20 to 30
- PAtk = 2 to 5
or 
- PAtk = 2 to 5
- PDef = 2 to 5

Because `Random range of attribute kinds` = 2, it will have 2 kinds of attributes will be increased to item.

It's good?

**Comment by ekasjanov** [comment]
this sounds interesting, yes

**Comment by surycr** [comment]
i want  see that

**Comment by insthync** [comment]
The settings screenshot:

![Screenshot_18](https://user-images.githubusercontent.com/2697550/73733791-2a02f400-476f-11ea-903c-88efd488c88f.png)

You can set random attributes for Character and Item.

**Comment by surycr** [comment]
nice one

**Comment by insthync** [comment]
Added to version 1.11
