### ISSUE TITLE
Hi, can I hire your engineer to add some new system for the Turnbase RPG Template?

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#180]
I want to add some different system,but I don't know understand the Turnbase RPG Template.
Besides, my coding ability is also very average. 
So do you have  business that I can hire your engineer to add some new system for the Turnbase RPG Template?

Looking forward to your reply.

**Comment by Ragingsura** [comment]
it one person and he has already stated his not for hire if you want something request for it and also support him with kofie

**Comment by TankLin2017** [comment]
@Ragingsura OK，thanks for answer.

**Comment by TankLin2017** [comment]
@Ragingsura @insthync where I can support you? what is kofie?

**Comment by TankLin2017** [comment]
Can you give me a link?

**Comment by Ragingsura** [comment]
https://ko-fi.com/insthync

**Comment by TankLin2017** [comment]
Your work has been very helpful to me :)


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "suriyun-production/turnbase-rpg-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月18日(星期三) 上午10:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [suriyun-production/turnbase-rpg-docs] Hi, can I hire your engineer to add some new system for the Turnbase RPG Template? (#180)





 
https://ko-fi.com/insthync
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
