### ISSUE TITLE
Moving all improvements under one ui

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#181]
hey @insthync is it possible to move level, evolve and equipment under one parent object and just toggle between them with buttons Please assist me I've tried the events but it doesn't seem to work
![Unity_kWmyf5mRBb](https://user-images.githubusercontent.com/52991546/129632315-bdad33c3-c0bd-486a-9194-8407fcc5de73.png)
![Unity_sz67BiVcQ7](https://user-images.githubusercontent.com/52991546/129632716-2032d6d4-2d5b-4149-abd7-80427b44fbca.png)

**Comment by Ragingsura** [comment]
trying to use the buttons on the left to toggle between them

**Comment by insthync** [comment]
Hmm, seems like I have to change some code structure to make it able to work like that, I might change selected item data to be static variable so it can access the variable by any components. So when click on level up/evolve and so on it won't have to set item data value before toggle.

**Comment by Ragingsura** [comment]
> Hmm, seems like I have to change some code structure to make it able to work like that, I might change selected item data to be static variable so it can access the variable by any components. So when click on level up/evolve and so on it won't have to set item data value before toggle.

thank you

**Comment by Ragingsura** [comment]
can character, items and materials get a separate itemicon prefab
also i would really apricated it if you could add a separate screen for equipment level up and evolve

**Comment by Ragingsura** [comment]
thank you again @insthync

**Comment by insthync** [comment]
https://youtu.be/tTMBz0n9J5E

**Comment by Ragingsura** [comment]
> https://youtu.be/tTMBz0n9J5E

thank you, your the best
