### ISSUE TITLE
Suggestion : Formation 3d model

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#184]
it would be cool to be able to see the character models in the formation
![Unity_E0zM6DoUa6](https://user-images.githubusercontent.com/52991546/130158905-e4001b04-a55c-471e-9f55-baa4ee851350.png)
I've try to move the character stance into the formation but no mater how i adjust it some character just look pixelated

**Comment by TankLin2017** [comment]
Oh，Nice ,I'm waiting for it ,too.

**Comment by insthync** [comment]
Okay, in the next version.

**Comment by insthync** [comment]
https://youtu.be/tTMBz0n9J5E

**Comment by TankLin2017** [comment]
Is it ready to download?@insthync

**Comment by insthync** [comment]
Uploaded, but I don't know when it will be published

**Comment by TankLin2017** [comment]
OK ! I will wait for it . @insthync

**Comment by Ragingsura** [comment]
> https://youtu.be/tTMBz0n9J5E

thank you very much
