### ISSUE TITLE
About Purchase App [Environment: FakeStore]

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#185]
![image](https://user-images.githubusercontent.com/24680678/130348282-a85bca14-13cd-4f38-ab51-81524fab45da.png)
I choose the button of "Buy", but there is nothing happen, and there isn't any mistake.
How can I purchase the virtual game goods ?

**Comment by TankLin2017** [comment]
Besides, I purchase coins in Android App , It doesn't even pop up this popover.

**Comment by surycr** [comment]
i need help with that again never was can use Iap

**Comment by insthync** [comment]
I didn't implement the fake store, you have to create your app and In-App purchasing items in Google Play or Apple when you create it you will have an item's ID, then uses those IDs to create In-App purchasing items in Unity, that is it.
