### ISSUE TITLE
About Switching Characters  - 1.18b

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#186]
I'm very like the version of 1.18b of character management, but if it can change character more easy, it will be perfect! @insthync 
![image](https://user-images.githubusercontent.com/24680678/131243197-9dbc5998-aceb-4254-9469-b37d5f6e7890.png)
![image](https://user-images.githubusercontent.com/24680678/131243215-b6662f3d-3edf-4e3a-9ec2-16553bb42616.png)
![image](https://user-images.githubusercontent.com/24680678/131243224-8a1241c0-7dcf-4a7f-ba18-9f37758ae25e.png)

**Comment by Ragingsura** [comment]
this would actually be an amazing feature to have

**Comment by insthync** [comment]
In 1.18d
- Add events to select previous and next items from character's inventory to `UIItem` component (`OnClickPreviousItem` and `OnClickNextItem`).

*Try ManageScene-2*
