### ISSUE TITLE
How to restore the original game data?

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#187]
I have change the name of one hero, than I can't load the hero in game , so I want to reset all data of the game, including server and database in MySQL.

**Comment by TankLin2017** [comment]
After change the name of hero database , I have sent the new gamebase.json to the server, then restart the cloud server、nginx、php-fpm、mysqld，but it still can't load the hero in game. Why?

**Comment by insthync** [comment]
Because its ID changed and it can't find the data with that ID, if you want to set its ID to the old one, you can set its ID here

![Screenshot_629](https://user-images.githubusercontent.com/2697550/132214632-a1917a74-261b-4287-aee2-e00108656909.png)

If this value is empty, it will use game data filename as ID.

**Comment by TankLin2017** [comment]
> Because its ID changed and it can't find the data with that ID, if you want to set its ID to the old one, you can set its ID here
> 
> ![Screenshot_629](https://user-images.githubusercontent.com/2697550/132214632-a1917a74-261b-4287-aee2-e00108656909.png)
> 
> If this value is empty, it will use game data filename as ID.

Thank you very much. Yesterday I looked at the database and wondered if it is related to dataID.

By the way , How to initialize the game data? 

What I can think of is to delete the player account in the database, but this project will be a bit large。

 and how can I back up the player data? I am worried that the player’s data will be lost.

**Comment by insthync** [comment]
Not sure that are you asking to know how game data is initialize, right?

You actually do not have to delete the player account, if you can remember the file's name before it was changed, you can use that old file as `Id` by set it to the `Id` setting.

For PHP service, it uses MySQL, you can learn how to export database by using tools like phpMyAdmin, I didn't create backup tool for it yet.

**Comment by TankLin2017** [comment]
> Not sure that are you asking to know how game data is initialize, right?
> 
> You actually do not have to delete the player account, if you can remember the file's name before it was changed, you can use that old file as `Id` by set it to the `Id` setting.
> 
> For PHP service, it uses MySQL, you can learn how to export database by using tools like phpMyAdmin, I didn't create backup tool for it yet.

Thank you .

**Comment by TankLin2017** [comment]
@insthync Do you have Alipay( 支付宝 )? I have tried many times on KO-Fi to support you, but my MasterCard debit card cannot be paid through PayPal.
