### ISSUE TITLE
How do I change the distance between melee attack and target in combat?

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#189]
Attacks are now divided into melee attacks and range attacks.

The range attack is to stand in the middle of the scene and release skills, and the melee attack is to run in front of the enemy, but now it is too close, the attacking character is directly overlapped with the enemy model, where can I change the range of melee attack?

Besides, where can I set the particle effects of missiles? I can't find it.

**Comment by insthync** [comment]
In 1.18d
- Add `meleeAttackDistance` setting to `AttackAnimationData` scriptable object.

**Comment by TankLin2017** [comment]
> * AttackAnimationData
@insthync Where can I set the particle effects of missiles? I can see the missiles , but I don't know where it can be setted.
