### ISSUE TITLE
i need autoupdate can one help me plz

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#19]
how can be auto Update

**Comment by insthync** [comment]
You means auto update after changes game data ?

**Comment by surycr** [comment]
what I want is how to make it verify the version on the phone and update the apk I update the data but my question is if anyone knows how to do that

**Comment by insthync** [comment]
If you can write codes, you can create the json web page which contains list of platforms and version its format may like
```
{
  {"Device":"Android", "Version":"1.0", "DownloadUrl":""},
  {"Device":"iOS", "Version":"1.0", "DownloadUrl":""},
}
```
Then at the client (your game project), you can read the web page with [UnityWebRequest](https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.html). Then read it from json string to object values with [JsonUtility](https://docs.unity3d.com/Manual/JSONSerialization.html)

Then you can check the version with [Application.version](https://docs.unity3d.com/ScriptReference/Application-version.html) or other version variable.

And open the update link with [Application.OpenURL](https://docs.unity3d.com/ScriptReference/Application.OpenURL.html)

**Comment by surycr** [comment]
ok thanks i will see arigato ;)

**Comment by surycr** [comment]
haha i cant and i was buy mg patch and dont work for android ahahh haha

**Comment by insthync** [comment]
So you should learn how to use Asset Bundles

**Comment by surycr** [comment]
??

**Comment by surycr** [comment]
a is free i will try
