### ISSUE TITLE
Problem about the Screen Space - Camera and Blood of the actor

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#190]
![image](https://user-images.githubusercontent.com/24680678/132660229-35aca19f-f96e-4e37-8a19-12293149c620.png)
@insthync I want to make two camera , one for actor and scene, another for UI, the blood of the actor can be rendered at Screen Space - Overlay.
![image](https://user-images.githubusercontent.com/24680678/132660292-485916d9-bfff-46a5-aca3-a29d5a47adb2.png)
But the blood of the actor can't be rendered at Screen Space - Camera, can you help me? Or teach me some methods, thanks.

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/132669893-68cce70d-4791-4f60-bc4b-da5a9742b155.png)
![image](https://user-images.githubusercontent.com/24680678/132669992-ab49d0f0-bc9c-4a77-88e2-c3331a7ad8f8.png)
Besides, I have changed the blood UI layer to UI layer , the UI camera is only look at the UI layer.

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/132712705-3f3d0ff7-11b6-47a7-81e1-cc6dd1248008.png)
![image](https://user-images.githubusercontent.com/24680678/132712819-093123c2-a0aa-48f2-ba68-6d85d80c6313.png)
![image](https://user-images.githubusercontent.com/24680678/132713017-97eba683-df7d-469a-a7fe-6e3bc197d6d8.png)
![image](https://user-images.githubusercontent.com/24680678/132713165-603e8f56-f9ec-484d-99ea-694fc1225ddb.png)

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/132718389-503cd1de-2d65-4e13-9d44-084600ff817d.png)
I can only find this , help~@insthync

**Comment by TankLin2017** [comment]
I can pay for solving this problem by buying MMORPG KIT (2D/3D/Survival)~ please help~

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/132728468-f7078c59-983b-4f83-8d7d-6758bb742223.png)
I have found that this is a difficult problem to solve, but I really hope you can help me.

**Comment by insthync** [comment]
[TBRPG-WorldSpaceUICharacterStats.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/7138533/TBRPG-WorldSpaceUICharacterStats.zip)

Download and import this patch, then in your `UICharacterStats` prefab, attach canvas which its render mode is world space

![Screenshot_635](https://user-images.githubusercontent.com/2697550/132732289-16d9a1d6-6c0b-4a3d-9331-2996b4a04a82.png)

**Comment by insthync** [comment]
It also added to 1.18d

**Comment by TankLin2017** [comment]
> It also added to 1.18d

 Nice , I have tried it ,but it still has some problem. Looking forward to the next version.

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/132791716-c60e6fc2-2bb6-4062-8ce0-b95074fa4e3d.png)
The problem is like this.

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/132795106-90ba3d60-b4ea-4cf8-8d84-0081e9ce601f.png)
Hope the camera can be divided into main camera and UI camera ，this can make a lot of visual effects. @insthync

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/132803328-3c9202a2-f522-4114-99c4-b8a9fcafef27.png)
It works，if the blood of hero can face to the main camera, that will be perfect.

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/132803533-fd0a5e84-0a2f-431b-af96-8d2d5ef1d5fb.png)
@insthync You deserve it ,tell your partner, it is yours. I hope you'll continue to update the game features.
