### ISSUE TITLE
Problem about the UI of charactor' blood

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#191]
![image](https://user-images.githubusercontent.com/24680678/133018147-4a6c207b-cd99-4b0d-a1fb-5cc320796f0d.png)
@insthync Please help...I found the UI of charactor's blood don't face to UI Camera, please solve it , then I believe it will be perfect.

**Comment by insthync** [comment]
You may try attach this document to the UI character stats
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace UtilsComponents
{
    public class Billboard : MonoBehaviour
    {
        public Camera targetCamera;

        public Transform CacheTransform { get; private set; }
        public Transform CacheCameraTransform { get; private set; }

        private void OnEnable()
        {
            CacheTransform = transform;
            SetupCamera();
        }

        private bool SetupCamera()
        {
            if (targetCamera == null)
            {
                targetCamera = Camera.main;
                if (targetCamera != null)
                    CacheCameraTransform = targetCamera.transform;
            }
            return targetCamera != null;
        }

        private void LateUpdate()
        {
            if (!SetupCamera())
                return;
            CacheTransform.rotation = Quaternion.Euler(Quaternion.LookRotation(CacheCameraTransform.forward, CacheCameraTransform.up).eulerAngles);
        }
    }
}

```

**Comment by TankLin2017** [comment]
> You may try attach this document to the UI character stats
> 
> ```
> using System.Collections;
> using System.Collections.Generic;
> using UnityEngine;
> 
> namespace UtilsComponents
> {
>     public class Billboard : MonoBehaviour
>     {
>         public Camera targetCamera;
> 
>         public Transform CacheTransform { get; private set; }
>         public Transform CacheCameraTransform { get; private set; }
> 
>         private void OnEnable()
>         {
>             CacheTransform = transform;
>             SetupCamera();
>         }
> 
>         private bool SetupCamera()
>         {
>             if (targetCamera == null)
>             {
>                 targetCamera = Camera.main;
>                 if (targetCamera != null)
>                     CacheCameraTransform = targetCamera.transform;
>             }
>             return targetCamera != null;
>         }
> 
>         private void LateUpdate()
>         {
>             if (!SetupCamera())
>                 return;
>             CacheTransform.rotation = Quaternion.Euler(Quaternion.LookRotation(CacheCameraTransform.forward, CacheCameraTransform.up).eulerAngles);
>         }
>     }
> }
> ```

![Uploading image.png…]()
@insthync It works!! Thank you~ and can the UI layer of the character blood  be higher than that of the character model?

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/133042278-561591dd-5916-4fac-930b-f0a4c8457523.png)
Please...

**Comment by insthync** [comment]
You may try set layer for your UI Character Stats then add a new camera as a child of main camera, set all settings like as the main camera, set culling mask for the UI only and set depth higher than the main camera

![Screenshot_640](https://user-images.githubusercontent.com/2697550/133046703-69a83c10-f7c4-4d14-ab41-a4c95a92b97b.png)

**Comment by TankLin2017** [comment]
> You may try set layer for your UI Character Stats then add a new camera as a child of main camera, set all settings like as the main camera, set culling mask for the UI only and set depth higher than the main camera
> 
> ![Screenshot_640](https://user-images.githubusercontent.com/2697550/133046703-69a83c10-f7c4-4d14-ab41-a4c95a92b97b.png)

![image](https://user-images.githubusercontent.com/24680678/133051432-5d437f62-d296-49b3-af31-017c40141d7d.png)
![image](https://user-images.githubusercontent.com/24680678/133051979-48ad3465-22ab-45d2-b622-9c683c53f346.png)
Because I‘m using the UPR Pinpline, the camera is different for Dault Pinpline, so the setting of camera can't set the depth, can you teach me by using URP camera? please...

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/133052506-1ea5f986-d12b-4114-b059-69efb3fd0da2.png)
Oh！！It works！Thanks !
