### ISSUE TITLE
Hoping that we can have UI of boss's blood in Battle System

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#192]
![image](https://user-images.githubusercontent.com/24680678/133019177-3cdb8211-6c68-4e71-af44-59b26762ca3e.png)
Deer@insthync , I found we have Clan and Raid Boss，but if I make a big model for the Boss , the UI of Boss's blood may hardly be saw by player.
Can we make one? It will be nice.

![image](https://user-images.githubusercontent.com/24680678/133019790-78838eab-0c8b-4952-aea9-3a4e81d268bf.png)
Besides, we can set the monster to become boss in the gamedata, insthync, please ...

**Comment by insthync** [comment]
Okay, in next version

**Comment by insthync** [comment]
Added in 1.19

**Comment by TankLin2017** [comment]
> Added in 1.19

Well done!
