### ISSUE TITLE
Hoping that we can have a action bar system

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#194]
![image](https://user-images.githubusercontent.com/24680678/133715647-b149f31b-5561-4585-ae4d-692cbff2bbaa.png)
@insthync Friend, our game mechanics prioritize attacks based on the speed of the character, so it would be perfect to have an action bar.  Hoping we can have this system.

**Comment by insthync** [comment]
Okay, in next version

**Comment by TankLin2017** [comment]
> Okay, in next version

@insthync Oh~You are my Jesus! Love you!

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/133885179-c42290de-bf86-4f6a-94ec-e37fbea736d0.png)
@insthync Dear friend, I found a problem, it makes me very uncomfortable, because the UI of blood is at the world space, so if the enemies are far from camera. The UI of blood will become very small, and the UI of hero's blood will be very big ToT...
![image](https://user-images.githubusercontent.com/24680678/133885281-c62da7a9-03ae-4bf8-bc3f-a64cc8570d35.png)
So is it possible like this? the UI of hero's blood is at the UI camera space, player can see all the hero's blood at UI layer, when the turn of the character's action is reached, play can choose the skill.

Hoping the function can achieve , I believe it will make the battle system very nice for the 3D visual, please....

**Comment by Ragingsura** [comment]
wow solid suggestions

**Comment by insthync** [comment]
Added in 1.19

**Comment by TankLin2017** [comment]
> Added in 1.19

Thanks! @insthync you are the best!
