### ISSUE TITLE
 can nerf and buff heros when is onlinne?

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#195]
hello I have a question, once a player obtains a character, he always keeps the same data, they cannot be improved or lowered and that all players who have the same character see the changes, so be able to nerf or buff or once the online game and the data created cannot be changed. Thank you

**Comment by insthync** [comment]
Yes, They will be improved or lowered follows what you have made changes, except random attributes.

**Comment by surycr** [comment]
For example, if a character has 3 skills and I change the data, of that same one and add a skill, and buy the hero in the loot, it will come out with 4 skills but those that already had of that same one are left with 3.

**Comment by insthync** [comment]
If players got the character when has 3 skills then you add or make changes to skills, for example, you add a new skill to have 4 skills.
Then the character will have 4 skills. If players get the character again it will have 4 skills too.
