### ISSUE TITLE
V1.19 Error

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#196]
![Unity_ah0ckcIv3D](https://user-images.githubusercontent.com/52991546/137431318-b1bdf056-8e72-49f4-a24e-82bd43a46a50.png)
 updated project and am getting all the errors related to purchasing

**Comment by insthync** [comment]
![Screenshot_714](https://user-images.githubusercontent.com/2697550/137431897-04f6832d-98c9-4967-91de-96980051c957.png)

Try install `In-app purchase` package

**Comment by Ragingsura** [comment]
Already got the iap package downloaded.

**Comment by insthync** [comment]
![Screenshot_716](https://user-images.githubusercontent.com/2697550/137448458-ffedf5ed-d1cb-4074-ad5f-d8816a0210dd.png)

Is this turn on?

**Comment by Ragingsura** [comment]
Yes it's checked both to make sure I have the iap package  installed and the service  turned on

**Comment by insthync** [comment]
What is your Unity version?

**Comment by Ragingsura** [comment]
> What is your Unity version?

update to latest Lts and the issue got fix but i got a new error now

**Comment by Ragingsura** [comment]
![Unity_nVPsUikueu](https://user-images.githubusercontent.com/52991546/137503948-187aae13-b16e-44c7-955d-ef84c3275d3b.png)

**Comment by Ragingsura** [comment]
v2021.1.25f1

**Comment by insthync** [comment]
Try delete `UIUtilities` folder which is located in `Assets/RPGGame` and reimport the package.
