### ISSUE TITLE
Hoping to add a UI Effect for getting equip or hero from the loot box

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#197]
![image](https://user-images.githubusercontent.com/24680678/137663053-0e341d7c-cb16-4e65-b1a1-99187f1b5df2.png)
@insthync every time I get a hero, I can't immediately know what quality the hero is. So, for the sake of surprise, I hope that when I get an item, there will be quality special effects behind the item.

Can you help me? please~

**Comment by Ragingsura** [comment]
+1 this suggestion

**Comment by insthync** [comment]
You can extend `AnimItemRewarding` class to override `Play` function, when it is going to play, you can read item data and get its  tier and use it as a condition to play the animation, I don't want to implement it because of difference games, will have difference animation.

**Comment by insthync** [comment]
I decided to add `ObjectsActivatingByItemTiers` setting to `AnimItemRewarding`, `AnimItemLevelUp` and `AnimItemEvolve`, use it to set activating objects by item tiers.
