### ISSUE TITLE
Is that possible to add a chance to skill attack?

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#198]
![image](https://user-images.githubusercontent.com/24680678/137665613-08997555-5576-4e10-9819-1ff6718c852c.png)
I found that the buff had chance , so I hope the skill attack can have chance, I think it will make the gameplay very interesting...can it be like this?... @insthync

**Comment by insthync** [comment]
When you use attack skill what will happen when the randomized result is not attacking the enemy?

**Comment by TankLin2017** [comment]
@insthync Some attacks deal damage to the enemy, but some will be missed.

**Comment by insthync** [comment]
Want to add a chance for skill hit missing?

**Comment by TankLin2017** [comment]
@insthync Happy New Year~，long time no talk~. yes, I hope can  add a chance for skill hit missing, please~

**Comment by insthync** [comment]
Implemented in 1.25
