### ISSUE TITLE
Error web build

### ISSUE THREAD

**Issue by RostislavStoliarchuk** [suriyun-production/turnbase-rpg-docs#200]
When launching a web project on unity 2020-2019, I get an error. Tell me what to do to fix 
![Error](https://user-images.githubusercontent.com/88757013/142209084-ae69eb96-9aae-466b-a044-098961e8cbeb.png)
it

**Comment by insthync** [comment]
See your browser console

**Comment by RostislavStoliarchuk** [comment]
I didn't understand you a little, watch the console?

**Comment by RostislavStoliarchuk** [comment]
navigator.mediaDevices support available
test.framework.js.gz:3 [UnityMemory] Configuration Parameters - Can be set up in boot.config

test.framework.js.gz:3     "memorysetup-temp-allocator-size-audio-worker=65536"

test.framework.js.gz:3     "memorysetup-temp-allocator-size-cloud-worker=32768"

test.framework.js.gz:3     "memorysetup-temp-allocator-size-background-worker=32768"

test.framework.js.gz:3     "memorysetup-bucket-allocator-granularity=16"

test.framework.js.gz:3     "memorysetup-bucket-allocator-bucket-count=8"

test.framework.js.gz:3     "memorysetup-bucket-allocator-block-size=4194304"

test.framework.js.gz:3     "memorysetup-bucket-allocator-block-count=1"

test.framework.js.gz:3     "memorysetup-main-allocator-block-size=16777216"

test.framework.js.gz:3     "memorysetup-thread-allocator-block-size=16777216"

test.framework.js.gz:3     "memorysetup-gfx-main-allocator-block-size=16777216"

test.framework.js.gz:3     "memorysetup-gfx-thread-allocator-block-size=16777216"

test.framework.js.gz:3     "memorysetup-cache-allocator-block-size=4194304"

test.framework.js.gz:3     "memorysetup-typetree-allocator-block-size=2097152"

test.framework.js.gz:3     "memorysetup-profiler-bucket-allocator-granularity=16"

test.framework.js.gz:3     "memorysetup-profiler-bucket-allocator-bucket-count=8"

test.framework.js.gz:3     "memorysetup-profiler-bucket-allocator-block-size=4194304"

test.framework.js.gz:3     "memorysetup-profiler-bucket-allocator-block-count=1"

test.framework.js.gz:3     "memorysetup-profiler-allocator-block-size=16777216"

test.framework.js.gz:3     "memorysetup-profiler-editor-allocator-block-size=1048576"

test.framework.js.gz:3     "memorysetup-temp-allocator-size-main=4194304"

test.framework.js.gz:3     "memorysetup-job-temp-allocator-block-size=2097152"

test.framework.js.gz:3     "memorysetup-job-temp-allocator-block-size-background=1048576"

test.framework.js.gz:3     "memorysetup-job-temp-allocator-reduction-small-platforms=262144"

test.loader.js:1 exception thrown: RangeError: Maximum call stack size exceeded,RangeError: Maximum call stack size exceeded
    at invoke_ii (http://localhost:50879/Build/test.framework.js.gz:3:379539)
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7561]:0x22b45c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7558]:0x22b2a1
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[2190]:0xbc030
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[811]:0x72aed
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[81695]:0x16ecc2c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[45989]:0xf00989
    at invoke_ii (http://localhost:50879/Build/test.framework.js.gz:3:379509)
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7561]:0x22b45c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7558]:0x22b2a1
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[2190]:0xbc030
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[811]:0x72aed
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[81695]:0x16ecc2c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[45989]:0xf00989
    at invoke_ii (http://localhost:50879/Build/test.framework.js.gz:3:379509)
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7561]:0x22b45c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7558]:0x22b2a1
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[2190]:0xbc030
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[811]:0x72aed
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[81695]:0x16ecc2c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[45989]:0xf00989
    at invoke_ii (http://localhost:50879/Build/test.framework.js.gz:3:379509)
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7561]:0x22b45c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7558]:0x22b2a1
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[2190]:0xbc030
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[811]:0x72aed
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[81695]:0x16ecc2c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[45989]:0xf00989
    at invoke_ii (http://localhost:50879/Build/test.framework.js.gz:3:379509)
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7561]:0x22b45c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7558]:0x22b2a1
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[2190]:0xbc030
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[811]:0x72aed
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[81695]:0x16ecc2c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[45989]:0xf00989
    at invoke_ii (http://localhost:50879/Build/test.framework.js.gz:3:379509)
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7561]:0x22b45c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7558]:0x22b2a1
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[2190]:0xbc030
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[811]:0x72aed
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[81695]:0x16ecc2c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[45989]:0xf00989
    at invoke_ii (http://localhost:50879/Build/test.framework.js.gz:3:379509)
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7561]:0x22b45c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[7558]:0x22b2a1
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[2190]:0xbc030
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[811]:0x72aed
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[81695]:0x16ecc2c
    at http://localhost:50879/Build/test.wasm.gz:wasm-function[45989]:0xf00989
    at invoke_ii (http://localhost:50879/Build/test.framework.js.gz:3:379509)
printErr @ test.loader.js:1
test.framework.js.gz:3 Uncaught RangeError: Maximum call stack size exceeded
    at invoke_ii (test.framework.js.gz:3)
    at test.wasm.gz:0x22b45c
    at test.wasm.gz:0x22b2a1
    at test.wasm.gz:0xbc030
    at test.wasm.gz:0x72aed
    at test.wasm.gz:0x16ecc2c
    at test.wasm.gz:0xf00989
    at invoke_ii (test.framework.js.gz:3)
    at test.wasm.gz:0x22b45c
    at test.wasm.gz:0x22b2a1
    at test.wasm.gz:0xbc030
    at test.wasm.gz:0x72aed
    at test.wasm.gz:0x16ecc2c
    at test.wasm.gz:0xf00989
    at invoke_ii (test.framework.js.gz:3)
    at test.wasm.gz:0x22b45c
    at test.wasm.gz:0x22b2a1
    at test.wasm.gz:0xbc030
    at test.wasm.gz:0x72aed
    at test.wasm.gz:0x16ecc2c
    at test.wasm.gz:0xf00989
    at invoke_ii (test.framework.js.gz:3)
    at test.wasm.gz:0x22b45c
    at test.wasm.gz:0x22b2a1
    at test.wasm.gz:0xbc030
    at test.wasm.gz:0x72aed
    at test.wasm.gz:0x16ecc2c
    at test.wasm.gz:0xf00989
    at invoke_ii (test.framework.js.gz:3)
    at test.wasm.gz:0x22b45c
    at test.wasm.gz:0x22b2a1
    at test.wasm.gz:0xbc030
    at test.wasm.gz:0x72aed
    at test.wasm.gz:0x16ecc2c
    at test.wasm.gz:0xf00989
    at invoke_ii (test.framework.js.gz:3)
    at test.wasm.gz:0x22b45c
    at test.wasm.gz:0x22b2a1
    at test.wasm.gz:0xbc030
    at test.wasm.gz:0x72aed
    at test.wasm.gz:0x16ecc2c
    at test.wasm.gz:0xf00989
    at invoke_ii (test.framework.js.gz:3)
    at test.wasm.gz:0x22b45c
    at test.wasm.gz:0x22b2a1
    at test.wasm.gz:0xbc030
    at test.wasm.gz:0x72aed
    at test.wasm.gz:0x16ecc2c
    at test.wasm.gz:0xf00989
    at invoke_ii (test.framework.js.gz:3)
3test.wasm.gz:0xe0305a Uncaught RuntimeError: null function or function signature mismatch
    at test.wasm.gz:0xe0305a
    at test.wasm.gz:0xde1dd1
    at JS_ScreenOrientation_eventHandler (test.framework.js.gz:3)
$func41889 @ test.wasm.gz:0xe0305a
$Ki @ test.wasm.gz:0xde1dd1
JS_ScreenOrientation_eventHandler @ test.framework.js.gz:3
test.wasm.gz:0xe0305a Uncaught RuntimeError: null function or function signature mismatch
    at test.wasm.gz:0xe0305a
    at test.wasm.gz:0xde1dd1
    at JS_ScreenOrientation_eventHandler (test.framework.js.gz:3)

**Comment by KWJ1019** [comment]
@RostislavStoliarchuk hi, how you resolve this issue?
