### ISSUE TITLE
Newton error

### ISSUE THREAD

**Issue by molonlabe1337** [suriyun-production/turnbase-rpg-docs#201]
hello I  purchased your turnbased kit,

on a fresh project unity 2021 im getting this error and cant find a fix any advice? thank you

```
Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included on the current platform. Only one assembly with the same name is allowed per platform. (C://PackageCache/com.unity.nuget.newtonsoft-json@2.0.0/Runtime/Newtonsoft.Json.dll)

Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included on the current platform. Only one assembly with the same name is allowed per platform. (Assets/RPGGame/Core/Plugins/Newtonsoft.Json.dll)
```

edit: thanks!

**Comment by insthync** [comment]
If you saw a message like this again, find a file whose name was mentioned (in this case, it is `Newtonsoft.Json.dll`) then delete it.

So you have to delete `Assets/RPGGame/Core/Plugins/Newtonsoft.Json.dll`
