### ISSUE TITLE
Multi-toggle does not work when leveling up.

### ISSUE THREAD

**Issue by SEUNGHWANYOUN** [suriyun-production/turnbase-rpg-docs#202]
When leveling up, it is set to Mute Toggle, but the status value is automatically changed to Toggle when the game is played.

use version 1.19
![image](https://user-images.githubusercontent.com/29048275/145744899-0c5b908b-d04f-4e7e-b45e-01bb9bb7fd3b.png)

**Comment by insthync** [comment]
Oh, it must be multiple toggle, I will fix it.

**Comment by insthync** [comment]
Fixed in 1.20

**Comment by SEUNGHWANYOUN** [comment]
Thank you, but I've already revised a lot of things. It's hard to update the version. Can you tell me which part of the source code should I modify?

**Comment by SEUNGHWANYOUN** [comment]
Found the part and fixed it
