### ISSUE TITLE
4 errors on fresh project

### ISSUE THREAD

**Issue by Syphon77** [suriyun-production/turnbase-rpg-docs#205]
Getting the below errors on a fresh project. Unity 2020.3.27. Followed the Getting Started guide and restarted Unity. Searching for "Newtonsoft" in Unity did not yield any results.

Assets/RPGGame/Core/Scripts/GameService/Implement/LiteDb/LiteDbGameService.cs(6,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

Assets/RPGGame/Core/Scripts/GameService/Implement/SQLite/SQLiteGameService.cs(6,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

Assets/RPGGame/Core/Scripts/GameService/Implement/SQLite/SQLiteGameServiceHelpers.cs(3,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

Assets/RPGGame/Core/Scripts/UI/Mail/UIMail.cs(1,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

**Comment by insthync** [comment]
Go to your project folder then `/Packages` edit `manifest.json`, Add 
```
    "com.unity.nuget.newtonsoft-json": "2.0.2",
```
![Screenshot_44](https://user-images.githubusercontent.com/2697550/152091846-1b08d1a4-d411-44a4-a346-1b81d1e6a619.png)

It was included with the version control package which was included when creating a new project, Unity change it again? :(

**Comment by Syphon77** [comment]
That worked and I see you updated the online guide. Excellent support!!!
