### ISSUE TITLE
[BUG] IAP - openssl_verify(): supplied key param cannot be coerced into a public key

### ISSUE THREAD

**Issue by sdk2016** [suriyun-production/turnbase-rpg-docs#206]
When i purchase an IAP item, successfully pay with google, i got error when contacting the php webservice. Please help, thank you

**====================
THE RESULT
====================**
```

 [POST->Error] ?action=google-play-buy-goods&logintoken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTIsInByb2ZpbGVOYW1lIjoieXJ5cnlyIn0.-PAUZ_TFartgp9B6uEOSl3ecw3JSn7mrcCaa9OC8vio HTTP/1.1 500 Internal Server Error <!DOCTYPE html>
<html>
<head><title>500 Internal Server Error</title></head>
 <body>
<h1>Internal Server Error</h1>
<p>openssl_verify(): supplied key param cannot be coerced into a public key</p>
<pre>[turn/fatfree/lib/base.php:2342] Base->error()
[turn/functions/Billing.php:67] openssl_verify()
 [turn/functions/Billing.php:121] VerfifyGooglePlayBilling()
 [turn/index.php:225] AndroidBuyGoods()
 [turn/index.php:374] {closure}()
</pre>
 </body>
</html>

```
**===========================
THE POST DATA
===========================**
`
[POST->Data] ?action=google-play-buy-goods&logintoken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTIsInByb2ZpbGVOYW1lIjoieXJ5cnlyIn0.-PAUZ_TFartgp9B6uEOSl3ecw3JSn7mrcCaa9OC8vio {"iapPackageDataId":"diamond50","data":"{\"orderId\":\"GPA.3357-2493-1342-81997\",\"packageName\":\"com.mydom.com.mygame\",\"productId\":\"diamond50\",\"purchaseTime\":1644104890782,\"purchaseState\":0,\"purchaseToken\":\"kdcefbiphbhbolpegplmonck.AO-J1OyMXcfM_XzHJ0FH5ce0NzKuiqcBrf-eVfnskoIirLgy17fcTitJzkEqdSfcjZSaMEasHnIJ2tECGnJ_mrB-y95ZFdK0xM6Fp1QMcZpRpwo9sMypa0k\",\"acknowledged\":false}","signature":"Lt2MFnLzIDCvIgdNRTNz9ReDxCdOteua08HjXKiBFpyV8UnXRkMrmieC6oHmzQL8BLoYBId9aH/mBHoe07easTFOvyPQ414goc0YiL9mQZBpcxYxVqxNVpLUJYh7RyeqiUlfuuqgWHXqnVxvIA8xoVqsBKmVYJmJuZY4ZXJbI4lL8jjb90WGVL6c7PBCHNlafpSaiRbEKWKYQfeWHQeaPoulpXd/KK00SZmJW7Fp5ja8sd047E2lLHR6R1tEG60PSOJKojjRhXHhAVE8WdlTrntQ38sKa2UJxxU8rpg/MYfAK6/4M88OlgOfqjtn+ovQ7LDViUajTMvTy8DDCtRqNA=="}`

**Comment by insthync** [comment]
Did you set `play_public_key` config in `config.ini` correctly?

**Comment by sdk2016** [comment]
Great, it's work now. Thank you for your support. :)
