### ISSUE TITLE
I want to be able to use the ingredients together when using evolutionary functions.

### ISSUE THREAD

**Issue by SEUNGHWANYOUN** [suriyun-production/turnbase-rpg-docs#208]
Hello

Currently, when using evolutionary functions, only equipment materials can be used for equipment evolution, and only character materials can be used for character evolution.

What should I do to make it possible to use even when material items evolve?

Thanks

**Comment by insthync** [comment]
You can change filter setting at `Game Database`

![Screenshot_969](https://user-images.githubusercontent.com/2697550/155531003-9f0377fb-9fa1-4fe0-92b0-06d7c2377c05.png)

**Comment by SEUNGHWANYOUN** [comment]
Thanks~ I find

**Comment by SEUNGHWANYOUN** [comment]
but i want evolve filter

**Comment by insthync** [comment]
How the filter work?, I don't get it.
