### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by imNoty0** [suriyun-production/turnbase-rpg-docs#209]
Is there any prediction for the next update and what is being done?

**Comment by insthync** [comment]
No plan yet, do you have any suggestions for the next update?, it doesn't have any interesting suggestions nowadays.

**Comment by imNoty0** [comment]
@insthync 1- Some system where you could put characters to train automatically (at that time the character cannot be used) and at each end of training you will receive an amount of EXP( You can choose between Daily and Weekly.)

2- [ITEM] (Pieces) will be a type of material that having a certain amount could transform into a hero.

3- [ITEM] Chests, when opening chests could come random predefined items or all items.

3- Individual servers, games in this style most have split servers where new ones are opened if the old one is full or very old, this gives freedom for new players to level up and want to reach the top of the ranking

4- VIP SYSTEM

5- Login Daily Rewards (One basic thing is important)

6- Event ranking (invasion), show players who dealt the most damage to the boss and what reward they will receive

7- Codex rewards for completing a character collection, things like diamond and gold, and also stat bonuses if you are using all characters from the same collection on your team.

8- General warnings (A bar appears above every time a player wins a very high star character warning all other players) this could also be used to warn of events among other things

9 - Daily or weekly item shops.

10 - Rewards roulette

11- Code system

I know it can be a lot, but they are essential for this type of game, I am very excited that you will update


Also, do you have a discord group? if you don't have one, it's better to create it, because other people can help with ideas and many other things
