### ISSUE TITLE
How to change weapon on character model ?

### ISSUE THREAD

**Issue by AeonTR** [suriyun-production/turnbase-rpg-docs#211]
What I want is that I added new 3d item models to the game, when I put them on the character in the inventory, I want the character to change in the weapon in his hand, but I couldn't do it, can you show me a way?

**Comment by insthync** [comment]
You have to set the equipment slot name and the item container transforms to your character entity

![Screenshot_1013](https://user-images.githubusercontent.com/2697550/161361737-9cbb0996-a782-4ac4-b068-5e40c7a1cb49.png)

Then set the slot name and equipment model prefab to your item game data

![Screenshot_1014](https://user-images.githubusercontent.com/2697550/161361738-da135549-3341-4d53-a00e-1647692f4f36.png)
