### ISSUE TITLE
Count does not add up when acquiring items.

### ISSUE THREAD

**Issue by SEUNGHWANYOUN** [suriyun-production/turnbase-rpg-docs#213]
hi

Every time a new item is acquired, it does not add up from the existing item and the number does not go up. That's why I keep getting new items.

thanks

**Comment by insthync** [comment]
An equipment?

**Comment by SEUNGHWANYOUN** [comment]
equipment & material

**Comment by insthync** [comment]
![Screenshot_1044](https://user-images.githubusercontent.com/2697550/163970461-0d42f52a-4ef7-4895-b211-e7f26f0ae15d.png)

Did you set max stack?

But equipment can have only 1 max stack because each equipment are difference

**Comment by SEUNGHWANYOUN** [comment]
I forgot sorry Let me check

**Comment by SEUNGHWANYOUN** [comment]
it is working but
<img width="575" alt="스크린샷 2022-04-21 오후 12 41 53" src="https://user-images.githubusercontent.com/29048275/164367547-d3e794c6-ccc2-4cf4-a063-1b495267d08e.png">

input Text Amount error
![image](https://user-images.githubusercontent.com/29048275/164367847-682efdc9-f1b6-47d1-bbd2-4ba21b75b87d.png)
![image](https://user-images.githubusercontent.com/29048275/164368052-06d79935-0993-4f3d-a65b-cfc55d90b113.png)

NullReferenceException: Object reference not set to an instance of an object
UIItem.SetupInfo (PlayerItem data) (at Assets/RPGGame/Core/Scripts/UI/Player/UIItem.cs:369)
UIItem.Clear () (at Assets/RPGGame/Core/Scripts/UI/Player/UIItem.cs:339)
UIDataItem`1[T].UpdateLogic () (at Assets/RPGGame/UIUtilities/Scripts/UIDataItem.cs:86)
UIDataItem`1[T].Update () (at Assets/RPGGame/UIUtilities/Scripts/UIDataItem.cs:71)
UIItem.Update () (at Assets/RPGGame/Core/Scripts/UI/Player/UIItem.cs:154)

**Comment by insthync** [comment]
This one was fixed, not sure when, if you still found this issue, tell me then.
