### ISSUE TITLE
How could I get value in scriptable object of skills?

### ISSUE THREAD

**Issue by lionforest** [suriyun-production/turnbase-rpg-docs#214]
Hello, how can I get these in script?

![skill](https://user-images.githubusercontent.com/13402095/163684377-3c358087-c220-4803-9586-95f024503a11.PNG)

There's nothing named "Attacks" under CharacterData.skills. :(

Please help me.

**Comment by insthync** [comment]
How you are going to use it ?

**Comment by insthync** [comment]
```
        CharacterItem character;
        (character.skills[0] as Skill).attacks
```
