### ISSUE TITLE
The evolutionary function doesn't working

### ISSUE THREAD

**Issue by SEUNGHWANYOUN** [suriyun-production/turnbase-rpg-docs#215]
Hi.

The evolutionary function doesn't working

If you don't put the ID value of the item in "Unity", it's normal.

but

If you insert the ID value of the item in "Unity", you will not be able to get the item to evolve.

Thank you.

**Comment by insthync** [comment]
I don't get it

**Comment by SEUNGHWANYOUN** [comment]
hi

evolutionary function working if id is null
![image](https://user-images.githubusercontent.com/29048275/163948691-d3b124bf-9b7b-4b92-9d11-96cc13666c4b.png)

evolutionary function doesn't working
![image](https://user-images.githubusercontent.com/29048275/163948945-41994246-999f-41b8-b2de-a0d6a982ccab.png)

However, the level-up function is normal with or without the id.

**Comment by insthync** [comment]
Okay, I will check it.

**Comment by SEUNGHWANYOUN** [comment]
Have you confirmed the evolution?

**Comment by insthync** [comment]
As I test I still can evolve characters, let's make an appointment to check on your PC via AnyDesk?

**Comment by SEUNGHWANYOUN** [comment]
Then thank you. Is the time on June 17th okay?
Or
Tell me a convenient date
ps: Please forward the schedule by email

**Comment by insthync** [comment]
Okay, when? 8 am GMT ?

**Comment by SEUNGHWANYOUN** [comment]
ok 8 am GMT is good

send email (ittipon.bay@gmail.com) my AnyDesk info

**Comment by SEUNGHWANYOUN** [comment]
hi
anydesk
309043143

2022년 6월 16일 (목) 오후 5:21, Ittipon Teerapruettikulchai <
***@***.***>님이 작성:

**Comment by SEUNGHWANYOUN** [comment]
I'm waiting. What's the matter?>

**Comment by insthync** [comment]
Not sure is it working after I changed codes ?

**Comment by SEUNGHWANYOUN** [comment]
Thank you very much. It's normal at the moment.
I will ask you if I have any questions during the process.
