### ISSUE TITLE
Can it work with 2D?

### ISSUE THREAD

**Issue by QmaxOu** [suriyun-production/turnbase-rpg-docs#216]
Hello I want to make a game with your asset, however within budget I decided to make it with 2D.
So I want to ask some questions about in your asset. Can all 3D things be replaced with 2D with less pain?

**Comment by insthync** [comment]
Yes, but you have to learn how to use sprite and animator.

**Comment by QmaxOu** [comment]
> Yes, but you have to learn how to use sprite and animator.

Of course I understand some code should be changed.
Anyway, thanks. Do you have a discrod channel for discussion and so on?

**Comment by insthync** [comment]
In the version: `1.24`

* * *

* Add `doNotRotate` field and `HeadDirection2D` property to entity movement component, can use them for your 2D character, set `doNotRotate` to `TRUE` to not rotate your character transform while moving, and use `HeadDirection2D`'s value to adjust to sprite.
