### ISSUE TITLE
Problem with UIAttributes not update

### ISSUE THREAD

**Issue by bma42** [suriyun-production/turnbase-rpg-docs#22]
Hello, I am working on the UI of my game. I have a problem when I equip an object with for example + 10 life,  UIAttributes is not updated.
I checked on an unmodified version it works normally.
However the +10 life
 is taken into account once in play (battlescene).
![Sans titre](https://user-images.githubusercontent.com/19147694/72706004-29f2d980-3b5d-11ea-98c8-f202550fb32d.png)
![Sans titre2](https://user-images.githubusercontent.com/19147694/72706023-3aa34f80-3b5d-11ea-9ec1-ac305990d956.png)
![Sans titre3](https://user-images.githubusercontent.com/19147694/72706035-4262f400-3b5d-11ea-9399-b1c26a28fe1b.png)
![Sans titre4](https://user-images.githubusercontent.com/19147694/72706050-4f7fe300-3b5d-11ea-885b-7f71be0a91f3.png)
![Sans titre6](https://user-images.githubusercontent.com/19147694/72706057-573f8780-3b5d-11ea-90de-ee39e445be7b.png)
Anyone have a solution? Thank you

**Comment by bma42** [comment]
![Sans titre6](https://user-images.githubusercontent.com/19147694/72706379-2ca1fe80-3b5e-11ea-8568-fe80ec7fff99.png)

**Comment by insthync** [comment]
Now I'm checking it.

**Comment by insthync** [comment]
Not sure it's not updated for every stats or just HP ?

**Comment by bma42** [comment]
It's for every stats.

**Comment by surycr** [comment]
how u can change life porcent

**Comment by insthync** [comment]
@surycr In `UICharacterStats`  component it has a field named `textHpPerMaxHp`, that is it.
@Koodetat  As I try, seems like it was fixed.
