### ISSUE TITLE
Hi, insthync , I am a fans of Turnbase RPG Template.

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#221]
I used your game(Turnbase RPG Template) for a long time.And I like it a lot.But if you can, I hope you can try to develop a new gameplay.
Because more and more turn-based games are changing based on player preferences.Especially the combat system gameplay like 《AFK Arena》.
Can your team develop a game template with combat gameplay like 《AFK Arena》? I believe that many developers and players will enjoy this game template.

The sincerity anticipates your reply.

**Comment by Ragingsura** [comment]
Don't waste your breath honestly  he doesn't  care about the turn-based kit you would be better of getting CBS from unity store it already  comes with well developed  back end  systems  with constant  update for you to build upon

**Comment by Ragingsura** [comment]
https://user-images.githubusercontent.com/52991546/188324463-957b6720-c614-4d5a-93dc-8762ae8398ca.mp4

**Comment by insthync** [comment]
If you can integrate CBS for your game then you can use it

**Comment by Ragingsura** [comment]
> If you can integrate CBS for your game then you can use it 

seems like a better step forward  than sitting  and waiting  for you to actually  change your mind a care more about this kit

**Comment by insthync** [comment]
Agree, it will be better, if anyone who's going to make their games, should try to do something not just wait for others for help.

**Comment by insthync** [comment]
@TankLin2017 I did not it the game yet, but I guess it is like an idle rpg games, is it right?

**Comment by Ragingsura** [comment]
> Agree, it will be better, if anyone who's going to make their games, should try to do something not just wait for others for help.

but the was  the thing I wasn't just sitting and waiting i actually  had to learn to get things done but I already had a lot of progress with your kit but the lack of any new update or feature implementation kill any progress made i have no hate towards you or problem dont get me wrong I think you do an amazing  work I just  had hope you would show this kit as much love as you did the mmo kit especially with how much potential it has but after years that hope faded away.

**Comment by TankLin2017** [comment]
> @TankLin2017 I did not it the game yet, but I guess it is like an idle rpg games, is it right?

I am so glad to hear from you.
Yes，because more and more players prefer idle rpg games.
The Google Store is full of these types of games.
So if you can design a game template like this, I believe developers and players will love it.
Please grant our little wish...

**Comment by TankLin2017** [comment]
> Don't waste your breath honestly he doesn't care about the turn-based kit you would be better of getting CBS from unity store it already comes with well developed back end systems with constant update for you to build upon

I think you must have been waiting for a long time. Let's study together and hope insthync can help us.
And thank you for telling me about CBS, my friend.

**Comment by insthync** [comment]
Or should I make a CBS integration for the kit?

**Comment by Ragingsura** [comment]
> Or should I make a CBS integration for the kit?

if you can I would really much  appreciate it

**Comment by TankLin2017** [comment]
> Or should I make a CBS integration for the kit?

I'd like to see a new combat gameplay similar to 《AFK Arena》.

**Comment by insthync** [comment]
Didn't decide to do it yet, I don't know how it should be calculated while players are offline, but while online, it is just like when entering a battle scene with auto-battle enabled which is already included in the kit.

**Comment by TankLin2017** [comment]
> Didn't decide to do it yet, I don't know how it should be calculated while players are offline, but while online, it is just like when entering a battle scene with auto-battle enabled which is already included in the kit.

I look at the combat play of AFK, the hero has the concept of front, middle and back, the front row moves and attacks the nearest enemy, the hero of the middle and back row attack is the same, but the distance is different.

**Comment by shubhank008** [comment]
> Didn't decide to do it yet, I don't know how it should be calculated while players are offline, but while online, it is just like when entering a battle scene with auto-battle enabled which is already included in the kit.

Probably the logic of the auto-battle will need to be done on server side as I think in all these idle games, the server does the auto-battle and in many cases directly just computes the result of battle after X amount of idle time.  
To be honest, don't think this kind of functionality is worth it compared to other new additions that can be done, specially incorporating the PUN/multiplayer repo into the main game/code itself  

PS: Although I think @TankLin2017 is request for that card-skill and row/position based combat system instead of idle-gameplay

**Comment by insthync** [comment]
As I see features in CBS, I saw just a few features that aren't included in turnbase RPG kit such as daily login, roulette

So I won't implement CBS, because it having just a few difference but would take more time than just add it to the php service,

I actually made a generic daily reward service, but it needs some modification to make it work with the kit, I want to ask you guys here if you guys can use nodeJS. if not then I won't use it because I don't want to teach you to use it, then I have to implement a daily reward for PHP service.

@TankLin2017 about some game mechanics like what you requested I think it must be a new assets package that I have to create it.

**Comment by Ragingsura** [comment]
> As I see features in CBS, I saw just a few features that aren't included in turnbase RPG kit such as daily login, roulette
> 
> So I won't implement CBS, because it having just a few difference but would take more time than just add it to the php service,
> 
> I actually made a generic daily reward service, but it needs some modification to make it work with the kit, I want to ask you guys here if you guys can use nodeJS. if not then I won't use it because I don't want to teach you to use it, then I have to implement a daily reward for PHP service.
> 
> @TankLin2017 about some game mechanics like what you requested I think it must be a new assets package that I have to create it.

as much  as they are similar  CBS has more interaction, progression  and social aspects thats more customizable by both players and developers leading to more variation in game play 

ex player profile, auction, better loot box, battlepass vip, daily weekly  and monthly  quest, guild instance, guild pvp, events etc store that you can be customizable with sales item rotation  limited on how much players can buy daily weekly  or monthly I can ramble on about  the amount of features CBS has but the point will be missed.

**Comment by insthync** [comment]
@Ragingsura Can you buy it for me?

**Comment by Ragingsura** [comment]
> @Ragingsura Can you buy it for me?

i dont mind buying you the asset or even donating to you but what would that do for the updates of the asset because if I remember correctly  the last time I funded a feature but never saw it get released.

**Comment by insthync** [comment]
Which features?

**Comment by Ragingsura** [comment]
> Which features?

the live pvp/arena

**Comment by insthync** [comment]
Isn't it already there?

**Comment by insthync** [comment]
Isn't it already there?

**Comment by Ragingsura** [comment]
> Isn't it already there?

no its not the live quee pvp

**Comment by insthync** [comment]
What? I don't get it, it has an offline PVP arena and also an online PVP arena, it is not enogh?

**Comment by Ragingsura** [comment]
> What? I don't get it, it has an offline PVP arena and also an online PVP arena, it is not enogh?

unless i missed it but online pvp wasn't available you had to fight bots of other players  if i did and you add it my bad

**Comment by insthync** [comment]
https://www.youtube.com/watch?v=IvLzh4AmJTk ?

**Comment by Ragingsura** [comment]
> https://www.youtube.com/watch?v=IvLzh4AmJTk ?

Okay my bad i missed that

**Comment by Ragingsura** [comment]
> @Ragingsura Can you buy it for me?

give me your email and ill send it to you

**Comment by insthync** [comment]
ittipon.bay@gmail.com

**Comment by Ragingsura** [comment]
> ittipon.bay@gmail.com

sent it

**Comment by Ragingsura** [comment]
@insthync anything planned or ??

**Comment by lcgames** [comment]
> > [ittipon.bay@gmail.com](mailto:ittipon.bay@gmail.com)
> 
> sent it



> > [ittipon.bay@gmail.com](mailto:ittipon.bay@gmail.com)
> 
> sent it

@Ragingsura hello my friend, could you share the CBS to me? i want to learn it. thank you.    young2015@yeah.net
