### ISSUE TITLE
2d characters

### ISSUE THREAD

**Issue by crashburne** [suriyun-production/turnbase-rpg-docs#222]
Hi,when i try tô make a 2d character,in battle scene he dont stay tô a 2d pose,there is some script in character entity chance the character side?

**Comment by insthync** [comment]
In the version: `1.24`

* * *

* Add `doNotRotate` field and `HeadDirection2D` property to entity movement component, can use them for your 2D character, set `doNotRotate` to `TRUE` to not rotate your character transform while moving, and use `HeadDirection2D`'s value to adjust to sprite.
