### ISSUE TITLE
How can I change the damage formula?

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#223]
![image](https://user-images.githubusercontent.com/24680678/197429936-7b67ae7b-01ed-4b8d-be43-81c44fe3fd17.png)
Hi, insthync ,I want to change the damage formula, but I couldn't find the formula code that I could modify.
There arent in BaseDamage.cs and Damage.cs. 
Can you tell me how to  change the damage formula?

**Comment by insthync** [comment]
In `BaseGameplayRule` class

**Comment by TankLin2017** [comment]
> In `BaseGameplayRule` class

@insthync 
![image](https://user-images.githubusercontent.com/24680678/198821853-1f206a7c-22cc-48a8-9352-22a891df3bc1.png)
I make all the attributes of the hero like the picture;

![image](https://user-images.githubusercontent.com/24680678/198821919-5f38ad49-b494-4591-91a4-9c8a1751a323.png)
So if the damage formula of normal attack is like the code : damage = attack * (100 / (100 + defense))
![image](https://user-images.githubusercontent.com/24680678/198821991-6d0e10cc-346f-4c62-ab4a-a2bdef89efcf.png)
![image](https://user-images.githubusercontent.com/24680678/198822013-44828207-fd44-427e-a270-d0f550de69e1.png)
The damage of normal attack such be |9.5| = 10, but the actual damage was 21.

![image](https://user-images.githubusercontent.com/24680678/198822154-16d573b2-96a7-4281-9bb1-840ccdd66c19.png)
![image](https://user-images.githubusercontent.com/24680678/198822351-7c4bb144-9140-4c52-b19b-51e46f9b7f4a.png)
![image](https://user-images.githubusercontent.com/24680678/198822244-709a9322-5fdd-4a31-aac9-a75094e4fefb.png)
If the damage formula of skill attack is like the code : Skill damage formula = `a.fixDamage` + ((`a.pAtkDamageRate` * `a.pAtk`) - `b.pDef`) + ((`a.mAtkDamageRate` * `a.mAtk`) - `b.mDef`)
![image](https://user-images.githubusercontent.com/24680678/198822385-3df50f13-63b6-40df-81b5-0cccd1667075.png)
The damage of skill attack such be 10, but the actual damage was 15.

So I can`t understand the damage formula of normal attack and skill attack，can you help me?

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/198824071-b697a8b4-d35f-486c-9af0-611a7bf35c28.png)
I found the damage formula of skill was like this. But I still don`t know the damage of normal attack.

**Comment by TankLin2017** [comment]
I found the damage of normal attack is a.pAtk * 1 * (100 / (100 + b.pDef)) + a.mAtk * 1 * (100 / (100 + b.mDef)) , I understand, Thank you @insthync
