### ISSUE TITLE
About the floating text problem of Blood Steal 

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#224]
![image](https://user-images.githubusercontent.com/24680678/198862893-afab9aa9-ff56-49d7-aae5-f95609c8c292.png)
![image](https://user-images.githubusercontent.com/24680678/198863013-b1907208-6ecd-400e-a47c-ed16a7755448.png)
I set the Thief can steal blood from enemy, but I found the floating text of Blood Steal was at the front of enemy ,not the front of attacker.

How can the  floating text of Blood Steal be in front of attacker?

**Comment by insthync** [comment]
https://youtu.be/NX2eFH4M-hk

**Comment by insthync** [comment]
Change from `Manager.SpawnHealText((int)stealHp, this, hitCount)` to `Manager.SpawnHealText((int)stealHp, attacker, hitCount)`

**Comment by TankLin2017** [comment]
> Change from `Manager.SpawnHealText((int)stealHp, this, hitCount)` to `Manager.SpawnHealText((int)stealHp, attacker, hitCount)`

You did it ! Nice! Thank you ~
