### ISSUE TITLE
About Crit Chance、Crit Damage Rate、Block Chance、Block Damage Rate numerical display problem

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#225]
![image](https://user-images.githubusercontent.com/24680678/198863910-86b40189-48bd-446c-a54c-970fc6f2cfd6.png)
I found I can`t control the display of numerical about Crit Chance、Crit Damage Rate、Block Chance、Block Damage Rate.
How can I set the display of numerical about Crit Chance、Crit Damage Rate、Block Chance、Block Damage Rate?

**Comment by insthync** [comment]
https://youtu.be/A2wHGRhtPos

**Comment by TankLin2017** [comment]
> https://youtu.be/A2wHGRhtPos

@insthync Sorry,Maybe I made a mistake.
I can found the component of Critical Chance，but numerical of Crit Chance was wrong, I set it to be 0.2，it should be 20% .
But in fact, it is only 5%, the other attributes of Crit Damage Rate、Block Chance、Block Damage Rate were the same problems.

Do I make a mistake at somewhere?

**Comment by insthync** [comment]
![Screenshot_137](https://user-images.githubusercontent.com/2697550/198870901-1b1ffa35-1203-446f-a1ff-353f6726659e.png)

In your game database, find for `Character Base Attributes`, it is base attributes value for all characters.

**Comment by TankLin2017** [comment]
> 

Thanks!! Love you~
