### ISSUE TITLE
Adding loootbox doesn't add it.

### ISSUE THREAD

**Issue by SEUNGHWANYOUN** [suriyun-production/turnbase-rpg-docs#226]
![image](https://user-images.githubusercontent.com/29048275/199513568-2dd7c9c9-2021-4cf2-aa88-f224372ac288.png)
![image](https://user-images.githubusercontent.com/29048275/199513900-e407459d-89eb-434a-9a42-80c08e2be134.png)
![image](https://user-images.githubusercontent.com/29048275/199514084-523003ef-12af-49ab-bb1b-8c3e4f2912c2.png)
![image](https://user-images.githubusercontent.com/29048275/199515812-7f180163-53c4-4ec2-8b70-b969e4e6ab8e.png)

The lootbox is not properly exposed to clients.

**Comment by insthync** [comment]
Hmm, how was it ?

**Comment by SEUNGHWANYOUN** [comment]
You don't have to worry about my mistake Thank you.
