### ISSUE TITLE
 Daily rewards do not work.

### ISSUE THREAD

**Issue by SEUNGHWANYOUN** [suriyun-production/turnbase-rpg-docs#227]
First of all, thanks for the new feature.

No abnormality occurs when uploading to the server, but if you use the daily function, the following error is exposed and you cannot check the normal function.
(The daily function was implemented by referring to the script in Unity.)

Is it possible to attach a daily sample that can be checked in Unity? 
OR
Can you make a guide video that reproduces the function in unity?
------------------------------------------------------------------------------------------------------
[GET->Error] all-daily-rewarding HTTP/1.1 500 Internal Server Error <!DOCTYPE html>
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<h1>Internal Server Error</h1>
<p>Invalid argument supplied for foreach()</p>
<pre>[fatfree/base.php:2378] Base->error()
[functions/DailyReward.php:87] Base->{closure}()
[index.php:333] GetAllDailyRewardList()
[index.php:357] {closure}()
[index.php:688] DoGetAction()
[fatfree/base.php:1987] {closure}()
[fatfree/base.php:1786] Base->call()
[index.php:700] Base->run()
</pre>
</body>
</html>
UnityEngine.Debug:LogError (object)
WebServiceClient/<GetRoutine>d__7:MoveNext () (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:100)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

------------------------------------------------------------------------------------------------------------

[GET->Error] daily-rewarding/7DaysDailyReward HTTP/1.1 500 Internal Server Error <!DOCTYPE html>
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<h1>Internal Server Error</h1>
<p>count(): Parameter must be an array or an object that implements Countable</p>
<pre>[fatfree/base.php:2378] Base->error()
[functions/DailyReward.php:43] Base->{closure}()
[functions/DailyReward.php:118] GetClaimableDailyRewards()
[index.php:336] GetDailyRewardList()
[index.php:357] {closure}()
[index.php:685] DoGetAction()
[fatfree/base.php:1987] {closure}()
[fatfree/base.php:1786] Base->call()
[index.php:700] Base->run()
</pre>
</body>
</html>
UnityEngine.Debug:LogError (object)
WebServiceClient/<GetRoutine>d__7:MoveNext () (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:100)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

----------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/29048275/199988074-0a648d3a-8bc3-4f30-bced-1db2292ae114.png)

**Comment by insthync** [comment]
Seems like you did not export a new game database

**Comment by SEUNGHWANYOUN** [comment]
Notably, we backed up the existing data and recovered the db after running
"sql-importer.php"
Is it because "sql-importer.php" is not running normally? It is expected
that the daily compensation information will be inserted into the db and
the daily compensation details will be retrieved from the db again...

I don't know.
[image: 스크린샷 2022-11-05 오후 3.03.15.png][image: 스크린샷
2022-11-05 오후 3.02.05.png]
[image: 스크린샷 2022-11-05 오후 3.00.24.png]
[image: 스크린샷 2022-11-05 오후 2.59.15.png]

**Comment by insthync** [comment]
I don't get what you want to tell me.

you cannot update to 1.21 ?

**Comment by SEUNGHWANYOUN** [comment]
There are no additional corrections after the error was exposed. I checked that it was applied normally the next day, thank you.

ps: The id value entered a json id value rather than an object id value...
2022년 11월 5일 (토) 오후 7:54, Ittipon Teerapruettikulchai <
***@***.***>님이 작성:
