### ISSUE TITLE
Dear insthync，Can turnbase add some new skills？ 

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#228]
@insthync , I find some interesting skills at other turnbase games .
These skills make the battle highly strategic，so I want to know is it possible that you can make a skill package.
I`d like to buy it very much, please.

These skills are like this :
1. Pursue the enemy : When one hero attack the enemy, another hero will attack this enemy after his attack ;
2. Energy hood: Giving one Ally a energy hood buff which can absorb attack damage by enemy;
......

I can write a skill list，if you can help me ... by the way , do you have Alipay？I can pay for the skill package at another way .

**Comment by insthync** [comment]
How does attack damage absorbing work? it has buff which increases def stats, how is it different?

**Comment by insthync** [comment]
All done in `1.24`

* * *
* Add provoke skill, setup in skill data -> attacks -> provoke chance and turns
* Add physical damage reduction rate, magical damage reduction rate and all damage reduction rate to attribute data use, it will reduce damage by this value (ex. formula: `pDmg -= (defenderAttributes.pDmgReductionRate + defenderAttributes.allDmgReductionRate) * pDmg`)

**Comment by TankLin2017** [comment]
> * Add provoke skill, setup in skill data -> attacks -> provoke chance and turns

Oh~You're always awesome!

**Comment by TankLin2017** [comment]
> * Add provoke skill, setup in skill data -> attacks -> provoke chance and turns

Oh~You're always awesome!
