### ISSUE TITLE
 I would like to pay for plugins

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#229]
I love how the package has improved, and I would like certain things more, I saw that you did it for donations, I would like to be able to include events like roulette, battle pass, also if there is a possibility of counter skills

**Comment by insthync** [comment]
The roulette was added, if you want to pay then just pay, amount is up to you via https://ko-fi.com/insthync

**Comment by insthync** [comment]
The counter stats was added, if you really want to pay then just pay, amount is up to you via https://ko-fi.com/insthync
