### ISSUE TITLE
problem with particules in spells

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#23]
![image](https://user-images.githubusercontent.com/43394702/72864429-95da5c80-3c99-11ea-8d50-0b3441c8ebab.png)

why is that

**Comment by insthync** [comment]
My game effect script not supports legacy particle system yet, I have to add codes to the game effect script

**Comment by surycr** [comment]
aaaa thx

**Comment by insthync** [comment]
But Unity said they will deprecate the legacy particle systems. So be aware of using them.

**Comment by insthync** [comment]
As I check, the problem occurs because it can't find the particle system component. It was in the array after called `GetComponentsInChildren()` function, not sure when it lost. So I made it avoid empty component before settings the emitter.
[TBRPG_GameEffectCheckForNullComponents.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/4096503/TBRPG_GameEffectCheckForNullComponents.zip)

**Comment by surycr** [comment]
wuoo u are amazing i will test

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/72925919-1e4c1200-3d19-11ea-8e3c-e4fa21847ed0.png)

**Comment by insthync** [comment]
Your particle game objects have destroy scripts ?

About this error if it's not break your gameplay you can ignore it.

**Comment by surycr** [comment]
yes i have destrod script

**Comment by insthync** [comment]
You can set GameEffect → isLoop to True, to let your scripts destroy it. Because when isLoop is false my script will destroy itself within lifetime.

**Comment by surycr** [comment]
@insthync  i test en 2 mobils and the same error with the stamina is =0 i was close unity and open and the error is the same i need erase that account if a i need test

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/73308804-a97c4a80-41e6-11ea-9017-dbe1a62138db.png)

**Comment by insthync** [comment]
You should post new issues, this is not relates to particles.
