### ISSUE TITLE
Errors on fresh install

### ISSUE THREAD

**Issue by TheMightyHades** [suriyun-production/turnbase-rpg-docs#231]
Hi, im having a few issues on the editor...

Version 2020.3.26f1

![Untitled-1](https://user-images.githubusercontent.com/60259329/211188326-69b15a4f-b634-497e-a9bb-622451fc96f6.png)
![Untitled-2](https://user-images.githubusercontent.com/60259329/211188328-ead6fb27-4f50-4666-b824-bb602ff0a7bb.png)

**Comment by TheMightyHades** [comment]
Please help, I've tried various versions of unity etc uninstalling and re-downloading the package and nothing much is working

**Comment by insthync** [comment]
In `LiteDbGameServiceItem.cs` file, find for `DoGetAvailableFortuneWheelList` 

And delete `result.error = GameServiceErrorCode.NOT_AVAILABLE;`

Or setup and use PHP web-service
https://github.com/insthync/rpg-php-service

**Comment by TheMightyHades** [comment]
amazing ty
