### ISSUE TITLE
Any New updates planned 

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#232]
I would honestly want to return if this will get more content and update this asset really has potential 

Need 
Power rating
Formation lock to specific roles 
Formation limit amount of characters 
Battlepass 
Vip 
Guild wars
Skill upgrade
Add boss every 5 or 10 level of tower 
Add buffs to the tower after 6 level
Ranking system 
Gm controls
Players inspect others profile in the chat
Servers
Chapters to story
Story rewards base on start completion 
Limited time shops
Recharge events

**Comment by insthync** [comment]
Return ?

**Comment by Ragingsura** [comment]
> Return ?

Yes return back I had a really good project going ![Unity_DPCbtuBxoB.png](https://user-images.githubusercontent.com/52991546/212422521-04db02d0-ae37-4c1c-bfcd-ebefe1ed4976.png)

**Comment by Ragingsura** [comment]
There wasn't much update so I put it on hold since we only get 1 update every 3 to 7 months I was hoping that wasn't the case and you would listen to some suggestions even if you wanted to be paid for those updates

**Comment by insthync** [comment]
I actually don't want to add anything, I did many things for this asset package, and it is worth 50 USD, if you hire someone to do it, you might have to pay around 6,000 USD. 

But someone still rates it 2 stars in the asset store. Why do I have to do anything for anyone who never does anything for me and devalues me?

Now I will do only what I want to do, I will still update, but no one can force me to update it frequently.

**Comment by Ragingsura** [comment]
> I actually don't want to add anything, I did many things for this asset package, and it is worth 50 USD, if you hire someone to do it, you might have to pay around 6,000 USD. 
> 
> But someone still rates it 2 stars in the asset store. Why do I have to do anything for anyone who never does anything for me and devalues me?
> 
> Now I will do only what I want to do, I will still update, but no one can force me to update it frequently.

I fully understand your statement and I would not disagree that the value of the asset is way more than it provided that's why I suggested if you need funds to update or request for updates I would love to do that just like we did for the live pvp
Plus with each update, you could sell it as a separate addon to the asset and you will still get the values worth for your hard work.
