### ISSUE TITLE
Many different issues every time i try to use this package.

### ISSUE THREAD

**Issue by TheMightyHades** [suriyun-production/turnbase-rpg-docs#233]
Every-time i try to use this package i end up with errors on a fresh install. Can you help with this ones? I really feel this great product shouldn't be having errors on a fresh install.
![Untitled-1](https://user-images.githubusercontent.com/60259329/214024297-8965d78d-5d06-49b8-a455-a3a7a06a96e6.png)

**Comment by insthync** [comment]
Did you read the getting started doc ?

**Comment by insthync** [comment]
Close because the solution is in getting started doc, and no response from you.
