### ISSUE TITLE
Template for an entire 2D game ?

### ISSUE THREAD

**Issue by elrosas** [suriyun-production/turnbase-rpg-docs#235]
Good morning yesterday I purchased this template and I wanted to know if there was any difficulty to convert it entirely to 2D everything, I have seen that you recently added a support for the rotation of the characters. But what to do for the enviroment? Can you do everything in 2D perfectly ?

**Comment by elrosas** [comment]
I have to say that every time I start a battle the 2d characters are looking towards the enemy and clearly as they are 2d you can't see anything. They would have to be rotated to be seen and I'm stuck with this.

**Comment by elrosas** [comment]
![Captura de pantalla 2023-01-24 142549](https://user-images.githubusercontent.com/48029847/214306675-89fbf68a-f9f6-4cb6-94f1-7cb13801cdf8.png)
![Captura de pantalla 2023-01-24 142620](https://user-images.githubusercontent.com/48029847/214306699-02b352d3-b589-4844-ba8b-e6fafc05839b.png)

Here are some images to show you what is the problem with my 2D characters

**Comment by insthync** [comment]
Did you try change `doNotRotate` and `HeadDirection2D` setting in `EntityMovement` component?

**Comment by elrosas** [comment]
What do you mean by change it? What I have done is to check the corresponding box. The problem is that the sprites always look at the enemies so they will never be seen. Would I have to modify something of the code?
![Captura de pantalla 2023-01-24 180122](https://user-images.githubusercontent.com/48029847/214358832-b9e2fd31-f0c1-4a71-8273-7fa6aa64aba0.png)

**Comment by insthync** [comment]
You can get `HeadDirection2D` from `EntityMovement`, you may write your script to use that value to flip character's sprite

**Comment by elrosas** [comment]
I'm sorry but I don't know how to do it without conflicting with the other scripts in the template. Could you give me a hand? I'm a bit desperate. Thank you very much.
I have tried to make the script and I only see errors and sprites that are not seen :(

Anyway I think it would be a good opportunity this post also for everyone who wants to publish a 2D game with its template. Thanks for the help really

**Comment by insthync** [comment]
Can you help me find free assets which I can use for the demo?

**Comment by elrosas** [comment]
Of course I leave you a couple of scenarios and sprites that I have tested in the template and everything works perfectly except what I said about the sprites that turn around in combat that is the only thing I can not do.

All these assets I have tested in your template 
https://assetstore.unity.com/packages/2d/characters/cute-2d-girl-wizard-155796
https://assetstore.unity.com/packages/2d/characters/100-fantasy-characters-mega-pack-222143
https://assetstore.unity.com/packages/2d/characters/2d-animated-pirate-165005
https://assetstore.unity.com/packages/2d/characters/custom-character-2d-vol-3-65471

Some scenarios 
https://assetstore.unity.com/packages/2d/environments/great-battle-background-05-sunshineforest-182785
https://assetstore.unity.com/packages/2d/characters/fairy-tale-simple-159524

I also believe that if you do this and put on your template page and everywhere that it is for 2D you will gain much more sales.

**Comment by insthync** [comment]
I don't believe that.

**Comment by elrosas** [comment]
What do you mean?
Need more help ?

**Comment by insthync** [comment]
Just don't believe that it will gain much more sales, and I don't need any help anymore, I will make the demo later.

**Comment by elrosas** [comment]
Ok perfect if you want I will list the only bugs and problems I have for the 2D project.

-The one with the camera with the screenshots above I think you understand, basically the characters look at their opponents and you will never see the sprite like that. Let's go with the screenshots it looks good.
-The environments are made to be created in 3D and many give failures in 2D. I personally have removed them
-The camera would have to be adapted to 2D but it is very easy.

For the moment it would be all, with a simple script I think it could be solved easily but I don't know how to do it.

**Comment by insthync** [comment]
Done, The repo: https://github.com/insthync/unity-tbrpg-2d 

No need to update the package from asset store, as I said.

It takes a lot of time to make an animation clip :(

Notice that it has only 1 script to rotate 2D character entities.

And in `BattleScene2D` I've to modify camera and character entity container.
