### ISSUE TITLE
The gameplay about hero`s front row and back row.

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#237]
Dear @insthync, I want to discuss the gameplay about the hero`s front row and back row.

You know that now many card turn base games, the heroes are divided into melee and ranged.

So I want the hero of melee can only attack the front-row enemies, and the hero of ranged can attack both front-row and back-row enemies.

Can you please help us? The sincerity anticipates your reply.

**Comment by TankLin2017** [comment]
In addition, do you have a donation platform that can use Alipay? I really like your game templates, I wish I could do my part.

**Comment by insthync** [comment]
Implemented in 1.25

**Comment by insthync** [comment]
https://suriyun-production.github.io/turnbase-rpg-docs/#/pages/025-formation

**Comment by TankLin2017** [comment]
> https://suriyun-production.github.io/turnbase-rpg-docs/#/pages/025-formation

Oh! Jesus! You are amazing!
You inspire my passion for making games.Love you~
