### ISSUE TITLE
About the global developing system

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#238]
Dear @insthync, With my in-depth study of games and understanding of our game system. 

I found the hero system and equipment system are both Separate development systems of heroes.

However, as the game develops, it becomes more and more cumbersome if you need to change the numerical value through both systems separately.

So can we add a global developing system that uniformly changes the numerical value of the hero later in the game?

**Comment by insthync** [comment]
Implemented in 1.25, you can set attributes in Item tier, I think it is global enough

**Comment by TankLin2017** [comment]
> Implemented in 1.25, you can set attributes in Item tier, I think it is global enough

Nice!Thx~
