### ISSUE TITLE
android manifest permissions problem 

### ISSUE THREAD

**Issue by frysomeeggs** [suriyun-production/turnbase-rpg-docs#239]
When I build the game as android, when I install it on the phone, the game gets stuck in the loading section. I think there is a problem about android manifest permissions. Can you help me with this?

**Comment by insthync** [comment]
Did you try to use logcat to see the log messages ?

**Comment by frysomeeggs** [comment]
how do i do that?

**Comment by frysomeeggs** [comment]
just wired it all works on unity the webserver and everything. but when i build apk the game plays i can log in set username but when it goes to load managescene it just stays there wont load it

**Comment by frysomeeggs** [comment]
DippeR on discord said you helped them with same problem and it was the androidmanifest permissions

**Comment by frysomeeggs** [comment]
downloading android studio now

**Comment by frysomeeggs** [comment]
what all permissions do i need to add to the androidManifest?

**Comment by insthync** [comment]
You should use adb logcat to know what is cause of error then you will know it is because of permission or other.

**Comment by insthync** [comment]
https://dev.to/insthync/how-to-watch-android-app-log-messages-with-adb-logcat-for-unity-developer-2i12

**Comment by frysomeeggs** [comment]
ok thank you
