### ISSUE TITLE
Questions about effects and combat

### ISSUE THREAD

**Issue by Jmora55g** [suriyun-production/turnbase-rpg-docs#240]
Good I have some doubts about the template.

The first would be to modify the casting times and skills effectively, what happens to me is that some attacks last 0.5sg and others last 4seconds, how do I fix that?

The second would be if the damage script lets you choose an effect but I don't want my game to have always the same effect for all attacks, how can I modify this to create multiple effects? 

And then to create mana for the game do you think it would be difficult to implement?

Thank you very much for everything

Your template is great and so is your work

**Comment by insthync** [comment]
Don't know what is `sg` means, is it seconds?

How you want it to play difference effects? difference by what?

Mana is not hard to implement
