### ISSUE TITLE
Problem about Service BUG , Ubuntu20.04 LNMP

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#241]
@insthync  Dear, I have changed the service and use Ubuntu20.04 LNMP;
The service of Turnbased is still version 1.18;
I use this tutorial all the time, It was fine until now @shubhank008  :
https://gamerzdan.com/setting-up-a-server-backend-for-your-unity3d-game-using-lemp-linux-nginx-mysql-php/

But now it doesn`t.
Every time, when I just installed MySQL, it was fine. 
![image](https://user-images.githubusercontent.com/24680678/223147127-71e8246f-134b-4cee-82e7-92976e539722.png)
But after a while, it becomes wrong like this.
![image](https://user-images.githubusercontent.com/24680678/223147019-2cf26e85-eac2-4472-87b2-0c81d0b0970a.png)
![image](https://user-images.githubusercontent.com/24680678/223149858-bf5d8734-e998-4c3a-9df9-e231b48fa62d.png)

What is the reason for this?

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/223152866-9023c3aa-4691-4f25-81f5-f013b7862d65.png)

**Comment by shubhank008** [comment]
> 

I think its trying to re-setup your database while it already exists
You probably need to remove the importer php file if you are using a already existing database

`You should remove sql-importer.php after imported`

If using request query in Unity Client, you need to change it in your web client (php) config too

`You can set use_request_query_action setting in config.ini to TRUE. And also have to set setting at client project -> WebServiceClient -> SendActionTargetViaRequestQuery to TRUE.`

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/223160495-8b765108-074f-42e0-991d-7a6321280ae5.png)
@shubhank008  Haven't talked for a long time, Do you mean I should remove sql-importer.php before MySQL re-setup the database?
Now I have removed the sql-importer.php, but it is still wrong...please help me...
![image](https://user-images.githubusercontent.com/24680678/223163211-38cde82b-3eeb-4139-b960-631a0222752f.png)
![image](https://user-images.githubusercontent.com/24680678/223163914-2c7a64e7-b9e4-44a9-8bc5-cab31882d361.png)

**Comment by insthync** [comment]
Did you try to login?

**Comment by insthync** [comment]
`TRUE` not `TURE`

**Comment by TankLin2017** [comment]
> `TRUE` not `TURE`

Oh, my god!!! Thanks for correcting me@insthync 
![image](https://user-images.githubusercontent.com/24680678/223168764-3a8e9948-ed85-4b00-9523-f371f67ad623.png)
![image](https://user-images.githubusercontent.com/24680678/223169159-de5c33fa-298d-41dd-aaaf-84a7d0f79e04.png)
![image](https://user-images.githubusercontent.com/24680678/223169364-86f5ca6b-45e4-42eb-9a95-b67f680e2c55.png)
![image](https://user-images.githubusercontent.com/24680678/223170038-672ef46a-6485-4d7a-a495-b6d419f97f0d.png)

**Comment by TankLin2017** [comment]
@insthync Oh, It is done!
![image](https://user-images.githubusercontent.com/24680678/223171197-77959681-9eb4-4142-be33-da9c762290b8.png)
I will try another project, the turn-based project of ver1.18 is OK.

**Comment by TankLin2017** [comment]
![image](https://user-images.githubusercontent.com/24680678/223172884-5b0bf4f4-16f4-466b-805b-c356f9e3bf26.png)
In the other game project, I make too many differences... 
And it becomes an unknown error... I think I have to check why...Thanks, guys. @shubhank008 @insthync

**Comment by TankLin2017** [comment]
I want to ask, how can I know the version of the client and server?
Where I can see the version? I think maybe the version between the client and server is difference 
@insthync

**Comment by insthync** [comment]
It doesn't have a version checking system / APIs.
