### ISSUE TITLE
UI for currencies 

### ISSUE THREAD

**Issue by PaleScribbles** [suriyun-production/turnbase-rpg-docs#242]
Hello!
I know it's little bit a stupid question but I'm serious i couldn't find a way to change the UI of currencies. They are showed as white square in editor although i try to change them manually also i use php web service.
Best regards..

**Comment by insthync** [comment]
Did you set the currency's icon?

Change anything to PHP web-service won't affect it, all sprites doesn't being loaded from PHP web-service

**Comment by PaleScribbles** [comment]
> Did you set the currency's icon?
> 
> Change anything to PHP web-service won't affect it, all sprites doesn't being loaded from PHP web-service

@insthync No.. I mean i still couldn't understand that where can i change it from? 

I tried to change default one as a test like renamed it "soft-currency" to "soft-currency 2" and renamed my  UI as "soft-currency" and didn't work. As other way, i deleted default one from the game folder and it became white square when i opened the game. I searched to change currency UI in game database and couldn't find an option to change it. I know maybe this is specifically weird that I can't find a way to change the UI. When i played it shows default soft currency icon but normally it shows white square in editor..

**Comment by PaleScribbles** [comment]
@insthync Hello again, please let me know.. 😔

**Comment by PaleScribbles** [comment]
I just need to know the solution please give a response :/ @insthync

**Comment by insthync** [comment]
What are you doing, please explains each step that you have done, As I read I don't get when you said you change from "soft-currency" to "soft-currency 2" then why change your UI to "soft-currency", not "soft-currency 2" ?

**Comment by PaleScribbles** [comment]
I mean i just wanted to to change currency UI and it looks like it's not possible to change them. First of all, i renamed my file as default one and nothing changed after all, it was still same UI. As i said before, when i tried to change them they appear as default UI in game and they always appear like white square in editor and also image/icon option looks empty in inspector @insthync

**Comment by insthync** [comment]
I don't get it, Please capture screenshots of where did you make changes.

**Comment by insthync** [comment]
Close because there is no response, and I can't find this is an issue, you just can't set it up, and don't tell me how you set it up.
