### ISSUE TITLE
equipment to display in CharacterModelViewer

### ISSUE THREAD

**Issue by frysomeeggs** [suriyun-production/turnbase-rpg-docs#243]
i got it all set up for the characters to show equipment items. The icon changes when i switch equipment but in the CharacterModelViewer the items are not spawned on there. Is there a way to show the items once they are equiped to show on the character in the CharacterModelViewer. So that way once you equip something it will update the char in the viewer.

**Comment by insthync** [comment]
Is it spawned in battle scene?

**Comment by frysomeeggs** [comment]
yes and i got it to update once i go out of the equipment manager back to the area but it would like to see if once they equip it to show the item on the char in the viewer or where can i grab that data or if there is a simple way to get it

**Comment by insthync** [comment]
Fixed, you can try fix it by yourself by add codes to `UIItem.cs` -> `SetupInfo` function

![Screenshot_424](https://user-images.githubusercontent.com/2697550/229374898-4a7e1750-0574-4171-8978-fddbf0864e17.png)

**Comment by insthync** [comment]
Fixed in 1.25
