### ISSUE TITLE
In game shop 

### ISSUE THREAD

**Issue by PaleScribbles** [suriyun-production/turnbase-rpg-docs#244]
Hello sorry for late reply i solved the previous problem and unfortunately didn't give a response.
I just wondered something. Is it possible to make them people buy these from in game shop (soft currency) like only client side? I mean I'm mentioning make manually shop except game data by only adding some UI and and buy buttons to the scene. If it's possible can you tell me how can i add buy script to on click() event?

**Comment by PaleScribbles** [comment]
Actually the main purpose of this question is i want to reskin in game shop tab completely and want to add some functions but i couldn't find a way to change them freely

**Comment by insthync** [comment]
You may try to use lootbox/gacha system to implement it, by having only 1 item, then when player buy it, player will the that 1 item
