### ISSUE TITLE
About Batch game value setting

### ISSUE THREAD

**Issue by TankLin2017** [suriyun-production/turnbase-rpg-docs#245]
![image](https://user-images.githubusercontent.com/24680678/230760153-8193722f-fbf5-43a0-88e8-95f395b4f9a4.png)
![image](https://user-images.githubusercontent.com/24680678/230760287-34e4fb91-7ad0-4125-a484-8823feed45c9.png)

@insthync Dear insthync, I find a new question, but that's not a problem with our game project. It's just a problem I'm hoping to solve.

Is there any tool that can read Excel sheets to batch modify the character item property value?

Now the difficulty I encountered was modifying and maintaining a large number of character attribute values, and each change had to be filled in one by one, which was very slow.

Can you help me? please.

**Comment by insthync** [comment]
No tools, have to create a new one, may make it read from CSV format to setup each data

**Comment by TankLin2017** [comment]
> No tools, have to create a new one, may make it read from CSV format to setup each data

How to make it read from CSV format to setup each data?

**Comment by insthync** [comment]
Write codes to read a file and then create game data or apply data changes to created game data files

**Comment by TankLin2017** [comment]
> Write codes to read a file and then create game data or apply data changes to created game data files

![image](https://user-images.githubusercontent.com/24680678/230761989-0a049add-3585-4cf0-83d6-4cafae908ccb.png)
I only know how to make CSV data.
But I didn't know how to make the created character data read CSV values, and it was too hard for me to write code...

**Comment by insthync** [comment]
I don't want to help anyone for free anymore, I actually helped you a lots.

**Comment by TankLin2017** [comment]
> I don't want to help anyone for free anymore, I actually helped you a lot.

Oh...@insthync, I still want to thank you , and hoping there will be a tool for players to quickly fill in values for their characters.

Besides, I found you 3D models are very cute.
![image](https://user-images.githubusercontent.com/24680678/233773849-9cb2bc99-81f2-4fbb-999b-a80e9ffccf6c.png)
