### ISSUE TITLE
When Changing To 2D - The Icons Don't Work! Not Even The Gameplay, the characters are empty! (USING THE DEMO 2D YOU MADE)

### ISSUE THREAD

**Issue by Nadezzs** [suriyun-production/turnbase-rpg-docs#247]
![image](https://user-images.githubusercontent.com/115464666/233345082-4f8db132-1032-45ef-8935-aedb8e0bc996.png)

**Comment by insthync** [comment]
Please tell me your invoice ID

**Comment by insthync** [comment]
I guess you didn't re-setup database properly, that is it.
