### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Mavado35** [suriyun-production/turnbase-rpg-docs#248]
Assets\RPGGame\Core\Scripts\GameService\Implement\WebServiceClient\WebServiceClient.cs(8,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

**Comment by insthync** [comment]
Why don't you follow getting started document?

**Comment by insthync** [comment]
https://suriyun-production.github.io/turnbase-rpg-docs/#/pages/101-fix-newtonsoft-not-found-error
