### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Mavado35** [suriyun-production/turnbase-rpg-docs#249]
I did everything according to the manual installation on Php service. The database has been installed.
![2023-04-22_20-46-28](https://user-images.githubusercontent.com/84982386/233788877-c5882a61-a572-4f9f-a7de-babc9e3b3d7f.png)
After that, errors come out.
![2023-04-22_20-44-52](https://user-images.githubusercontent.com/84982386/233788904-07ad06a4-dc36-436f-a932-b4cbc68a307d.png)
![2023-04-22_20-45-48](https://user-images.githubusercontent.com/84982386/233788906-ed5effe7-2541-4422-b32a-f22e044882e1.png)

**Comment by insthync** [comment]
It is already told what is happening, check your service url.

**Comment by Mavado35** [comment]
In Unity, do I need to register the address where I installed the files?

**Comment by insthync** [comment]
What is the URL to this page : https://user-images.githubusercontent.com/84982386/233788877-c5882a61-a572-4f9f-a7de-babc9e3b3d7f.png

**Comment by Mavado35** [comment]
http://lizardrp.ru/index.php

**Comment by insthync** [comment]
Yep, then set that URL to this

![Screenshot_453](https://user-images.githubusercontent.com/2697550/233793140-ff0fbead-e6e5-4fb5-8a9f-dc66e821eda0.png)

**Comment by Mavado35** [comment]
Doesn't help, maybe the whole problem is encryption?
![2023-04-22_22-35-13](https://user-images.githubusercontent.com/84982386/233793640-ce1c3b7b-b61e-4870-a234-f19593925b8c.png)
![2023-04-22_22-35-58](https://user-images.githubusercontent.com/84982386/233793642-ff6cf146-a407-4596-8f10-dea90ce01c4b.png)
![2023-04-22_22-36-29](https://user-images.githubusercontent.com/84982386/233793645-5570ce58-4ad7-446d-86ba-01546d7bcb7e.png)

**Comment by insthync** [comment]
I want to see the log (not the error one)

**Comment by Mavado35** [comment]
Here
![2023-04-22_23-21-27](https://user-images.githubusercontent.com/84982386/233795701-0a228e20-faf4-4910-9de7-4027094786fc.png)

**Comment by insthync** [comment]
I said: NOT THE ERROR ONE

**Comment by Mavado35** [comment]
I just don't understand where the error should be shown from.

**Comment by insthync** [comment]
I want to see debugging message not an error messages

**Comment by insthync** [comment]
Or may just send me your AnyDesk address then I will check it, and show you how to fix it very fast.

**Comment by Mavado35** [comment]
Install Any Desk

**Comment by insthync** [comment]
You can send your AnyDesk address to my email: ittipon.bay@gmail.com

**Comment by Mavado35** [comment]
![2023-04-23_00-24-46](https://user-images.githubusercontent.com/84982386/233798215-182413b8-3c86-448c-950e-9267d6ecb94f.png)

**Comment by insthync** [comment]
I guess that your host may use nginx and having a problem with .htaccess

Please read [For someone who has problem with .htaccess settings](https://github.com/insthync/rpg-php-service#for-someone-who-has-problem-with-htaccess-settings)

**Comment by Mavado35** [comment]
I also think that the problem is on the provider's side. I wrote them appeals.

**Comment by insthync** [comment]
Try to follow what I've told you.

server -> `configs/config.ini` -> `use_request_query_action` = true
client -> `WebServiceClient` -> `SendActionTargetViaRequestQuery` = true

**Comment by Mavado35** [comment]
I did as I was told above. The problem is all about connecting to the site, for some reason he doesn't want to.
![2023-04-23_19-15-58](https://user-images.githubusercontent.com/84982386/233839383-279c2af7-9ea1-4bcd-9cc2-33bc3a027495.png)
If I create a local server on a PC, then the same problem.

**Comment by insthync** [comment]
Send me your AnyDesk address, I don't to take more time to answer this anymore, just show how to make it work is easier.

**Comment by Mavado35** [comment]
331 702 035
