### ISSUE TITLE
Help with Photon pvp  ( PUN2 ARENA )

### ISSUE THREAD

**Issue by Jmora55g** [suriyun-production/turnbase-rpg-docs#250]
Good when I configure the photon server with the asset installed inside unity and everything perfect, always gives me the same error and does not let me or logearme.te I leave here the error to see if you can help me please.

![Captura de pantalla 2023-05-08 160711](https://user-images.githubusercontent.com/127048144/236846007-21b3d9b0-d28e-43e6-8247-0c30346f96c8.png)

A second question would be how to implement this pvp to my game taking into account that I have changed much of the aesthetics of the template, because if I put the scenes as it changes everything. Could you tell me what I would have to incorporate in a simple way so that my previous work is not loaded to implement the pvp?

I am a little desperate to introduce pvp in the game, please if you could give me a hand,

Thank you and a big hug
 I leave below the network error

OnGameServiceError: ERROR_NETWORK
UnityEngine.Debug:LogError (object)
GameInstance:OnGameServiceError (string,UnityEngine.Events.UnityAction) (at Assets/RPGGame/Core/Scripts/Game/GameInstance.cs:122)
GameInstance:OnGameServiceError (string) (at Assets/RPGGame/Core/Scripts/Game/GameInstance.cs:129)
UIAuthentication:OnError (string) (at Assets/RPGGame/Core/Scripts/UI/Player/UIAuthentication.cs:72)
BaseGameService:HandleResult<PlayerResult> (PlayerResult,UnityEngine.Events.UnityAction`1<PlayerResult>,UnityEngine.Events.UnityAction`1<string>) (at Assets/RPGGame/Core/Scripts/GameService/BaseGameService.cs:83)
BaseGameService/<>c__DisplayClass22_0:<Register>b__0 (PlayerResult) (at Assets/RPGGame/Core/Scripts/GameService/BaseGameService.cs:98)
WebServiceClient/<>c__DisplayClass25_0:<DoRegister>b__0 (UnityEngine.Networking.UnityWebRequest,PlayerResult) (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:316)
WebServiceClient/<>c__DisplayClass9_0`1<PlayerResult>:<PostAsDecodedJSON>b__0 (UnityEngine.Networking.UnityWebRequest) (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:127)
WebServiceClient/<PostRoutine>d__10:MoveNext () (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:180)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**Comment by insthync** [comment]
You have to setup and make it able to connect to rpg-php-service first.
