### ISSUE TITLE
POST ERROR webservice, 500 Internal Server Error

### ISSUE THREAD

**Issue by solodevelopment97** [suriyun-production/turnbase-rpg-docs#252]
Hello, I get this error when I try to use webservice client and use free hosting at 000webhost
![Screenshot (7)](https://github.com/suriyun-production/turnbase-rpg-docs/assets/102871041/838d3d57-9246-4b44-aa70-5815be30fefd)

**Comment by insthync** [comment]
Did you try to register or login after to seen that?

**Comment by solodevelopment97** [comment]
> Did you try to register or login after to seen that?

I can't click anything in play mode because of that error

**Comment by solodevelopment97** [comment]
sorry, I forgot to turn off the pause error

**Comment by solodevelopment97** [comment]
thank you finally I can use the webservice client the last question is whether this error can be fatal?
