### ISSUE TITLE
equipment accumulates when using other equipment

### ISSUE THREAD

**Issue by solodevelopment97** [suriyun-production/turnbase-rpg-docs#256]
![Screenshot (26)](https://github.com/suriyun-production/turnbase-rpg-docs/assets/102871041/abc71cda-407d-4dd8-8025-d865d1a2d46d)

**Comment by solodevelopment97** [comment]
when I try to use it with children prefabs the result is when removing the equipment everything is gone

**Comment by solodevelopment97** [comment]
![Screenshot (27)](https://github.com/suriyun-production/turnbase-rpg-docs/assets/102871041/e21d7388-dd85-4bf6-a2bd-5c235d5c69db)

**Comment by solodevelopment97** [comment]
![Screenshot (28)](https://github.com/suriyun-production/turnbase-rpg-docs/assets/102871041/99b7ada3-3c75-4bbf-967b-be6488a9567f)

how do you define if one of the equipment is installed then the previous gameobject is destroyed and a new one is installed on the equipment

**Comment by insthync** [comment]
I don't understand it.

**Comment by solodevelopment97** [comment]
thanks before, I mean when I want to use custom model equipment, the results are stacked like the first picture

**Comment by solodevelopment97** [comment]
I try to show the hair model on the character before equipping the equipment and hide the hair model when wearing the helmet equipment
