### ISSUE TITLE
ERROR sql when trying to save icon and frame in game

### ISSUE THREAD

**Issue by solodevelopment97** [suriyun-production/turnbase-rpg-docs#258]
![Screenshot (33)](https://github.com/suriyun-production/turnbase-rpg-docs/assets/102871041/8b1e3e46-c314-44e0-8812-612c82467f81)

**Comment by insthync** [comment]
Icon and frame for character?

**Comment by solodevelopment97** [comment]
save icon and frame in here

![Screenshot (34)](https://github.com/suriyun-production/turnbase-rpg-docs/assets/102871041/d0e573c8-1c48-4188-9250-80778bc47b14)

**Comment by solodevelopment97** [comment]
iam trying to delete sql line 'limit 1' in script SqlLiteGameServiceProfile and thats work without error

**Comment by solodevelopment97** [comment]
Does removing the limit affect anything?

**Comment by insthync** [comment]
Delete it, it won't affect anything
