### ISSUE TITLE
Data iconId and frameId null

### ISSUE THREAD

**Issue by solodevelopment97** [suriyun-production/turnbase-rpg-docs#259]
![Screenshot (35)](https://github.com/suriyun-production/turnbase-rpg-docs/assets/102871041/b49a3694-39d6-46c5-ac4c-15d1dde4c3a3)

**Comment by insthync** [comment]
What you want to tell me?

**Comment by solodevelopment97** [comment]
when playing the user cannot see the icon and frame that is being used by the player

**Comment by solodevelopment97** [comment]
and when I check the data player as photographed, there is no id icon and frame id data taken from the database

**Comment by insthync** [comment]
Find `SELECT * FROM player WHERE`

Then add codes to apply read data like this

![Screenshot_782](https://github.com/suriyun-production/turnbase-rpg-docs/assets/2697550/e852bbb5-18a0-4949-b6bc-6c0faa86a77d)

```
            player.IconId = players.GetString("iconId");
            player.FrameId = players.GetString("frameId");
            player.TitleId = players.GetString("titleId");
```

**Comment by solodevelopment97** [comment]
thanks and this is working fine, if anyone encounters the same script file it is in SQLiteGameServiceHelpers.cs
