### ISSUE TITLE
how can make a shield more HP 

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#26]
![image](https://user-images.githubusercontent.com/43394702/73871885-42791a00-4814-11ea-8d75-66f8ab25b1c5.png)

**Comment by surycr** [comment]
i try use fix hp but my hero lost the life

**Comment by kawaiidivinity** [comment]
Hi Surycr can i add you on discord to talk about somethings ?

**Comment by insthync** [comment]
I don't understand, you mean buff skills which increasing HP?

**Comment by kawaiidivinity** [comment]
> I don't understand, you mean buff skills which increasing HP?

Hi Suriyun can you check your mail, its Hexone thanks you very much ^^

**Comment by surycr** [comment]
My question is how do I put extra life, like when life put a gray bars, I mean something that increases life.

**Comment by surycr** [comment]
https://discord.gg/qn6rcX
