### ISSUE TITLE
This may be a strange sentence since it is translated from Japanese. I am looking forward to purchasing this asset, but there is one thing I would like to know.

### ISSUE THREAD

**Issue by kkkk1448** [suriyun-production/turnbase-rpg-docs#261]
In 2D, is it possible to load a png file for an ally character instead of an animation?

The game I want to make does not need to animate characters, so I would like to purchase this asset if it can load image files!

I am Japanese and I am translating Japanese, so I apologize if the text is strange.

**Comment by insthync** [comment]
You want to ask that it can load sprites externally or from StreamingAssets folder?

**Comment by kkkk1448** [comment]
Nice to meet you and thank you for your reply.

Can I load my own illustrations instead of the sprites used by default?

Because I intend to use still images as combat graphics,
I would like to know if image files such as png,jpg that I have prepared can be loaded as sprites!

**Comment by kkkk1448** [comment]
@insthync 
Sorry, this was my first time using GitHub and I forgot to make the mentions.

**Comment by insthync** [comment]
Oh, don't have to mention, it is always being notified

**Comment by kkkk1448** [comment]
@insthync 
![スクリーンショット 2023-12-09 120346](https://github.com/suriyun-production/turnbase-rpg-docs/assets/69753768/ff39cca5-cc60-4006-8bc8-ca9d7e611b72)

Hello. I purchased this asset after our last conversation.
However, when I try to play the game demo, I cannot play it.

I read the guide and dragged LoginScene, ManageScene and BattleScene from /Assets/RPGGame/Demo/Scenes and added them to the Scenes In Build section.
Installed newtonsoft-json package.

However, I tried to specify ".NET 4.x equivalent" for "Script Runtime Version" and ".NET 4.x" for "Api Compatibility Level" without success,
I tried reopening PROJECT and reinstalling unity, but this was the only thing I could not set.

I still tried to press the play button for the game, but it does not move from the screen as shown in the attached image, and I get a red error mark and cannot work with it.

This is my first time using unity and I am having trouble solving this problem.
What should I do?

Please ask if there is any information I am missing.

**Comment by insthync** [comment]
Some error can be ignored, you have to turn off error pause to continues

**Comment by kkkk1448** [comment]
@insthync 

Thank you very much, I didn't know you could ignore bugs!

But now I have another problem.
Before I bought it, I thought I could make a game in 2D because others had written about it on this forum,
In my case, when I try to open this asset in Unity, it is in 3D.

I can't do 3D modeling, but I have a strong preference for using my own illustrations in my games.
Therefore, I would like to know how to switch to 2D and how to use still images for models of allied and enemy characters.

**Comment by insthync** [comment]
Try download this demo https://github.com/suriyun-turnbase-rpg/unity-tbrpg-2d , extract it into project -> assets folder. But this is not a still image demo, it hard to tell you how to do it because you are very new to Unity.

**Comment by insthync** [comment]
And not all error messages are bugs

**Comment by kkkk1448** [comment]
@insthync 

![スクリーンショット 2023-12-12 220248](https://github.com/suriyun-production/turnbase-rpg-docs/assets/69753768/366f3ba8-e187-4cdb-bc2d-feed12660a31)
![スクリーンショット 2023-12-12 220323](https://github.com/suriyun-production/turnbase-rpg-docs/assets/69753768/e3bc5e4c-0048-4808-8262-60a931f2b556)

Thank you very much.
I have loaded the folder into the assets as advised, but cannot start the game.

I was not able to start the game even after enabling the ignore bug that you previously told me about.
I would like to know what is causing this, if you can help me figure it out.

**Comment by insthync** [comment]
Repeat!, not all error messages are bugs.

It cannot compile because it cannot find some script, I will check the 2D demo to make sure that it is suite with package on asset store later.

**Comment by insthync** [comment]
As I tried, it has no problem with 2D demo, which Turnbase RPG package version are you using?
