### ISSUE TITLE
BattleResult bug

### ISSUE THREAD

**Issue by bma42** [suriyun-production/turnbase-rpg-docs#264]
Hello,

I have noted two bugs:

The first one can be reproduced only when placing a single character in a formation, making it impossible to complete a stage.

`ArgumentNullException: Value cannot be null.
Parameter name: id
LiteDB.LiteCollection`1[T].FindById (LiteDB.BsonValue id) (at <751cdf508bc14b20a0c722990ee83aa8>:0)
LiteDbGameService.DoFinishStage (System.String playerId, System.String loginToken, System.String session, EBattleResult battleResult, System.Int32 totalDamage, System.Int32 deadCharacters, UnityEngine.Events.UnityAction`1[T0] onFinish) (at Assets/RPGGame/Core/Scripts/GameService/Implement/LiteDb/LiteDbGameServiceBattle.cs:125)
BaseGameService.FinishStage (System.String session, EBattleResult battleResult, System.Int32 totalDamage, System.Int32 deadCharacters, UnityEngine.Events.UnityAction`1[T0] onSuccess, UnityEngine.Events.UnityAction`1[T0] onError) (at Assets/RPGGame/Core/Scripts/GameService/BaseGameService.cs:254)
BaseGamePlayManager.WinGame () (at Assets/RPGGame/Core/Scripts/GamePlay/BaseGamePlayManager.cs:153)
BaseGamePlayManager+<WinGameRoutine>d__74.MoveNext () (at Assets/RPGGame/Core/Scripts/GamePlay/BaseGamePlayManager.cs:146)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)`

The second one has already been confirmed here #257 

tested in a fresh installation.

Thank you

**Comment by insthync** [comment]
Is this a proper way to reproduce it ? https://youtu.be/vMK1LMRnviM

Is it have any error messages for the second one?

**Comment by insthync** [comment]
The second one was fixed, but I forget to upload it

**Comment by bma42** [comment]
Yep, that's right, but you need to win the match (not give up or leave).

**Comment by insthync** [comment]
Fixed, just add a null checking.
