### ISSUE TITLE
change range projectiles for skills

### ISSUE THREAD

**Issue by spectator884** [suriyun-production/turnbase-rpg-docs#265]
Hello I was wondering if it's possible to change the range projectile for a certain skill? for example the character has an ice shard skill, so it throws an ice shard projectile instead of the RangeDamage prefab. I couldn't find an option for it if it exists. Thank you.

**Comment by insthync** [comment]
Change it by change attack animation
![Screenshot_1047](https://github.com/suriyun-production/turnbase-rpg-docs/assets/2697550/87b1c35c-e73b-4528-bba4-0ff8d68858ff)

In the attack animation you can change the prefab
![Screenshot_1048](https://github.com/suriyun-production/turnbase-rpg-docs/assets/2697550/5702b687-cb5a-4b32-be59-e77752eafe02)

**Comment by insthync** [comment]
You can create a new attack animation with difference damage prefab

**Comment by spectator884** [comment]
i see now. Thank you for the fast reply!
