### ISSUE TITLE
PunBattleScene shows 500 Internal Server Error

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#266]
Hello!
Problems with Photon Arena on a new installation. After PunLobby, PunBattleScene shows 500 Internal Server Error.
Unity version 2022.3.10f, Turnbase RPG version 1.25b, Newtonsoft Json version 3.0.2.
Web server configuration: Apache 2.4, PHP 8.0, MySQL 8.0

Turnbase RPG downloaded from here: https://github.com/suriyun-turnbase-rpg/rpg-php-service
Realtime (PUN) downloaded from here: https://github.com/insthync/unity-tbrpg-pun-arena

The errors differ only in playerId:

[GET->Error] ?action=arena-formation-characters-and-equipments&playerId=1 HTTP/1.1 500 Internal Server Error <!DOCTYPE html>
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<h1>Internal Server Error</h1>
<p>Too few arguments to function GetArenaFormationCharactersAndEquipments(), 1 passed in D:\OpenServer\domains\localhost\rpg-php-service-master\index.php on line 231 and exactly 2 expected [D:\OpenServer\domains\localhost\rpg-php-service-master\functions\Arena.php:185]</p>
<pre>[D:/OpenServer/domains/localhost/rpg-php-service-master/index.php:231] GetArenaFormationCharactersAndEquipments()
</pre>
</body>
</html>
UnityEngine.Debug:LogError (object)
WebServiceClient/<GetRoutine>d__7:MoveNext () (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:100)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**Comment by insthync** [comment]
I will check it

**Comment by brabaris** [comment]
Forgot to add screenshots...
![0](https://github.com/suriyun-production/turnbase-rpg-docs/assets/16080577/a5d98faa-271d-4c92-bca4-d104adee907c)
![1](https://github.com/suriyun-production/turnbase-rpg-docs/assets/16080577/b69db27e-e694-416a-b024-a93d343a43f9)
![2](https://github.com/suriyun-production/turnbase-rpg-docs/assets/16080577/e912759e-7ee7-4114-85a1-478ec1cafe71)

**Comment by brabaris** [comment]
Any idea what's causing the error in Arena.php?

**Comment by insthync** [comment]
Try this https://github.com/suriyun-turnbase-rpg/rpg-web-service-client/tree/master

**Comment by insthync** [comment]
Try this https://github.com/suriyun-turnbase-rpg/rpg-php-service/commit/60445ebd20d04bdcd1528b4eb569f89836473a96

**Comment by brabaris** [comment]
I did it (Removed $formationDataId from Arena.php), the error is not displayed, but working in Photon is incorrect!
There is no attack animation, the automatic attack works, although there is still time left, damage is not displayed correctly, corpses are not displayed...
I showed everything on video.
https://youtu.be/rqbaix8IDYI

**Comment by insthync** [comment]
Oh, please wait, this one seems to be hard to fix

**Comment by insthync** [comment]
Fixed, please wait for a new update
