### ISSUE TITLE
Question about SQLite Login and WebService Login

### ISSUE THREAD

**Issue by spectator884** [suriyun-production/turnbase-rpg-docs#267]
Hello, does LoginSceneSQLite supports the online features such as socials/ world chat? or is it only available on the LoginSceneWebService ? I can't seem to decide which one should I use. 

On the assetstore description, it says SQLite integration for offline games, does that mean the online features such as socials, or world chat is not available?
![Capture](https://github.com/suriyun-production/turnbase-rpg-docs/assets/107297032/5673f110-721f-43c6-94ff-2d885f61a5c3)

**Comment by insthync** [comment]
No, it is available on the loginscenewebservice

**Comment by spectator884** [comment]
> No, it is available on the loginscenewebservice

Okay gotcha, so in order to make the loginscenewebservice work I should upload the database .db file or is there a .db file? to mysql with phpmyadmin and place this file https://github.com/suriyun-turnbase-rpg/rpg-php-service on the htdocs folder? 

sorry for the questions I am not sure what to do, I appreciate any response. A simple step by step process in order for it to work would be nice. Thank you as always :)

**Comment by insthync** [comment]
Did you ever use PHP / MySQL to develop website or anything else?

The `rpg-php-service`, doesn't contains an `.sql` files but it has a `sql-importer.php` script which can be used for database structure importing and migrating, the instruction is in https://github.com/suriyun-turnbase-rpg/rpg-php-service 's read me file.
