### ISSUE TITLE
equipment skill

### ISSUE THREAD

**Issue by frysomeeggs** [suriyun-production/turnbase-rpg-docs#269]
when adding a skill to equipment it works(shows up) in the battle scene but when your in ManageScene and you view char it dosnt show up in the skills list. is there a easy fix for it to update in there?

**Comment by insthync** [comment]
I will fix it.

**Comment by frysomeeggs** [comment]
ok cool thank you. do you have a eta no rush just wondering so i know on my end like couple weeks or months or what.

**Comment by insthync** [comment]
Fixed, please wait for a new update
