### ISSUE TITLE
Stack items on GUI

### ISSUE THREAD

**Issue by rzeznick** [suriyun-production/turnbase-rpg-docs#27]
Hi there,

is it possible to show stacked items in inventory? (for example, if Item max stack has been set to 100?)

**Comment by insthync** [comment]
Yes, it's possible but I have to add some codes.
You can download the package

[TBRPG_Patch_AddAmountText.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/4168898/TBRPG_Patch_AddAmountText.zip)

Then import to your project, now your UIItem will have new field: `textAmount` set `Text` component which you want to show amount.

![Screenshot_19](https://user-images.githubusercontent.com/2697550/73999729-3322d980-4998-11ea-82b7-f7007387f8bd.png)

**Comment by rzeznick** [comment]
I got a strange issue (maybe this is the root cause of my problem) MaxStack is always set to 1 no matter what I fill in in the Equipment Item scriptable object

![image](https://user-images.githubusercontent.com/60580196/74075903-52138100-4a15-11ea-8d6e-cdd6d39844a4.png)

![image](https://user-images.githubusercontent.com/60580196/74075919-68214180-4a15-11ea-85c9-3bc84994731f.png)

**Comment by insthync** [comment]
It's equipment item?, an equipment item / character item max stack was forced to be 1

You can find in `Item.cs` around line 240
```
    public override int MaxStack
    {
        get { return 1; }
    }
```
You are going to use the item as upgrade material or upgrade part?, I think if it's a upgrade part it still should have only 1 max stack

**Comment by rzeznick** [comment]
Thanks for the hint, after I removed the overridden property it is almost working :)
![image](https://user-images.githubusercontent.com/60580196/74083881-0985b300-4a69-11ea-8c73-019bac7c6e19.png)

While I'm trying to achieve something like this:
![image](https://user-images.githubusercontent.com/60580196/74083947-d7c11c00-4a69-11ea-913a-8d8909fd2303.png)

There is some kind of grouping missing in the background logic.

As for the nature of the item - it is a shard (or blueprint) so it is strictly an upgrade material - it has no stats or any possibility to upgrade or evolve itself.



**---Edit 2020.02.11---**
I've added grouping in UIItemList.cs by changing first `SetListItems` method from this:
```
        ClearListItems();
        foreach (var entry in list)
        {
            var ui = SetListItem(entry);
            if (ui != null && onSetListItem != null)
                onSetListItem(ui);
        }
```
into this:

```
        ClearListItems();
        var groupedList = list.GroupBy(i => i.ActorItemData.name);
        foreach (var subList in groupedList)
        {
            foreach (var entry in subList)
            {
                var ui = SetListItem(entry);
                if (ui != null && onSetListItem != null)
                    onSetListItem(ui);
            }
        }
```
 
I'm still testing it to check if it doesn't have a negative impact on all game aspects (like rewards, loots upgrades, etc.) but so far so good.

**Comment by insthync** [comment]
I will help you to make the items tomorrow :p

**Comment by insthync** [comment]
I've add stackable items in the project, you can see `MaterialItem` as example
