### ISSUE TITLE
what scripts used for skill on equip

### ISSUE THREAD

**Issue by frysomeeggs** [suriyun-production/turnbase-rpg-docs#271]
i have my project on an older version that was before the skills on equipment so wasd wondering what all scripts are affected to add the skills to the list. i copyed from the equipmentitem script and it lets me add the skill but in battle it dosnt show up like in the new version.
thank you

**Comment by insthync** [comment]
![Screenshot_16](https://github.com/suriyun-production/turnbase-rpg-docs/assets/2697550/503ff52e-9635-4463-a518-12c49d673543)

I can't remember, you may try find it by right-click and choose menu like this.

**Comment by insthync** [comment]
![Screenshot_16](https://github.com/suriyun-production/turnbase-rpg-docs/assets/2697550/09261dc7-e090-446a-b6dd-c580884ffbba)

After do it, it will tells which codes/files which use the codes, I found this, I guess this is it.

**Comment by insthync** [comment]
![Screenshot_18](https://github.com/suriyun-production/turnbase-rpg-docs/assets/2697550/9f6a5f7c-ed6f-4d34-9fc9-83cf154e5c7d)


After do it, it will tells which codes/files which use the codes, I found this, I guess this is it.

**Comment by frysomeeggs** [comment]
awsome will try that thank you

**Comment by frysomeeggs** [comment]
what program are you using i tryed it in visual studio and it didnt find anything. i cant find the bottom pic section

**Comment by CreativePixel101** [comment]
that's just regular visual studio. i use 2019 and it works just fine
