### ISSUE TITLE
Separate Items from character items

### ISSUE THREAD

**Issue by CreativePixel101** [suriyun-production/turnbase-rpg-docs#273]
Hey would it be possible to separate the items from character items so  i can have different designs for both

**Comment by insthync** [comment]
I don't get it

**Comment by CreativePixel101** [comment]
am sorry English is not my first language

**Comment by insthync** [comment]
May uses pictures to show me how is it.

**Comment by CreativePixel101** [comment]
![dnplayer_SYZA2p8ARD](https://github.com/suriyun-production/turnbase-rpg-docs/assets/86085759/eca9dfd8-945e-48d8-8c0c-884b20087eb4)
![dnplayer_awj0oDlxk1](https://github.com/suriyun-production/turnbase-rpg-docs/assets/86085759/830afe5f-dcbb-4380-8618-ce569b2f1052)

**Comment by CreativePixel101** [comment]
character list design is different from Inventory item but because character list is an item i would not be able to have two separate designs for both

**Comment by CreativePixel101** [comment]
also would be much appreciated if you can add filter to items like shown in picture so items can go into different tabs for both Inventory and character list

**Comment by CreativePixel101** [comment]
thank you very much

**Comment by insthync** [comment]
Did you try to use difference prefabs for character and item?

**Comment by CreativePixel101** [comment]
> Did you try to use difference prefabs for character and item?

No i have not tried that because i thought that characters and item use one item prefab related to ui elements and functionality 
![Unity_aTaqYp0aNg](https://github.com/suriyun-production/turnbase-rpg-docs/assets/86085759/94fafbe9-5adc-4275-8ac6-191809c8d5d7)
if i was to make a new prefab that only characters use how would i go about that?

**Comment by insthync** [comment]
You can use difference prefabs here.

![Screenshot_81](https://github.com/suriyun-production/turnbase-rpg-docs/assets/2697550/0b051f4d-0c87-4df1-be6e-a37eaab0e14e)

**Comment by CreativePixel101** [comment]
Thank you very much
