### ISSUE TITLE
 Type Effectiveness

### ISSUE THREAD

**Issue by at0311** [suriyun-production/turnbase-rpg-docs#29]
I want to type a character.
For example, fire, water, wood, darkness, light, etc.
Please help me.

I am Japanese so I am not good at English.
sorry for the inconvenience.

**Comment by insthync** [comment]
You can create `Elemental` game data in `Project` tab by right click in `Project` then select `Create ScriptableObject (TurnbaseRPG)` → `Elemental` then set to `elementalEffectivenesses` and set created `Elemental` to character item or equipment item

**Comment by at0311** [comment]
What are the weaknesses and tolerances?

**Comment by insthync** [comment]
You can set `effectiveness` from 0.01 to 2, 1 = 100%, if `fire` weak to `water` you can set `water` to `fire`'s `elementalEffectivenesses` list and set `effectiveness` value to `0.5`. Then when fire character attacking water character damage will reduce 50% becauase we've set `effectiveness` to `water` = 0.5

**Comment by at0311** [comment]
Thank you very much.
