### ISSUE TITLE
PHP Host: Error Login Token

### ISSUE THREAD

**Issue by wovencode** [suriyun-production/turnbase-rpg-docs#3]
After setting up PHP service
I get ERROR_INVALID_LOGIN_TOKEN all the time
no matter if new user or existing user
clearing player prefs does not help

attached screen shows token in player prefs and below, token in database, they are different
<img width="976" alt="Screen_Shot_2019-07-22_at_08 30 41" src="https://user-images.githubusercontent.com/40817126/61611643-a105ee80-ac5c-11e9-9a8e-a5f78ef6b543.png">

**Comment by insthync** [comment]
It can login or not?, the error showing up when you enter game later after previous login?

**Comment by wovencode** [comment]
cannot login
can create new account, is also correctly inserted into db
but then when logging in, username is always empty
wants me to enter username
then i get ERROR_INVALID_LOGIN_TOKEN error
username stays empty

**Comment by insthync** [comment]
I can't reproduce this issues. you saids username is always empty, it's mean that you enter username but it still empty ?

**Comment by wovencode** [comment]
Yes, exactly.
Attached some screens and the URL to my webservice, you can test with that URL and blank project (default game data). I think its a configuration issue of my webhoster.

Webservice URL: http://grindquest.net/rpg-php-service

<img width="882" alt="Screen Shot 2019-07-24 at 19 48 44" src="https://user-images.githubusercontent.com/40817126/61816206-31eeec80-ae4c-11e9-93ff-5e2c45072f45.png">
<img width="874" alt="Screen Shot 2019-07-24 at 19 48 25" src="https://user-images.githubusercontent.com/40817126/61816207-32878300-ae4c-11e9-8fe2-76904c71ee4d.png">
<img width="1019" alt="Screen Shot 2019-07-24 at 19 45 08" src="https://user-images.githubusercontent.com/40817126/61816209-32878300-ae4c-11e9-84f7-61e65c200c54.png">

**Comment by insthync** [comment]
Please try the latest update, I try to add log when not able to login to check which data is invalid

**Comment by wovencode** [comment]
Done, still same.

shows ERROR_INVALID_LOGIN_TOKEN but does not show "loginToken:"

**Comment by insthync** [comment]
Please try new updates again

**Comment by wovencode** [comment]
looks like this now:

<img width="1053" alt="Screen Shot 2019-07-25 at 15 06 05" src="https://user-images.githubusercontent.com/40817126/61876739-d83efe80-aeed-11e9-8478-a378c62fb6ec.png">

**Comment by insthync** [comment]
I try to update .htaccess , try to upload it , and also upload phpinfo.php I want to see your server settings

**Comment by wovencode** [comment]
PHPInfo (I remove after you check it out):
http://grindquest.net/rpg-php-service/phpinfo.php

Attached is screenshot of htaccess

<img width="346" alt="Screen Shot 2019-07-25 at 19 20 56" src="https://user-images.githubusercontent.com/40817126/61894903-a5a6fd00-af11-11e9-8f32-dc68ae4a1c41.png">

**Comment by insthync** [comment]
Checked

**Comment by insthync** [comment]
I tried add `SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0` on top of htaccess file

**Comment by wovencode** [comment]
Still same.

Its clearly some configuration issue on the server.
<img width="360" alt="Screen Shot 2019-07-25 at 19 29 11" src="https://user-images.githubusercontent.com/40817126/61895252-86f53600-af12-11e9-8232-b0f80688fd96.png">

**Comment by insthync** [comment]
Okay, try update to latest commit and also update [WebServiceClient](https://github.com/insthync/rpg-web-service-client/blob/master/WebServiceClient.cs) at Unity project side. Then before start game, turn on `sendLoginTokenViaGetMethod` in `GameInstance` → `WebServiceClient`

![Screenshot_46](https://user-images.githubusercontent.com/2697550/61898729-2da5fa80-af44-11e9-9607-baf3c95e167a.png)

**Comment by wovencode** [comment]
Now it works fine!

There is one more bug in the log, besides that it works.
<img width="851" alt="Screen Shot 2019-07-25 at 20 30 18" src="https://user-images.githubusercontent.com/40817126/61899130-17377900-af1b-11e9-8fcf-9e46025fe0ac.png">

**Comment by wovencode** [comment]
solved, works very good now!
