### ISSUE TITLE
Php Server Problem

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#31]
Please help 
When I say war in the arena it gives this error.
The waiting area is constantly stopping.

![unknown (1)](https://user-images.githubusercontent.com/61230304/74824442-306da000-5319-11ea-96f8-951843cdf46c.png)
![unknown](https://user-images.githubusercontent.com/61230304/74824445-32376380-5319-11ea-9bc7-ac532b32848b.png)

And,

Can you add clan and chat for turnbase?
please give this update.
a simple public chat can be a simple clan, and the clan monster is enough.
I've been tracking for months, please help.

**Comment by insthync** [comment]
Fixed, try use new php-service codes.

**Comment by dclgamingtr** [comment]
Thank You :)
