### ISSUE TITLE
Clan and Chat system.

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#32]
Can you add clan and chat for turnbase?
please give this update.
a simple public chat can be a simple clan, and the clan monster is enough.
I've been tracking for months, please help.

It happens if the clan monster is added later.
What is important now is a clan, albeit without function.
It should be a simple chat system.
Please take care of this game as much as Mmorpg.

**Comment by insthync** [comment]
I may finish the clan system this month
