### ISSUE TITLE
evolves

### ISSUE THREAD

**Issue by at0311** [suriyun-production/turnbase-rpg-docs#33]
I want to change the appearance when the character evolves.
Is it possible.

**Comment by Maltech9** [comment]
Yes make a new model. :( An evolved unit is completely different so why not give it a different model.

**Comment by at0311** [comment]
I was able to make a new model.
But cannot reflect the changes in the new model.

Please tell me the source code.

**Comment by Maltech9** [comment]
So of the character evolved is an entire new character object, then you should have the new model dragged into the evolved form of the character. Almost like treating them as completely separate entities linked through the evolve mecanic
