### ISSUE TITLE
Give Up Error

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#35]
![42733554-c534-4133-a94c-dd727d7b0e6e](https://user-images.githubusercontent.com/61230304/75121863-437dc880-56a9-11ea-95f4-db69f5bbb89b.jpg)

The game gives an error when you press give up in the adventure section.

**Comment by insthync** [comment]
Fixed, update the service.

**Comment by dclgamingtr** [comment]
Thank you :)
