### ISSUE TITLE
Random attributes dissapearing

### ISSUE THREAD

**Issue by Maltech9** [suriyun-production/turnbase-rpg-docs#36]
I have made many items using the randomized attributes system, and when I equip them to the player, only the base attributes apply and not the random ones. They actually get deleted and the item's data gets reset to having no random attributes. Help!

**Comment by insthync** [comment]
Weird, every item's `randomAttributes` mustn't be reset, there is no any codes that change this value. It's possible that the `randomAttributes ` may not be applied but `randomAttributes ` value is reset must not.

**Comment by insthync** [comment]
I have a few questions, 
- Which service are you using, PHP or something else?
- Did you export game data before test?
- Did you do something to get item after export game data?

**Comment by Maltech9** [comment]
I am using all of the default settings, so if that is PHP then yes. 
I have not exported any data at all. This is all testing in the engine and once on my mobile device. 
The _randomAttributes_ are quite frankly deleting once the game saves any data or the item is equipped. Let me provide screenshots to show.

**Comment by Maltech9** [comment]
![afterEquip](https://user-images.githubusercontent.com/10693635/75243683-316e5980-577f-11ea-8623-e6101a5b563e.PNG)
![NoBonusStats](https://user-images.githubusercontent.com/10693635/75243686-3206f000-577f-11ea-8fdb-6472bdbb2425.PNG)
![Weapon](https://user-images.githubusercontent.com/10693635/75243688-329f8680-577f-11ea-95d1-9f9006063efc.PNG)

These images show the weapon with random attributes, me equipping them and the random attributes not applying,and then those attributes being removed from the item after

**Comment by Maltech9** [comment]
This example was taken from a download right out of the asset store and I added the random attributes  on the sword and pressed play

**Comment by insthync** [comment]
When you start game, you start with `LoginScene` or `LoginSceneSQLite` ?

**Comment by insthync** [comment]
Okay, I found the issues ocurring with LiteDB service (which start with `LoginScene`)

**Comment by insthync** [comment]
Okay, I've fixed it, if you want to update immediately, send your invoice id to contact@suriyun.com.

**Comment by Maltech9** [comment]
Yeah I logged in with SQLite

**Comment by insthync** [comment]
Seems like it was fixed, right?

You can reopen this if you still having the problem.
