### ISSUE TITLE
characterlevel

### ISSUE THREAD

**Issue by Atsushi0514811** [suriyun-production/turnbase-rpg-docs#37]
I don't want to return to level 1 as my character evolves.
What should I do.

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/75199429-b24e3680-5728-11ea-8401-0dbb1e83416f.png)

**Comment by surycr** [comment]
u need check that slot (reset item after)

**Comment by Atsushi0514811** [comment]
It was helpful.

**Comment by rzeznick** [comment]
@surycr thanks a lot!

**Comment by surycr** [comment]
u welcome
