### ISSUE TITLE
Sucking blood skill

### ISSUE THREAD

**Issue by Atsushi0514811** [suriyun-production/turnbase-rpg-docs#39]
Can I make a damage vampire skill?
A skill that recovers 50% of attack damage.

**Comment by insthync** [comment]
Will be added in next update

**Comment by Atsushi0514811** [comment]
Thank you very much.

**Comment by insthync** [comment]
`BloodStealByPAtkRate` and `BloodStealByMAtkRate` were added to the latest update.
