### ISSUE TITLE
Idea: New Combat Mode(s)

### ISSUE THREAD

**Issue by wovencode** [suriyun-production/turnbase-rpg-docs#4]
1-2 new combat modes would be nice!

Raid or Worldboss or Guild/Guild-Battle

Right now we have PVP (Arena) and PVE (Adventure) - its very good, but gets boring after a while.

Its a bit of work ;-)

**Comment by surycr** [comment]
yes nice point

**Comment by surycr** [comment]
but is good

**Comment by bma42** [comment]
Yes need this !

**Comment by surycr** [comment]
me too but i know how to that and i want add a Ui For see the action turn

**Comment by insthync** [comment]
Will gradually add guild system then guild battle :p
