### ISSUE TITLE
Arena score problem

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#41]
When the Arena also attacked someone. If you win the war, I get points. but the score does not decrease from the person who lost the attack.

**Comment by insthync** [comment]
It's not a problem, I intently did it like that.

Why do you want to decrease the opponent's score? I think it's not a good mechanic.

**Comment by dclgamingtr** [comment]
but if the score does not decrease, the score rises constantly and there is no fear of losing.

**Comment by dclgamingtr** [comment]
When he says "give up" when he is going to lose, points do not decrease.

**Comment by insthync** [comment]
As I try, when I lose the opponent my score decreases.

**Comment by dclgamingtr** [comment]
my score is falling when i lose.

**Comment by dclgamingtr** [comment]
I mean, if I win when I attack. The score does not drop from the loser.

**Comment by dclgamingtr** [comment]
![image](https://user-images.githubusercontent.com/61230304/75783160-26b05780-5d71-11ea-9df1-6528edf85140.png)


Since I made a leaderboard

**Comment by dclgamingtr** [comment]
If I win when I attack. The score of the loser must drop.

**Comment by insthync** [comment]
No, defenders score should not decrease. Because they are not intended to fight to increase their score.

**Comment by dclgamingtr** [comment]
but it is so in all general games. must lose or everyone just rises. Is it possible for you to do this, there is no point in going online.

**Comment by insthync** [comment]
Give me one example game

**Comment by dclgamingtr** [comment]
Mobile legends adventure , ıdle heroes , RAID shadow legeds

**Comment by dclgamingtr** [comment]
Idle heroes have played for years.

**Comment by dclgamingtr** [comment]
logically, I attacked, lost the war, points are dropped from me.
When I won the war. if i earn points. Why from the loser. points do not fall.

**Comment by insthync** [comment]
Because that loser does not intend to fight with you.

**Comment by dclgamingtr** [comment]
But I attack her, and I win.

**Comment by insthync** [comment]
So you collect your score why you want to decrease other score?

**Comment by dclgamingtr** [comment]
The loser has to drop the score. Otherwise only the score has to go forward.

**Comment by dclgamingtr** [comment]
It is generally unreasonable. The scoring system is only for winning. However, it must fall when I attack. It is so in all the games I play.  This isn't just for this game. Every game with an arena system is like that.

**Comment by insthync** [comment]
No score won't always go forward if the player starts the battle and lose.

**Comment by dclgamingtr** [comment]
but if i win. loser person score does not decrease.

**Comment by insthync** [comment]
Yes that is because they are not intended to fight

**Comment by dclgamingtr** [comment]
Since he doesn't want to attack. Why am I attacking? I earn.

**Comment by insthync** [comment]
Score can be reset every week or month or season.

**Comment by insthync** [comment]
Can you show me when opponents win your formation and you lose your score?

**Comment by dclgamingtr** [comment]
Of course wait

**Comment by dclgamingtr** [comment]
![image](https://user-images.githubusercontent.com/61230304/75785792-55c8c800-5d75-11ea-9cbf-11bf0d6efe90.png)

I'm going to attack SASA now.

**Comment by insthync** [comment]
No in other games

**Comment by dclgamingtr** [comment]
wait I'm downloading

**Comment by dclgamingtr** [comment]
I'm waiting for someone to attack me. I will throw a picture.

**Comment by dclgamingtr** [comment]
I an all games if someone attacks enemy in arena, and if the attacker loses, defender gains point and attacker loses point

And if attacker wins, defender loses point and attacker earns point Other wise being attacked changes nothing in game
Also because of that reason, defenders sometimes puts his lowest class army to loose point to reduce rank and later to win daily challenges

**Comment by surycr** [comment]
@dclgamingtr nice leadboard how u did that

**Comment by dclgamingtr** [comment]
@surycr  dclgamingtr@gmail.com Send email

**Comment by surycr** [comment]
ready

**Comment by dclgamingtr** [comment]
I coded it myself.

**Comment by insthync** [comment]
> I an all games if someone attacks enemy in arena, and if the attacker loses, defender gains point and attacker loses point
> 
> And if attacker wins, defender loses point and attacker earns point Other wise being attacked changes nothing in game
> Also because of that reason, defenders sometimes puts his lowest class army to loose point to reduce rank and later to win daily challenges

No, Not all games, Seven Knights, not decrease opponent score. As it's mechanic issues that can be different for each game, I won't change it now. If you want to change it you can do it in functions/Arena.php → FinishDuel, you got all source codes you can do anything.

**Comment by dclgamingtr** [comment]
![Adsız](https://user-images.githubusercontent.com/61230304/75886337-1a8fcd00-5e39-11ea-8ad9-781e657284f6.png)

when i wasn't in the game. it attacks me and my score drops.

**Comment by insthync** [comment]
I know, As I said it's about game mechanic, I won't change it now, If you want to change it you can do it in functions/Arena.php → FinishDuel, you got all source codes you can do anything. Why I have to repeat this :(
