### ISSUE TITLE
Please Mobile not work

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#42]
In version 1.11c, packaged to PC platform , the player's appearance is delayed, but it is normal in unity.

Package to Android platform, select guess login or register to log in, and it will stay in loading forever
![Screenshot_20200302-025217_Turnbase2](https://user-images.githubusercontent.com/61230304/75636576-f6fa3600-5c30-11ea-8617-ab4218aa5a71.png)

**Comment by insthync** [comment]
Did you set webservice client's url correctly?

**Comment by dclgamingtr** [comment]
It is not a php server. Neither of them is working.

**Comment by dclgamingtr** [comment]
![Adsız](https://user-images.githubusercontent.com/61230304/75773936-ea283000-5d5f-11ea-8af7-d14b62976ebe.png)

**Comment by dclgamingtr** [comment]
LoginScene and LoginSceneWebService both remain in the loading text in the same way.

**Comment by dclgamingtr** [comment]
I tried both of them individually.

**Comment by insthync** [comment]
Any error log?

**Comment by dclgamingtr** [comment]
No I get build, it goes into the game and stays like this when he says sign in.

**Comment by insthync** [comment]
Are you developer?, can't you use adb logcat?

**Comment by dclgamingtr** [comment]
I do not know how to use it. If I give teamwiever, can you look?

**Comment by dclgamingtr** [comment]
It enters the game on the computer, but the phone does not work either.

**Comment by insthync** [comment]
Send your TeamViewer info to contact email.

**Comment by insthync** [comment]
And don't send issues post to email again, please.

**Comment by dclgamingtr** [comment]
problem solved. Thank you.

**Comment by c3068296098** [comment]
怎么解决这个问题的？我也遇到同样的问题

**Comment by c3068296098** [comment]
How to solve this problem? I have the same problem

**Comment by c3068296098** [comment]
> problem solved. Thank you.

How to solve this problem? I have the same problem

**Comment by c3068296098** [comment]
> Send your TeamViewer info to contact email.

Please tell me how to solve it? I have the same problem

**Comment by c3068296098** [comment]
> > Send your TeamViewer info to contact email.
> 
> Please tell me how to solve it? I have the same problem

I only need offline. How do I set it
