### ISSUE TITLE
EquipmentItem

### ISSUE THREAD

**Issue by john540** [suriyun-production/turnbase-rpg-docs#43]
Can add passive skills to equipment?
I want to add a function.

**Comment by insthync** [comment]
Why passive skills?, an passive skills just adding stats, equipment already have settings to add stats. Why adding passive skills to do the same thing?

**Comment by john540** [comment]
I wanted to add an automatic recovery function.

**Comment by insthync** [comment]
How it work?, recovery HP every turns?
