### ISSUE TITLE
Gamesparks

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/turnbase-rpg-docs#48]
Characters, gems, gold and items are not loaded if you use the gamesparks. What could I miss?
![image](https://user-images.githubusercontent.com/47291794/77418746-61d60180-6dd8-11ea-9343-865d15fe1fb8.png)
![image](https://user-images.githubusercontent.com/47291794/77419047-d741d200-6dd8-11ea-97e5-4bfd6a47e55f.png)

**Comment by insthync** [comment]
Not sure is there any error occurring while using the API or not, please find it from `Data Explorer` → `Runtime` → `Script.log` 

![Screenshot_69](https://user-images.githubusercontent.com/2697550/77614526-c2437b00-6f5f-11ea-9155-5616d89a5e3c.png)

**Comment by DimasjkTV** [comment]
> Not sure is there any error occurring while using the API or not, please find it from


[script.log.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/4385483/script.log.zip)

**Comment by insthync** [comment]
Did you try create new account and login after export data from GameInstance → GSGameService?

**Comment by insthync** [comment]
Seems like I have to write codes which avoid null-cursor (It was never null), GameSpark's developer may changes something.

**Comment by DimasjkTV** [comment]
> Did you try create new account and login after export data from GameInstance → GSGameService?

Yes

**Comment by DimasjkTV** [comment]
I made a purchase of characters for 0 crystals. Bought 10. They were added to inventory. But after restarting the inventory was empty

**Comment by insthync** [comment]
Want to see the log after bought characters

**Comment by DimasjkTV** [comment]
> Want to see the log after bought characters

[script.log.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/4386979/script.log.zip)

**Comment by DimasjkTV** [comment]
![image](https://user-images.githubusercontent.com/47291794/77644901-dfce1000-6f72-11ea-9cb1-5765c18e3868.png)

**Comment by insthync** [comment]
[CloudCode-GS-TBRPG-master (4).zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/4387005/CloudCode-GS-TBRPG-master.4.zip)

Try the updated cloud codes

**Comment by DimasjkTV** [comment]
> [CloudCode-GS-TBRPG-master (4).zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/4387005/CloudCode-GS-TBRPG-master.4.zip)
> 
> Try the updated cloud codes

the same. I updated and copy game data code from my game data (export).

**Comment by DimasjkTV** [comment]
[script.log (1).zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/4387044/script.log.1.zip)

**Comment by insthync** [comment]
![Screenshot_70](https://user-images.githubusercontent.com/2697550/77647644-5e3da880-6f99-11ea-9668-469af3423e3a.png)

An Items are empty ?

**Comment by DimasjkTV** [comment]
no 
![image](https://user-images.githubusercontent.com/47291794/77647830-2f630a80-6f78-11ea-92af-52b337db3388.png)

**Comment by insthync** [comment]
Hmm, I currently don't know where the problem occurring :P

**Comment by DimasjkTV** [comment]
> Hmm, I currently don't know where the problem occurring :P

But specifically, I do not need gamesparks. I just decided to try testing it =)
but it would be nice if there was a connection with google сloud & icloud to save single player progress
