### ISSUE TITLE
Clan and Friend search problem.

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#50]
Clan and friend search function does not work.  I can't find the player or clan I'm looking for.

**Comment by insthync** [comment]
Try changes follow this comit 
https://github.com/insthync/rpg-php-service/commit/cd84303b61cc394ece4c5ad4ffbcb717dd352179

**Comment by dclgamingtr** [comment]
Yes, the problem is solved. Thank you.

**Comment by dclgamingtr** [comment]
It's ridiculous to add oneself in search. Can you hide yourself.

**Comment by insthync** [comment]
https://github.com/insthync/rpg-php-service/commit/e68b707934e8d0d7b1f0d53ed3e1a692f44f038d
Try this.
