### ISSUE TITLE
The problem of sending friend requests.

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#56]
![image](https://user-images.githubusercontent.com/61230304/78256134-d4de2700-7500-11ea-9b6f-e65b92e3bf0e.png)

friendship request is not sent when the game is over.
gives this error.

**Comment by insthync** [comment]
This is not occurring when I test it, it seems like it was fixed ?

**Comment by dclgamingtr** [comment]
your last update also has this problem. I have tried many times.

**Comment by insthync** [comment]
The error said like you're accessing character's selected skill when request dialog showing up, did you use `UICharacterActionAttack` or `UICharacterActionSkill` for request dialog?
