### ISSUE TITLE
1.12 BUG Acc/Eva/Defense/Attack formulas

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/turnbase-rpg-docs#58]
* Evasion formula does not work correctly. When I increase the accuracy of my character, the enemy often hits me.
* When character acc = 1, then monster miss all time. When character acc = 100, then monster hit all time.
* Monster Accuracy = Character Accuracy.

[Acc & Eva Bug 1.12.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/4423606/Acc.Eva.Bug.1.12.zip)

It seems that the problem is in all damage calculations. Character bonuses do not affect the character itself. These bonuses apply to enemies.

In the video below, my character has 100 damage. The enemy does 54 damage to me. I change damage of my character to 200 damage. The enemy began to inflict 161 damage on me. But I changed damage on my character, not the enemy.
[Defense & Attack Bug 1.12.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/4427852/Defense.Attack.Bug.1.12.zip)

* According to my tests, I found out that in battle the character uses the characteristics of the enemy, and the enemy uses the characteristics of the character

**Comment by insthync** [comment]
Fixed, update soon.

**Comment by insthync** [comment]
Fixed in 1.12c
