### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#6]
Hi, buy your battle game in turns and get it to work online with Spark, thank you very much but now my problem is that when I level up a character does not work, thank you very much

**Comment by insthync** [comment]
Is there any error in console, not work in Editor right ?

**Comment by surycr** [comment]
i was build my proyect  and i cant lvl up my items, error data token invalid plz if u can help i love u template

**Comment by surycr** [comment]
I dont know if my problem is with GameSpark Sorrry, but now i can see my Stamine Time Recovery and whne sell Item dont get Gold or when win stage

**Comment by insthync** [comment]
When you test in Editor it's working well ?

**Comment by insthync** [comment]
Please send me an error logs, I can't help you if I don't know what happened exactly

**Comment by surycr** [comment]
OnGameServiceError: ERROR_INVALID_PLAYER_ITEM_DATA

UnityEngine.Debug:LogError(Object)
GameInstance:OnGameServiceError(String, UnityAction) (at Assets/RPGGame/Core/Scripts/Game/GameInstance.cs:99)
GameInstance:OnGameServiceError(String) (at Assets/RPGGame/Core/Scripts/Game/GameInstance.cs:107)
UIItemLevelUp:OnLevelUpFail(String) (at Assets/RPGGame/Core/Scripts/UI/InventoryManagement/UIItemLevelUp.cs:143)
BaseGameService:HandleResult(ItemResult, UnityAction`1, UnityAction`1) (at Assets/RPGGame/Core/Scripts/GameService/BaseGameService.cs:81)
<LevelUpItem>c__AnonStorey6:<>m__0(ItemResult) (at Assets/RPGGame/Core/Scripts/GameService/BaseGameService.cs:185)
<DoLevelUpItem>c__AnonStorey16:<>m__0(LogEventResponse) (at Assets/GamesparksIntegration/Scripts/GSGameServiceItem.cs:49)
GameSparks.Core.<>c__DisplayClass1:<Send>b__0(GSObject) (at c:/jenkins/workspace/clientsdk-dotnet-rt-tls/GameSparks.Api/Core/GSTypedRequest.cs:118)
GameSparks.Core.<>c__DisplayClass4:<Complete>b__1() (at c:/jenkins/workspace/clientsdk-

**Comment by surycr** [comment]
working well if i dont use Game Spark and i dont understand with my gold dont change

**Comment by insthync** [comment]
Did you export game database 
![Screenshot_184](https://user-images.githubusercontent.com/2697550/69428668-645e1700-0d64-11ea-93b4-c80b5c8d5013.png)

To Cloud code → GAME_DATA ?
![Screenshot_185](https://user-images.githubusercontent.com/2697550/69428764-9a9b9680-0d64-11ea-8d22-afff9b59e494.png)

**Comment by surycr** [comment]
yes i was

**Comment by insthync** [comment]
Did you add game data yet ?
![Screenshot_186](https://user-images.githubusercontent.com/2697550/69473893-358b8380-0dec-11ea-88d0-1321ab7e62f6.png)

**Comment by surycr** [comment]
![bet](https://user-images.githubusercontent.com/43394702/69474365-f0cd0180-0d85-11ea-9466-9065dc384bd7.png)

**Comment by surycr** [comment]
![aa](https://user-images.githubusercontent.com/43394702/69474384-3b4e7e00-0d86-11ea-8b43-b96f3c405d2b.png)

**Comment by insthync** [comment]
After you have made changes on database (add/remove/update some items/stages/lootboxes and so on) you have to export game data again, not sure that you already did it ?. If you changes file name for example item file name, it can cause INVALID_DATA error because it cannot find item from database. So you have to create new account to test it. If item file name changes or it was removed from game database

**Comment by surycr** [comment]
Yea I know I change my data base all times and just have that problem I
understand

**Comment by surycr** [comment]
![aa](https://user-images.githubusercontent.com/43394702/69475452-ed8c4280-0d92-11ea-9a8f-dbed66c5f630.png)

Every time I make a change I extract the data and change it on the page, I understood that, but I tried it with a project only importing the one that I bought you and the same gave me the error without changing anything

**Comment by insthync** [comment]
Did you try to create new account and test it yet?

**Comment by insthync** [comment]
Now you can do everything except level up your character?

**Comment by surycr** [comment]
yes i try with another account and one friend too just have that problem i can send u my apk if u want see

**Comment by insthync** [comment]
Yes, post the APK link here, please.

**Comment by insthync** [comment]
And it would be better if you send me exported GAME_DATA.js too

**Comment by surycr** [comment]
https://drive.google.com/open?id=1M-jCELYhn705AoUMkZVzQ30ZgbYU3xvC

**Comment by surycr** [comment]
[DATA.txt](https://github.com/suriyun-production/turnbase-rpg-docs/files/3883225/DATA.txt)

**Comment by surycr** [comment]
https://drive.google.com/open?id=1M-jCELYhn705AoUMkZVzQ30ZgbYU3xvC

**Comment by insthync** [comment]
As I see your configs are correct, I want to test/debug it with your backend environment please add me as `Collaborator` by

Create group in dashboard
![Screenshot_190](https://user-images.githubusercontent.com/2697550/69495824-e2095a80-0efd-11ea-8997-5df719aec2d3.png)

Then set permission like this
![Screenshot_189](https://user-images.githubusercontent.com/2697550/69495829-ec2b5900-0efd-11ea-909d-3b428d713734.png)

And add me as `Collaborator` with email `ittipon.bay@gmail.com`
![Screenshot_191](https://user-images.githubusercontent.com/2697550/69495835-ffd6bf80-0efd-11ea-94c1-ddc343103456.png)

**Comment by surycr** [comment]
![aa](https://user-images.githubusercontent.com/43394702/69512115-6cef5280-0f08-11ea-8752-e59767f703b0.png)

**Comment by insthync** [comment]
Okay, now checking it

**Comment by insthync** [comment]
Ahhhh, I found the cause of issues.

The index name is invalid there is a space before the name

![Screenshot_194](https://user-images.githubusercontent.com/2697550/69522904-23991480-0f95-11ea-932c-ea1c0f0d7969.png)

**Comment by insthync** [comment]
I fix an invalid path, try it.

**Comment by surycr** [comment]
thank you very much if it already works ..
Now with this I am ready now I will see how the animation control is used that I still do not understand very well but thank you very much

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/69788202-9c5dc380-1183-11ea-83a9-a5678ac937e5.png)

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/69788249-ba2b2880-1183-11ea-925d-ff8d9fcbcd76.png)

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/69788326-de870500-1183-11ea-9512-589b5ca92efe.png)

**Comment by surycr** [comment]
Sorry me Again i dont know why i change icons in Database but i have a problem i dont know why in stage the icon is the same like arena and when win a stage dont get win u.u i am newbie sorry

**Comment by insthync** [comment]
Which Icon ?

**Comment by surycr** [comment]
Now when I look for stage, the icon that appears is the same one I have in the sand, I already changed the database, I updated it but it didn't change in the manage screen.

**Comment by surycr** [comment]
i have problem with icon stamina i dont know why

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/69833569-52fc8b00-11fa-11ea-9d4f-ab3b93d4b827.png)

**Comment by insthync** [comment]
Want to try your APK

**Comment by surycr** [comment]
i will

**Comment by surycr** [comment]
i cant fix  that icon

**Comment by surycr** [comment]
i fix the problem i was import the scene again just change again sorry

**Comment by surycr** [comment]
but i dont know how use the animacion i will see videos
