### ISSUE TITLE
I forgot my password ? There is a problem.

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#61]
If you log into Google play. it will be much better with password. There is no possibility to change the password. It disappears when you forget your password. This is a big problem. It will be better to log in via google play. I can't do anything because it is a salty panel. This problem is much more important than anything. Please I cannot publish my game because of this problem.

Best regards.

**Comment by insthync** [comment]
You use PHP web-service, right?

**Comment by dclgamingtr** [comment]
yes i am using php system.

**Comment by insthync** [comment]
What's the method you are going to use to recover the password?

**Comment by dclgamingtr** [comment]
E-mail address can be used. Forgotten password needs to be changed somehow via php panel. Or by typing an email address in the game, send a password change request.

**Comment by dclgamingtr** [comment]
Can you link it to  Google account. Therefore, they will not have problems such as entering a password or forgetting usernames.

**Comment by insthync** [comment]
Okay, I will add google play login and facebook login to PHP -service

**Comment by dclgamingtr** [comment]
thank you so much.

**Comment by insthync** [comment]
I've created an facebook login, google play login extensions

**Backend side**
* https://github.com/insthync/rpg-php-service-facebook-login
* https://github.com/insthync/rpg-php-service-google-play-login

**Frontend side**
* https://github.com/insthync/unity-tbrpg-google-play-login
* https://github.com/insthync/unity-tbrpg-facebook-login

You also have to update rpg-php-service to make extension system working.
