### ISSUE TITLE
Clan development.

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#65]
Can you make a daily boss for the clan. Can you add a level system to the clan.
Can you add a power of strength like each character's level. So we can rank power.

Let each character give different numbers in the range we set.
Thus, we can reflect this as power. The clan develops as the sum of this.

**Comment by surycr** [comment]
Yes i like all that he can i buy another pack good dev haha

**Comment by bma42** [comment]
It's true that the clan system is a bit empty right now, I imagine it will evolve!
