### ISSUE TITLE
Systems Needed

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#66]
1. Account Level

2. Account profile 

3. Overall Power System [Br, cp, etc]

4. Overall Ranking ex[ Power, level,  amount of stages cleared, guild level and power, amount of characters owned, world boss damage, Endless tower ]

5. Clan systems [ Clan level, Daily clan rewards for signing in, Member donations/contributions towards clan level up, Clan skills, Clan missions, Clan war, Clan boss ]

6. Missions [ main missions, daily missions, weekly missions bounty missions, etc ]

7. World boss [ timed boss, special boss event boss with damage ranking and rewards and each time players kill the boss it health double the next time it spawns ]

8. Crafting [ crafting items, gear, etc ]

9. Endless Tower [ fight monsters and climb up a tower with every 10 levels you fight a boss and ever Lvl of the tower increases in difficulty  so  does the rewards for clearing it

10. Sockets or gems

11, Daily/ Weekly events [ Setup event that starts at a specific time or specific day of the week ]

12. support for 2d sprites

13. battle pass and VIP systems

14. Vip system that gives you benefits to 3x speed play or battle skip, more stamina, arena fights, etc

15.Video, image or image dialog story Animation  before during or after stage clear

16. Energy system during the battle to cast skills with certain skills having specific  energy required to cast specific skill

17. Character combo system [https://www.youtube.com/watch?v=-7VesVKqXJQ](url)

18. Character costumes change how the player looks but keep stats and everything else 

 19 Stage difficulty  Easy, hard etc

20. Locking stage/chapter base on account level

 21.gobal chat, whisper, guild, party, etc

22. IAP store

23. Character Bond [ give extra stats base on which characters you have in your formation that share  a link or bond it could be 2 characters 3 or more

24. Option to start the game with a battle before selecting your name

25. Option to use 2d art instead of showing the 3d model

26. Character fragments instead of full character you collect fragments get enough to turn it into a character

27. Stage chapters setting stages under chapter

28. chapter/stages clear have the option to give rewards after a clear set number of stages after completing the star requirement ex stars https://imgur.com/5fGLsWS

29. Stage raid/blitz option to raid the already cleared stage for resources x1 or x10 times

this is some of the systems I would like to see implemented into the assets
and thank you for your hard work, looking forward to the progress and success of this asset

**Systems Implemented from the list** 

21.gobal chat, whisper, guild, party, etc
8. Crafting [ crafting items, gear, etc ]
3.Overall Power System [Br, cp, etc]
11, Daily/ Weekly events [ Setup event that starts at a specific time or specific day of the week ]

**Comment by surycr** [comment]
Like

**Comment by Ragingsura** [comment]
**Character Bond** [ give extra stats base on which characters you have in your formation that share a link or bond it could be 2 characters 3 or more

Option to start the game with a battle before selecting your name

Option to use 2d art instead of showing the 3d model

Character fragments instead of full character you collect fragments get enough to turn it into a character 

Stage chapters setting stages under chapter

chapter/stages clear     have the option to give rewards after a clear set number of stages after completing the star requirement ex stars [https://imgur.com/5fGLsWS](url) 


Stage raid/blitz option to raid the already cleared stage for resources  x1 or x10 times

**Comment by insthync** [comment]
Don't you think your requests are too much? :P

**Comment by Ragingsura** [comment]
> Don't you think your requests are too much? :P

bit much yes,  But these are systems that this asset needs to implement, so I'm just giving an idea base on what not only I personally need for my project but what I think others later down the line will most likely ask for

**Comment by insthync** [comment]
I will gradually add it :P

**Comment by dclgamingtr** [comment]
yes everything is needed here. The game is very empty in this state. No chat in an online game.

**Comment by Giftid01** [comment]
Great ideas, That would add a lot of spectacular content to the game
