### ISSUE TITLE
Are there any update feature for this asset in the future?

### ISSUE THREAD

**Issue by supergamereco** [suriyun-production/turnbase-rpg-docs#67]
Are there any update feature for this asset in the future?
It's ok if the update will take sometime but at least please confirm that there are any update in progress.
Thanks for great asset.

**Comment by insthync** [comment]
Yes, I've adding chat and crafting system.

**Comment by supergamereco** [comment]
Thanks for answering me, I have found some problems please help.
I can't create the ScriptableObject.
I've attached the picture in the link below.
![Annotation 2020-07-10 143307](https://user-images.githubusercontent.com/15682380/87128727-512f9580-c2ba-11ea-9b65-b856e717cd63.jpg)

**Comment by supergamereco** [comment]
I've found another bug.
Stamina is not update if we want to enter the adventure mode we have to restart the game.
Stamina UI updated was fine but it seem stamina variable is not update.
![Annotation 2020-07-10 174257](https://user-images.githubusercontent.com/15682380/87146224-d3c54e80-c2d4-11ea-8ed0-786892e74e88.jpg)
