### ISSUE TITLE
Can't create the ScriptableObject & Stamina is not update.

### ISSUE THREAD

**Issue by supergamereco** [suriyun-production/turnbase-rpg-docs#68]
I can't create the ScriptableObject. I've try many of Unity versions and it doesn't help.
I've followed your guide to change .NET version already and it doesn't help too.
![87128727-512f9580-c2ba-11ea-9b65-b856e717cd63](https://user-images.githubusercontent.com/15682380/87275941-6ea66e80-c509-11ea-8dbb-9c49eda37e04.jpg)
Stamina is not update if we want to enter the adventure mode we have to restart the game.
Stamina UI updated was fine but it seem stamina variable is not update.
![87146224-d3c54e80-c2d4-11ea-8ed0-786892e74e88](https://user-images.githubusercontent.com/15682380/87276173-fb512c80-c509-11ea-9e6b-860f2be57b9d.jpg)
Please fix them thank you.

**Comment by insthync** [comment]
Not sure there is a ScriptableObject (TurnbaseRPG ) menu or not?
![Screenshot_244](https://user-images.githubusercontent.com/2697550/87295914-251d4a00-c530-11ea-9caf-3359472a9d7b.png)
