### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#69]
Hello!
An error occurs, PHP Web-service integration:

[POST->Error]/validate-login-token HTTP/1.1 500 Internal Server Error <!DOCTYPE html>
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<h1>Internal Server Error</h1>
<p>Wrong number of segments [D:\Server\OSPanel\domains\localhost\rpg-php-service-master\jwt\JWT.php:78]</p>
<pre>[D:/Server/OSPanel/domains/localhost/rpg-php-service-master/functions/Helpers.php:11] Firebase\JWT\JWT::decode('5b792df0-d49f-4076-b598-f22c5ec172bb','jwtSecret1234',['HS256'])
[D:/Server/OSPanel/domains/localhost/rpg-php-service-master/functions/Helpers.php:105] DecodeJwt('5b792df0-d49f-4076-b598-f22c5ec172bb')
[D:/Server/OSPanel/domains/localhost/rpg-php-service-master/functions/Auth.php:73] GetPlayer()
[D:/Server/OSPanel/domains/localhost/rpg-php-service-master/index.php:73] ValidateLoginToken(true)
[D:/Server/OSPanel/domains/localhost/rpg-php-service-master/fatfree/lib/base.php:1873] {closure}(Base::__set_state(['hive'=>['HEADERS'=>['Host'=>'localhost','User-Agent'=>'UnityPlayer/2018.4.24f1 (UnityWebRequest/1.0, libcurl/7.52.0-DEV)','Accept-Encoding'=>'identity','Authorization'=>'Bearer 5b792df0-d49f-4076-b598-f22c5ec172bb','Accept'=>'application/json','Content-Type'=>'application/json','X-Unity-Version'=>'2018.4.24f1','Content-Length'=>'31'],'AGENT'=>'UnityPlayer/2018.4.24f1 (UnityWebRequest/1.0, libcurl/7.52.0-DEV)','AJAX'=>false,'ALIAS'=>NULL,'ALIASES'=>[],'AUTOLOAD'=>'databases/|enums/','BASE'=>'/rpg-php-service-master','BITMASK'=>2,'BODY'=>'%7b%22refreshToken%22%3atrue%7d','CACHE'=>false,'CASELESS'=>true,'CLI'=>false,'CORS'=>['headers'=>'','origin'=>false,'credentials'=>false,'expose'=>false,'ttl'=>0],'DEBUG'=>3,'DIACRITICS'=>[],'DNSBL'=>'','EMOJI'=>[],'ENCODING'=>'UTF-8','ERROR'=>NULL,'ESCAPE'=>true,'EXCEPTION'=>UnexpectedValueException::__set_state([]),'EXEMPT'=>NULL,'FALLBACK'=>'en','FORMATS'=>[],'FRAGMENT'=>'','HALT'=>true,'HIGHLIGHT'=>false,'HOST'=>'localhost','IP'=>'127.0.0.1','JAR'=>['expire'=>0,'lifetime'=>0,'path'=>'/rpg-php-service-master','domain'=>'','secure'=>false,'httponly'=>true],'LANGUAGE'=>'en','LOCALES'=>'./','LOGGABLE'=>'*','LOGS'=>'./','MB'=>true,'ONERROR'=>NULL,'ONREROUTE'=>NULL,'PACKAGE'=>'Fat-Free Framework','PARAMS'=>['/validate-login-token'],'PATH'=>'/validate-login-token','PATTERN'=>'/validate-login-token','PLUGINS'=>'D:/Server/OSPanel/domains/localhost/rpg-php-service-master/fatfree/lib/','PORT'=>'80','PREFIX'=>NULL,'PREMAP'=>'','QUERY'=>'','QUIET'=>false,'RAW'=>false,'REALM'=>'http://localhost/rpg-php-service-master/validate-login-token','RESPONSE'=>'','ROOT'=>'D:\Server\OSPanel\domains\localhost','ROUTES'=>['/validate-login-token'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/unlock-items'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/unequip-item'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/start-stage'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/start-duel'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/staminas'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/set-profile-name'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/set-formation'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/service-time'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/sell-items'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/select-formation'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/revive-characters'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/register'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/pending-requests'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/opponents'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/open-lootbox'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/open-ingame-package'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/login'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/levelup-item'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/items'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/ios-buy-goods'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/helpers'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/guest-login'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/google-play-buy-goods'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/friends'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/friend-requests'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/friend-request-delete'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/friend-request'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/friend-delete'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/friend-decline'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/friend-accept'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/formations'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/finish-stage'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/finish-duel'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/find-player'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/find-clan'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/evolve-item'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/equip-item'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/earn-achievement-reward'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/currencies'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/create-clan'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/convert-hard-currency'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clear-stages'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/clan-terminate'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clan-set-role'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clan-owner-transfer'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clan-members'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clan-member-delete'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clan-join-requests'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clan-join-request-delete'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clan-join-request'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clan-join-pending-requests'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clan-join-decline'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clan-join-accept'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clan-exit'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/clan'=>[['POST'=>[Closure::__set_state([]),0,0,NULL]]],'/available-lootboxes'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/available-ingame-packages'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/available-iap-packages'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/achievements'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]],'/'=>[['GET'=>[Closure::__set_state([]),0,0,NULL]]]],'SCHEME'=>'http','SEED'=>'3dsn2jqyjeckc','SERIALIZER'=>'igbinary','TEMP'=>'tmp/','TIME'=>1595025268.105,'TZ'=>'Europe/Moscow','UI'=>'./','UNLOAD'=>NULL,'UPLOADS'=>'./','URI'=>'/rpg-php-service-master/validate-login-token','VERB'=>'POST','VERSION'=>'3.6.5-Release','XFRAME'=>'SAMEORIGIN','GET'=>[],'POST'=>[],'COOKIE'=>[],'REQUEST'=>[],'SESSION'=>NULL,'FILES'=>[],'SERVER'=>['REDIRECT_HTTP_AUTHORIZATION'=>'Bearer 5b792df0-d49f-4076-b598-f22c5ec172bb','REDIRECT_STATUS'=>'200','HTTP_AUTHORIZATION'=>'Bearer 5b792df0-d49f-4076-b598-f22c5ec172bb','HTTP_HOST'=>'localhost','HTTP_USER_AGENT'=>'UnityPlayer/2018.4.24f1 (UnityWebRequest/1.0, libcurl/7.52.0-DEV)','HTTP_ACCEPT_ENCODING'=>'identity','HTTP_ACCEPT'=>'application/json','CONTENT_TYPE'=>'application/json','HTTP_X_UNITY_VERSION'=>'2018.4.24f1','CONTENT_LENGTH'=>'31','PATH'=>'d:\server\ospanel\modules\php\PHP_7.2-x64\ext;d:\server\ospanel\modules\php\PHP_7.2-x64\pear;d:\server\ospanel\modules\php\PHP_7.2-x64\pear\bin;d:\server\ospanel\modules\php\PHP_7.2-x64;d:\server\ospanel\modules\imagemagick;d:\server\ospanel\modules\wget\bin;d:\server\ospanel\modules\database\MySQL-8.0-x64\bin;d:\server\ospanel\modules\http\Apache_2.4-PHP_7.2-7.3-x64\bin;d:\server\ospanel\modules\http\Apache_2.4-PHP_7.2-7.3-x64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\SysWOW64','SystemRoot'=>'C:\WINDOWS','COMSPEC'=>'C:\WINDOWS\system32\cmd.exe','PATHEXT'=>'.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC','WINDIR'=>'C:\WINDOWS','SERVER_SIGNATURE'=>'','SERVER_SOFTWARE'=>'Apache','SERVER_NAME'=>'localhost','SERVER_ADDR'=>'127.0.0.1','SERVER_PORT'=>'80','REMOTE_ADDR'=>'127.0.0.1','DOCUMENT_ROOT'=>'D:\Server\OSPanel\domains\localhost','REQUEST_SCHEME'=>'http','CONTEXT_PREFIX'=>'','CONTEXT_DOCUMENT_ROOT'=>'D:/Server/OSPanel/domains/localhost','SERVER_ADMIN'=>'[no address given]','SCRIPT_FILENAME'=>'D:/Server/OSPanel/domains/localhost/rpg-php-service-master/index.php','REMOTE_PORT'=>'6652','REDIRECT_URL'=>'/rpg-php-service-master/validate-login-token','GATEWAY_INTERFACE'=>'CGI/1.1','SERVER_PROTOCOL'=>'HTTP/1.1','REQUEST_METHOD'=>'POST','QUERY_STRING'=>'','REQUEST_URI'=>'/rpg-php-service-master/validate-login-token','SCRIPT_NAME'=>'/rpg-php-service-master/index.php','PHP_SELF'=>'/rpg-php-service-master/index.php','REQUEST_TIME_FLOAT'=>1595025268.105,'REQUEST_TIME'=>1595025268,'argv'=>[],'argc'=>0],'ENV'=>[],'db_prefix'=>'rpg_','db_host'=>'localhost','db_port'=>3306,'db_name'=>'rpg','db_user'=>'root','db_pass'=>8xxxxxx0,'db_freeze'=>false,'timezone'=>'Europe/Kiev','jwt_secret'=>'jwtSecret1234','password_salt'=>'lSALTlMUSTlATlLEASTl22','appstore_is_sandbox'=>true,'play_public_key'=>NULL,'GameData'=>['achievements'=>['2EvolveCharacters'=>['type'=>4,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'2EvolveEquipments'=>['type'=>5,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'2Helpers'=>['type'=>7,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'2Revives'=>['type'=>6,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'2UpgradeCharacters'=>['type'=>2,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'2UpgradeEquipments'=>['type'=>3,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'Clear2Stages'=>['type'=>0,'targetAmount'=>2,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'Clear5Stages'=>['type'=>0,'targetAmount'=>5,'rewardSoftCurrency'=>1000,'rewardHardCurrency'=>5,'rewardPlayerExp'=>100,'rewardItems'=>[]],'Clear10Stages'=>['type'=>0,'targetAmount'=>10,'rewardSoftCurrency'=>1000,'rewardHardCurrency'=>5,'rewardPlayerExp'=>100,'rewardItems'=>[['id'=>'RedMushroom','amount'=>1]]],'Collect6Stars'=>['type'=>1,'targetAmount'=>6,'rewardSoftCurrency'=>0,'rewardHardCurrency'=>5,'rewardPlayerExp'=>0,'rewardItems'=>[]],'Collect15Stars'=>['type'=>1,'targetAmount'=>15,'rewardSoftCurrency'=>1000,'rewardHardCurrency'=>5,'rewardPlayerExp'=>100,'rewardItems'=>[]],'Collect30Stars'=>['type'=>1,'targetAmount'=>30,'rewardSoftCurrency'=>1000,'rewardHardCurrency'=>5,'rewardPlayerExp'=>100,'rewardItems'=>[['id'=>'RedMushroom','amount'=>1]]]],'items'=>['BlackKnight'=>['id'=>'BlackKnight','category'=>'','itemTier'=>['id'=>'0-White','maxLevel'=>20,'expTable'=>['minValue'=>10,'maxValue'=>2206,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>2000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>1000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>1544,'growth'=>2.5],'evolvePrice'=>1000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>0,'fixSellPrice'=>0,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>0,'fixRewardExp'=>0,'evolveInfo'=>['requiredMaterials'=>[['id'=>'RedMushroom','amount'=>1]],'evolveItem'=>'BlackKnight 1'],'randomAttributes'=>['minType'=>0,'maxType'=>0,'minHp'=>0,'maxHp'=>0,'minPAtk'=>0,'maxPAtk'=>0,'minPDef'=>0,'maxPDef'=>0,'minMAtk'=>0,'maxMAtk'=>0,'minMDef'=>0,'maxMDef'=>0,'minSpd'=>0,'maxSpd'=>0,'minEva'=>0,'maxEva'=>0,'minAcc'=>0,'maxAcc'=>0,'minCritChance'=>0,'maxCritChance'=>0,'minCritDamageRate'=>0,'maxCritDamageRate'=>0,'minBlockChance'=>0,'maxBlockChance'=>0,'minBlockDamageRate'=>0,'maxBlockDamageRate'=>0,'minResistanceChance'=>0,'minBloodStealRateByPAtk'=>0,'maxBloodStealRateByPAtk'=>0,'minBloodStealRateByMAtk'=>0,'maxBloodStealRateByMAtk'=>0,'end'=>0]],'Shaman'=>['id'=>'Shaman','category'=>'','itemTier'=>['id'=>'0-White','maxLevel'=>20,'expTable'=>['minValue'=>10,'maxValue'=>2206,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>2000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>1000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>1544,'growth'=>2.5],'evolvePrice'=>1000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>0,'fixSellPrice'=>0,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>0,'fixRewardExp'=>0,'evolveInfo'=>['requiredMaterials'=>[['id'=>'RedMushroom','amount'=>1]],'evolveItem'=>'Shaman 1'],'randomAttributes'=>['minType'=>0,'maxType'=>0,'minHp'=>0,'maxHp'=>0,'minPAtk'=>0,'maxPAtk'=>0,'minPDef'=>0,'maxPDef'=>0,'minMAtk'=>0,'maxMAtk'=>0,'minMDef'=>0,'maxMDef'=>0,'minSpd'=>0,'maxSpd'=>0,'minEva'=>0,'maxEva'=>0,'minAcc'=>0,'maxAcc'=>0,'minCritChance'=>0,'maxCritChance'=>0,'minCritDamageRate'=>0,'maxCritDamageRate'=>0,'minBlockChance'=>0,'maxBlockChance'=>0,'minBlockDamageRate'=>0,'maxBlockDamageRate'=>0,'minResistanceChance'=>0,'minBloodStealRateByPAtk'=>0,'maxBloodStealRateByPAtk'=>0,'minBloodStealRateByMAtk'=>0,'maxBloodStealRateByMAtk'=>0,'end'=>0]],'Thief'=>['id'=>'Thief','category'=>'','itemTier'=>['id'=>'0-White','maxLevel'=>20,'expTable'=>['minValue'=>10,'maxValue'=>2206,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>2000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>1000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>1544,'growth'=>2.5],'evolvePrice'=>1000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>0,'fixSellPrice'=>0,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>0,'fixRewardExp'=>0,'evolveInfo'=>['requiredMaterials'=>[['id'=>'RedMushroom','amount'=>1]],'evolveItem'=>'Thief 1'],'randomAttributes'=>['minType'=>0,'maxType'=>0,'minHp'=>0,'maxHp'=>0,'minPAtk'=>0,'maxPAtk'=>0,'minPDef'=>0,'maxPDef'=>0,'minMAtk'=>0,'maxMAtk'=>0,'minMDef'=>0,'maxMDef'=>0,'minSpd'=>0,'maxSpd'=>0,'minEva'=>0,'maxEva'=>0,'minAcc'=>0,'maxAcc'=>0,'minCritChance'=>0,'maxCritChance'=>0,'minCritDamageRate'=>0,'maxCritDamageRate'=>0,'minBlockChance'=>0,'maxBlockChance'=>0,'minBlockDamageRate'=>0,'maxBlockDamageRate'=>0,'minResistanceChance'=>0,'minBloodStealRateByPAtk'=>0,'maxBloodStealRateByPAtk'=>0,'minBloodStealRateByMAtk'=>0,'maxBloodStealRateByMAtk'=>0,'end'=>0]],'RedMushroom'=>['id'=>'RedMushroom','category'=>'','itemTier'=>['id'=>'0-White','maxLevel'=>20,'expTable'=>['minValue'=>10,'maxValue'=>2206,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>2000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>1000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>1544,'growth'=>2.5],'evolvePrice'=>1000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'useFixSellPrice'=>1,'fixSellPrice'=>1000000,'useFixLevelUpPrice'=>0,'fixLevelUpPrice'=>0,'useFixRewardExp'=>1,'fixRewardExp'=>1000000,'evolveInfo'=>['requiredMaterials'=>[],'evolveItem'=>''],'randomAttributes'=>['minType'=>0,'maxType'=>0,'minHp'=>0,'maxHp'=>0,'minPAtk'=>0,'maxPAtk'=>0,'minPDef'=>0,'maxPDef'=>0,'minMAtk'=>0,'maxMAtk'=>0,'minMDef'=>0,'maxMDef'=>0,'minSpd'=>0,'maxSpd'=>0,'minEva'=>0,'maxEva'=>0,'minAcc'=>0,'maxAcc'=>0,'minCritChance'=>0,'maxCritChance'=>0,'minCritDamageRate'=>0,'maxCritDamageRate'=>0,'minBlockChance'=>0,'maxBlockChance'=>0,'minBlockDamageRate'=>0,'maxBlockDamageRate'=>0,'minResistanceChance'=>0,'minBloodStealRateByPAtk'=>0,'maxBloodStealRateByPAtk'=>0,'minBloodStealRateByMAtk'=>0,'maxBloodStealRateByMAtk'=>0,'end'=>0]],'BlackKnight 1'=>['id'=>'BlackKnight 1','category'=>'','itemTier'=>['id'=>'1-Green','maxLevel'=>40,'expTable'=>['minValue'=>10,'maxValue'=>6364,'growth'=>2.5],'sellPriceTable'=>['minValue'=>100,'maxValue'=>4000,'growth'=>1],'levelUpPriceTable'=>['minValue'=>50,'maxValue'=>2000,'growth'=>1],'rewardExpTable'=>['minValue'=>7,'maxValue'=>4455,'growth'=>2.5],'evolvePrice'=>5000,'sortWeight'=>0],'type'=>'CharacterItem','maxStack'=>1,'us<message truncated>

**Comment by brabaris** [comment]
Tried various bundles php + mysql, still an error ...

**Comment by insthync** [comment]
Can you re-login?, seems like the token generate by other service (maybe an offline server for test)

**Comment by brabaris** [comment]
This error appears immediately after clicking "Tap to start"... :(

**Comment by insthync** [comment]
Yes, then can you try to login ?

**Comment by brabaris** [comment]
![Error500](https://user-images.githubusercontent.com/16080577/87849906-eb17c380-c8f4-11ea-9b95-a0fd324439c1.jpg)
Your Asset just bought yesterday, hasn't changed anything except PHP Web-service integration ...

**Comment by brabaris** [comment]
![Error500_1](https://user-images.githubusercontent.com/16080577/87850014-9a549a80-c8f5-11ea-88e5-af8d858ba679.jpg)
I can't even register!

**Comment by insthync** [comment]
Okay, how about register error log?

**Comment by brabaris** [comment]
error log Apache?

**Comment by insthync** [comment]
![Screenshot_249](https://user-images.githubusercontent.com/2697550/87850093-a8b3ae00-c917-11ea-91f1-cfbfc7750d08.png)

Select this

**Comment by brabaris** [comment]
![Error500_2](https://user-images.githubusercontent.com/16080577/87850115-4c8c6200-c8f6-11ea-943d-d0162d06d239.jpg)

**Comment by insthync** [comment]
You know how to alter table's column or not?, seems like you use difference database system to me and it needed to changed some columns, if not I will make new patch for the php-service

**Comment by brabaris** [comment]
If necessary, I can provide phpinfo.
http://109.87.133.xx/rpg-php-service-master/phpinfo.php

**Comment by insthync** [comment]
I want to know which database are you using mysql or mariadb? and its version.

**Comment by brabaris** [comment]
MySQL 8.x.x

**Comment by brabaris** [comment]
MySQL 8.0 x64

**Comment by insthync** [comment]
Okay

**Comment by brabaris** [comment]
It seems to me that this is related to the php settings, or the htaccess file ...

**Comment by insthync** [comment]
Updated.

Unzip, set your config, then browse {path to service}/sql-importer.php?update=1.13b to update columns settings

**Comment by insthync** [comment]
Then try to register and login again.

**Comment by brabaris** [comment]
Ok, through 10 min...

**Comment by brabaris** [comment]
![Error500_3](https://user-images.githubusercontent.com/16080577/87851050-c3792900-c8fd-11ea-8ee7-fddfc9a38471.jpg)


Done :)

![Error500_4](https://user-images.githubusercontent.com/16080577/87850988-2fa75d00-c8fd-11ea-8290-98be37a17c2a.jpg)
After clicking "Tap to start", there was an error again, but I was able to register and enter the game ...

**Comment by insthync** [comment]
Yep, then next time when you "Tap to start" the error won't appear because the gererated access token  is correct.

**Comment by brabaris** [comment]
Many thanks! I have five stars in the Assetstore and a positive review. Good luck!

**Comment by insthync** [comment]
Thank you :)
