### ISSUE TITLE
How to add currency

### ISSUE THREAD

**Issue by Malvunction** [suriyun-production/turnbase-rpg-docs#7]
I have been wondering if I am able to add Hard currency as a 1 time reward for finishing a part of story, hopefully through a present box system, but as it is I do not know how to add characters or hard currency directly.

**Comment by insthync** [comment]
It is first time reward when finish stage right?, seems like I have to add some codes to support it, I will check.

**Comment by Malvunction** [comment]
Thank you so much!

**Comment by insthync** [comment]
Added to version 1.10, which uploaded to asset store.

**Comment by surycr** [comment]
if i update u game how change my gamespark

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/70942184-b74d8600-2013-11ea-9195-f886df179c0e.png)

**Comment by surycr** [comment]
i cant fix u.u

**Comment by surycr** [comment]
![image](https://user-images.githubusercontent.com/43394702/70971280-39ff3100-2066-11ea-9861-e3a59dbc2088.png)

**Comment by insthync** [comment]
Import the latest version from https://github.com/insthync/gamesparks-tbrpg-addons/releases to Unity project

And also import https://github.com/insthync/CloudCode-GS-TBRPG/releases to Gamespark cloud codes

Then export game data to game spark.

**Comment by surycr** [comment]
thanks so much
