### ISSUE TITLE
Clan creation error

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#70]
Hello! Found a new error when creating a clan. The clan does not create two errors. But the money is debited ...
![Create_Clan_Error](https://user-images.githubusercontent.com/16080577/87859303-d52df100-c93c-11ea-9bcf-07fba44ad1a7.jpg)

**Comment by brabaris** [comment]
This error appears even if you fill in the clan name field ... The clan is not created, but the money is debited.
Need to change `description` :
CREATE TABLE `<<__prefix__>>clan` (
  `id` bigint(20) NOT NULL,
  `name` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `description` text CHARACTER SET utf8 COLLATE utf8_unicode_ci, -- Edit!
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by brabaris** [comment]
This error appears even if you fill in the description... The clan is not created, but the money is debited.

**Comment by insthync** [comment]
I will upload new patch

**Comment by brabaris** [comment]
ok!

**Comment by brabaris** [comment]
I had another error on Unix hosting. In the index.php file you need to change $it = new RecursiveDirectoryIterator("./extensions");

**Comment by brabaris** [comment]
And you need to prohibit the creation of a clan without a name ...

**Comment by insthync** [comment]
Okay, I will fix it.

**Comment by brabaris** [comment]
Thank you! When to wait for the next update?

**Comment by insthync** [comment]
Updated (1.13c)

Browse sql-importer.php?update=1.13c to update database schema.

**Comment by brabaris** [comment]
ok! In the morning I'll try, I'm already going to bed (I have 01:14).
