### ISSUE TITLE
No new character added

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#72]
Hello! No new character is added. Although it is visible in CODEX ...
![1](https://user-images.githubusercontent.com/16080577/88479134-ad9ae200-cf55-11ea-9a24-2b2bab7687c9.jpg)
![2](https://user-images.githubusercontent.com/16080577/88479136-affd3c00-cf55-11ea-9110-b588538e364b.jpg)
![3](https://user-images.githubusercontent.com/16080577/88479139-b1c6ff80-cf55-11ea-8f54-0e10b975631e.jpg)
![4](https://user-images.githubusercontent.com/16080577/88479141-b2f82c80-cf55-11ea-9ad1-5a04b4fd75bc.jpg)
![5](https://user-images.githubusercontent.com/16080577/88479143-b390c300-cf55-11ea-8669-38aa55b70914.jpg)
![6](https://user-images.githubusercontent.com/16080577/88479145-b55a8680-cf55-11ea-872e-14b8967802b3.jpg)

**Comment by brabaris** [comment]
This problem is seen only when working with PHP Web-service in regular LoginScene.unity everything works ... :(
![LoginScene_without_php](https://user-images.githubusercontent.com/16080577/88485032-a8508e00-cf7b-11ea-8386-e9150996b480.jpg)

**Comment by brabaris** [comment]
I tried various options. New characters are not added to the game! The error is related to MySQL and WebServiceClient.cs

**Comment by insthync** [comment]
Did you export game data to place it on web-service's root folder ?

![Screenshot_258](https://user-images.githubusercontent.com/2697550/88586630-d8cd2080-d07e-11ea-9fa3-7d0a524d40a8.png)

![Screenshot_259](https://user-images.githubusercontent.com/2697550/88586716-f8644900-d07e-11ea-8be6-2e1f46226085.png)

**Comment by brabaris** [comment]
Many thanks! Everything works now. I didn't know about exporting GameData.json
