### ISSUE TITLE
Cyrillic does not work in chat!

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#74]
Hello! Cyrillic does not work in chat. I attach the screenshots.
![1](https://user-images.githubusercontent.com/16080577/89270780-81155300-d644-11ea-8192-5e0d73cedb75.jpg)
![2](https://user-images.githubusercontent.com/16080577/89270789-84104380-d644-11ea-9d6d-b4cd48cb4f98.jpg)

**Comment by insthync** [comment]
You may use PhpMyAdmin or HeidiSQL to change table `chat` → column `message` → collation to `cp1251_general_ci`

**Comment by brabaris** [comment]
Everything is working. Thank you!
