### ISSUE TITLE
Found 2 bugs.

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#75]
Found 2 bugs. The first mistake: The arena reward does not work. Second bug: Buttons in UILoseGame do not work.
Screenshots are attached.
![1](https://user-images.githubusercontent.com/16080577/90158042-2774fd00-dd97-11ea-925b-25132097a6e5.jpg)
![2](https://user-images.githubusercontent.com/16080577/90158048-293ec080-dd97-11ea-8f63-2d7bc3b58d4c.jpg)
![3](https://user-images.githubusercontent.com/16080577/90158055-29d75700-dd97-11ea-9d5a-21335616c816.jpg)
Need to connect buttons ...
![4](https://user-images.githubusercontent.com/16080577/90158059-2b088400-dd97-11ea-89bf-d469ece6677d.jpg)

**Comment by insthync** [comment]
About arena reward, did you export game data to the service before test?

**Comment by insthync** [comment]
Thank you to inform about button events, there also have an missing events in pause dialog (for the demo find `UIMenu`), there are functions in `UIPauseGame` component that you have to set to buttons (`OnClickContinue`, `OnClickRestart`, `OnClickGiveUp`)

**Comment by insthync** [comment]
Oh, you don't have to set events to `UIWin`, `UILose`, `UIPauseMenu` if you are already set buttons to the button fields

**Comment by brabaris** [comment]
After the changes in arena rewards, I was exporting GameData.json to the server. I fixed the buttons a long time ago, and you can see it in the last screenshot. I said that you would fix it in asset version 1.13+ for new buyers ...
