### ISSUE TITLE
Webservices Not work

### ISSUE THREAD

**Issue by FleksisLV** [suriyun-production/turnbase-rpg-docs#77]
Hello, webservice is not working, i tryed all difrent xampp version with difrent php versions, in most of them i by folowing the tutorial everything is okey but as soon as try log true client i got error like this :

`[POST->Error]/guest-login HTTP/1.1 404 Not Found <!DOCTYPE html>
<html>
<head><title>404 Not Found</title></head>
<body>
<h1>Not Found</h1>
<p>HTTP 404 (POST //guest-login)</p>
<pre>[C:/xampp/htdocs/rpg-php-service-master/fatfree/lib/base.php:1787] Base->error()
[C:/xampp/htdocs/rpg-php-service-master/index.php:301] Base->run()
</pre>
</body>
</html>
UnityEngine.Debug:LogError(Object)
<PostRoutine>d__9:MoveNext() (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:143)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
`
`[POST->Error]/validate-login-token HTTP/1.1 404 Not Found <!DOCTYPE html>
<html>
<head><title>404 Not Found</title></head>
<body>
<h1>Not Found</h1>
<p>HTTP 404 (POST //validate-login-token)</p>
<pre>[C:/xampp/htdocs/rpg-php-service-master/fatfree/lib/base.php:1787] Base->error()
[C:/xampp/htdocs/rpg-php-service-master/index.php:301] Base->run()
</pre>
</body>
</html>
UnityEngine.Debug:LogError(Object)
<PostRoutine>d__9:MoveNext() (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:143)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
`
`OnGameServiceError: ERROR_UNKNOW
UnityEngine.Debug:LogError(Object)
GameInstance:OnGameServiceError(String, UnityAction) (at Assets/RPGGame/Core/Scripts/Game/GameInstance.cs:102)
GameInstance:OnGameServiceError(String) (at Assets/RPGGame/Core/Scripts/Game/GameInstance.cs:110)
UIAuthentication:OnError(String) (at Assets/RPGGame/Core/Scripts/UI/Player/UIAuthentication.cs:74)
BaseGameService:HandleResult(PlayerResult, UnityAction`1, UnityAction`1) (at Assets/RPGGame/Core/Scripts/GameService/BaseGameService.cs:83)
<>c__DisplayClass25_0:<GuestLogin>b__0(PlayerResult) (at Assets/RPGGame/Core/Scripts/GameService/BaseGameService.cs:139)
<>c__DisplayClass21_0:<DoGuestLogin>b__0(UnityWebRequest, PlayerResult) (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:254)
<>c__DisplayClass8_0`1:<PostAsDecodedJSON>b__0(UnityWebRequest) (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:113)
<PostRoutine>d__9:MoveNext() (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:149)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
`

`[GET->Error]/service-time HTTP/1.1 404 Not Found <!DOCTYPE html>
<html>
<head><title>404 Not Found</title></head>
<body>
<h1>Not Found</h1>
<p>HTTP 404 (GET //service-time)</p>
<pre>[C:/xampp/htdocs/rpg-php-service-master/fatfree/lib/base.php:1787] Base->error()
[C:/xampp/htdocs/rpg-php-service-master/index.php:301] Base->run()
</pre>
</body>
</html>
UnityEngine.Debug:LogError(Object)
<GetRoutine>d__6:MoveNext() (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:87)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
`

**Comment by insthync** [comment]
What is current Apache and PHP version?

**Comment by FleksisLV** [comment]
i tryed, from php 5 to 7.2, appache from 2.0 - 2.4.

**Comment by insthync** [comment]
It might be .htaccess problem, which xampp version are you using, I will try it.

**Comment by FleksisLV** [comment]
https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/7.2.0/

**Comment by FleksisLV** [comment]
More better would be if it works on newest version of xampp, because of security.

**Comment by FleksisLV** [comment]
i fixed need add in fattfree httacess 
RewriteBase /fatfree/

**Comment by FleksisLV** [comment]
and it works
