### ISSUE TITLE
hi how can make sumon skill

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#8]
hi all good with u template just one a question, can i make a sumon or pet, example i want a skill for necromancer summon criatures? can i do that?

**Comment by insthync** [comment]
I have to add new codes for that :P, now I am thinking about where they should be spawned.

**Comment by surycr** [comment]
ooo cool u so pro thanx

**Comment by surycr** [comment]
i think make another slot floor body and summon and make a cointer front de character
