### ISSUE TITLE
Arena rewards don't work!

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#80]
Arena rewards don't work! I rechecked everything, overwritten the GameData.json file on the server
Here is a piece of code from the file:
"arenaRanks":[{"id":"001_Bronze","scoreToRankUp":100,"rewardSoftCurrency":100,"rewardHardCurrency":20,"rewardItems":[]},{"id":"002_Silver","scoreToRankUp":200,"rewardSoftCurrency":200,"rewardHardCurrency":25,"rewardItems":[]},{"id":"003_Gold","scoreToRankUp":300,"rewardSoftCurrency":300,"rewardHardCurrency":30,"rewardItems":[]},{"id":"004_Platinum","scoreToRankUp":400,"rewardSoftCurrency":400,"rewardHardCurrency":35,"rewardItems":[]},

**Comment by insthync** [comment]
Fixed, try update latest rpg-php-service

**Comment by brabaris** [comment]
Good job! Thanks for you!

**Comment by brabaris** [comment]
Good job! Thanks for you!
