### ISSUE TITLE
Turn-base More Upadate

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#81]
It would bee nice if this assets get a frequent update like the MMORPG kit. MMO kit get 1-2 update per month while turn base gets 1 every 6 months or more

**Comment by insthync** [comment]
Choose one feature that you really want it, then tell me how it work, now there are many requests that I can't prioritize :P

**Comment by Ragingsura** [comment]
thank you and I would like to say I fully understand that it takes time to code and implement features but sadly 1 feature add will not let me finish the game I'm fully ready to make and I've already made a list of features I would like to see but I will just give you the most important ones

**Comment by Ragingsura** [comment]
1. Account profile

currently, the player account has no profile 1 is need for basic account information, settings, and few extra settings.
[https://imgur.com/Ra12YOm](url)
[https://imgur.com/hjdizV7](url)

2 Level Usefulness

Currently levels servers no purpose other than just leveling up.  I would like the ability to use the account level to lock/hide/Restrict content until the player reaches a set level such as ( Story, chapter, Arena, Dungeon, Equipment Crafting Etc)
i would also love to use the account level to limit the max upgrade for character gear base on the account level.

3 Timed Events/ daily

to be able to create events/battles that happen at a specific time of the day and how long set event last for until it's closed for the day until the server reset or day reset

4 World Boss

A boss battle for the entire server can take part in to kill the boss. The Boss will happen at a set time a day for a limited time (15 minutes) players can compete to deal the most damage to the boss. Rewards will be given to players based of damage ranking and addition rewards will be given if the boss is killed 
if the boss is killed the next time the world boss starts its stats will be doubled but if the boss was not killed it stats will stay the same 

5 creation of any currency or battle stamina

would like to be able to create any form of currency or stamina. and either one can be bought or earned as a reward.

6 Fragments

have items/characters as fragments (Characters, Gear, Upgrade materials) peace fragments of characters, items, gear as a whole. and these fragments can be obtained from summons, rewards, or shop. 
Lastly, universal fragments can be used as replacement if you're miss set fragment (character, item, Gear, etc)

7 Clan Improvements

improve the clan thru clan member's contributions with soft and hard currency. players that contribute to the clan will receive clan currency to spend and buy items or use it to upgrade clan skills that boost certain stats, give exp boost and gold boost

8 Gems Socket

Insert gems into gear or skills to give extra stats or give passive skills ex ( enemies attack while this gem is equipped will cause the poison to the opponent, attack will increase by 5% when the gem is equipped )

9 Skill Upgrade

improve skill stats with gold or items  base on account level

10 Battle Stamina and overall health

character skills cost some form of every to cast and in total the team has 100 stamina/ energy. Energy recover every turn round 1- 20 energy round 2- 40 round 3 60 energy so on until the energy is 100
overall player and enemy health is at the top
[https://i.imgur.com/U2cIps3.jpg](url)

11 Friendship

currently, friendship serves no purpose please add the options to send gold and stamina as gift daily to friends

**Comment by insthync** [comment]
Choose one

**Comment by TheMightyHades** [comment]
Would it be possible to set up a kick starter to fund these updates? I would love to see more features availiable also, but as a solo part time dev i cant spend lots of money on it. I would however donate a little for some of these features to be added. :)

**Comment by Ragingsura** [comment]
1 is not enough but I would really like this 2

- 3 **Timed Events/ daily**
to be able to create events/battles that happen at a specific time of the day and how long set event last for until it's closed for the day until the server reset or day reset

- 5 **creation of any currency or battle stamina**
I would like to be able to create any form of currency or stamina. and either one can be bought or earned as a reward.

**Comment by insthync** [comment]
@Ragingsura Better :P, Okay, about custom currency and stamina, how you're going to use it ?

**Comment by Ragingsura** [comment]
@insthync  the custom currency will be used to set up a shop that the players will have options to buy various items or goods, for example, a custom currency created for the arena. fighting in the arena will give you specific arena currency that you can then use in the arena shop

as for the stamina, I would like to be able to create stamina for specific scenarios or battles for example  story and the arena has a different source of stamina so I would like the ability to create different stamina for different battles  and the stamina can be earned as a reward or, bought with a set currency

**Comment by insthync** [comment]
@Wosit If you like to support me, you can do it via https://ko-fi.com/insthync, I don't have plan to make fund for specific project yet.

**Comment by Ragingsura** [comment]
@insthync thank you for the update, is it possible to get a roadmap for what's planned for future updates
