### ISSUE TITLE
Stamina Issues

### ISSUE THREAD

**Issue by TheMightyHades** [suriyun-production/turnbase-rpg-docs#83]
Hi would someone mind posting a photo of their settings on the stamina section that make it work, ive been playing around with the settings and the only thing ive made it do is tick backwards negitively. For example im now on '0 stamina, -34:-23' on the timer. Editing settings has made the timer disapear but not let it recover stamina. Ive sat and waited for 30 mins so see if the number goes up. 

Currently i have it set to,

min value 0
max value 360
growth at 1
recovery unit minutes
recovery duration 6

Would really like to see the ability to buy stamina from the app store

**Comment by insthync** [comment]
About buy stamina, I will add it in next version. About stamina bugs, it was reported many time, but it doesn't occuring when I test it. I don't know when the problem occuring, are you stop and play game after you change settings ?

**Comment by Wosit** [comment]
Its ok, i figured out i needed to update the version of the template. Only issue is now i have 2 errors coming up.
Any ideas?

Assets\RPGGame\Core\Scripts\GameData\Item\EquipmentItem.cs(20,23): error CS0103: The name 'ScriptableObjectUtility' does not exist in the current context
Assets\RPGGame\Core\Scripts\GameData\Item\CharacterItem.cs(25,23): error CS0103: The name 'ScriptableObjectUtility' does not exist in the current context

**Comment by TheMightyHades** [comment]
I think i fixed it by simply updating the version of the template. 
Really loving this though, I can see this being a huge addition to the Unity store.
Will 5 star asap.
