### ISSUE TITLE
Randomised stats on loot?

### ISSUE THREAD

**Issue by TheMightyHades** [suriyun-production/turnbase-rpg-docs#84]
Hi, just a small request if you get around to it. 
It's very common in these kind of games to have loot in sets. For example a 'speed set' of equipment that adds a speed bonus when you wear 2, 3 or 4 peices in that 'speed set' but also has a selection of randomised stats below it for if you were to wear just one piece.

I'm wondering how easy to impliment this would be. Below is an example of such a piece from a similar game of the same style.
This one is 'divine offence set' and gives +15% attack and a 5% shield to the player if they equip 2 peices of that set.

![Raid_GearYourChampions_S5](https://user-images.githubusercontent.com/60259329/93506762-6281c780-f925-11ea-9e48-d3ef4f67ceb5.jpg)

**Comment by insthync** [comment]
In items and characters, there is `Random Attributes` which will random attributes from min to max value, did you try it?

**Comment by insthync** [comment]
But there is no item attributes set yet

**Comment by TheMightyHades** [comment]
Amazing i hadn't yet spotted that. Will check into it. Thanks!!!
