### ISSUE TITLE
GameDatabase BUG?

### ISSUE THREAD

**Issue by c3068296098** [suriyun-production/turnbase-rpg-docs#86]
Set Items number to 0 in GameDatabase , The INVENTORY page still shows many characters.WHY?
![WMQT GTXFC`G`RT5 J@JD6W](https://user-images.githubusercontent.com/71299993/93566318-6feb9000-f9bf-11ea-98c3-e2782dc56006.png)
![`G_Q Y@ 4`L~(E_)C5(3S0](https://user-images.githubusercontent.com/71299993/93566342-7d087f00-f9bf-11ea-8bda-0dafcc34f5a8.png)

**Comment by insthync** [comment]
Why you want to set it to 0?, You want to make it no starting items or something?

Did you create new game database or using demo's game database?

**Comment by c3068296098** [comment]
> demo's game database?

using demo's game database
![7FQTRYLI7_(P{{CVEQX@8T5](https://user-images.githubusercontent.com/71299993/93568698-1b4a1400-f9c3-11ea-8bcb-a955ef5fd379.png)

**Comment by insthync** [comment]
Did you tries create new account ?

**Comment by c3068296098** [comment]
> Did you tries create new account ?

no ,offline Game

**Comment by insthync** [comment]
You have to create new account, it's offline, you can determined it as new character.

Or delete database which may store at project folder, its extension is `.sqlite3`.

**Comment by insthync** [comment]
You also have to delete items in `Start Items`, `Start Characters` 

![Screenshot_80](https://user-images.githubusercontent.com/2697550/93570118-ba1f4200-f9bc-11ea-8bc4-9181e63c7f4d.png)

**Comment by c3068296098** [comment]
> You also have to delete items in `Start Items`, `Start Characters`
> 
> ![Screenshot_80](https://user-images.githubusercontent.com/2697550/93570118-ba1f4200-f9bc-11ea-8bc4-9181e63c7f4d.png)

it won 't work.I delete tbRpgDb.sqlite3
![N(3)JY$_23@%CTNMP E1$IJ](https://user-images.githubusercontent.com/71299993/93571738-75e56f00-f9c7-11ea-836f-5a21f8c674ff.png)
game database
![$_9 G24KQM9IBXJSU6~E96O](https://user-images.githubusercontent.com/71299993/93572146-fdcb7900-f9c7-11ea-8571-8b66d816846e.png)
![)C}8K(U PEBLS14S%DJFN9C](https://user-images.githubusercontent.com/71299993/93572156-015f0000-f9c8-11ea-9f5e-33130a28e771.png)
I even unplugged the net cable.  BUT 
![`1@C@W9{0A4EB{S H1 W{{I](https://user-images.githubusercontent.com/71299993/93572290-3c613380-f9c8-11ea-9fd0-59f648df5392.png)

**Comment by c3068296098** [comment]
Do I need to export  GameData.json？

**Comment by insthync** [comment]
You don't have to unplugged from the internet :P, Why when you delete items from start items and start characters then you're not delete an items, I don't understand what you want at all, because if you don't delete it it will be added to game database then it will still show in inventory.

NO, you don't have to export GameData.json, it needed for PHP Web-service only.

**Comment by insthync** [comment]
When you start with LoginSceneSQLite, it will uses `SQLiteGameService` which is offline service (There are 2 offline services: `SQLiteGameService` and `LiteDbGameService`. 

Offline service will store data to the device and it is not need internet connection to connect to service.

**Comment by c3068296098** [comment]
But I adjusted the DemoGameDatabase, I wanted to reduce the role, but the Inventory page did not change.

**Comment by insthync** [comment]
Delete all items, start items and start characters then see what happen.

**Comment by c3068296098** [comment]
> But I adjusted the DemoGameDatabase, I wanted to reduce the role, but the Inventory page did not change.

Where does inventory data come from? Has nothing to do with demogamedatabase?

**Comment by c3068296098** [comment]
![)XKQOSS)3IVK8F~BEMCR47D](https://user-images.githubusercontent.com/71299993/93574100-919e4480-f9ca-11ea-9fb7-834dc32f9e01.png)

**Comment by insthync** [comment]
Is it correct?, Is it what you want?

**Comment by insthync** [comment]
Inventory store in tbRpgDb.sqlite3, you can open it with [SQLiteBrowser](https://sqlitebrowser.org/) to see what is in the file.

**Comment by c3068296098** [comment]
Items adjustment 1 characterItem,but  inentory show 6? 
![1 BUHBR`MYFK1KMNF~L}` 9](https://user-images.githubusercontent.com/71299993/93574894-8c8dc500-f9cb-11ea-9125-8d3a0354b82a.png)


![12](https://user-images.githubusercontent.com/71299993/93575164-e0001300-f9cb-11ea-8be2-780912ad7621.png)

**Comment by insthync** [comment]
It's because you're playing with old save, you have to create new save or delete save file (tbRpgDb.sqlite3) and try again.

Items in item database is not item in inventory, it's list of items that player can receives, the system will add item to inventory or delete from inventory or so something else with it later.

**Comment by c3068296098** [comment]
BUt  tbRpgDb.sqlite3 I deleted it before. Now it doesn't exist in the project folder.

**Comment by c3068296098** [comment]
I just want to set the number of  characters。

**Comment by insthync** [comment]
Can you capture video to show how you do that ?

**Comment by c3068296098** [comment]
OK

**Comment by insthync** [comment]
Number of start characters ?

**Comment by c3068296098** [comment]
original
![11](https://user-images.githubusercontent.com/71299993/93578145-8a2d6a00-f9cf-11ea-9329-cf2d33d2f967.png)
 I want to
![11](https://user-images.githubusercontent.com/71299993/93578213-a204ee00-f9cf-11ea-8ee3-88d2150cc61b.jpg)

**Comment by insthync** [comment]
Set `start items` and `start characters`

**Comment by insthync** [comment]
- `Start Characters` is list for characters which will be added to inventory and battle formation
- `Start Items` is list for items and characters which will be added to inventory

**Comment by c3068296098** [comment]
I'd better record a video for you. Wait a minute!

**Comment by insthync** [comment]
How about it ?

**Comment by c3068296098** [comment]
[Video.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/5248884/Video.zip)
Why ?

**Comment by insthync** [comment]
You have to delete `tbRpgDb.sqlite3` file before start a game

**Comment by c3068296098** [comment]
I'm sure I've deleted it.

**Comment by insthync** [comment]
Delete it immediately before start game, in the video I saw that you restart a game immediately after changes database

**Comment by c3068296098** [comment]
Yes, that's what I'm trying to do, but it can't be shown

**Comment by c3068296098** [comment]
Even my own new characters can't be shown.

**Comment by insthync** [comment]
May I access your PC with TeamViwer, send your TeamViewer info to my email: ittipon.bay@gmail.com, I think this is pretty wasting time, we have to do something to solve it.

This is very basic, it should not wasting time like this.

**Comment by c3068296098** [comment]
I'm in a foreign country, you record a video to show how you add new Character, I think it can solve the problem.

**Comment by insthync** [comment]
[bandicam 2020-09-19 08-36-26-285.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/5248930/bandicam.2020-09-19.08-36-26-285.zip)

**Comment by c3068296098** [comment]
[Video.zip](https://github.com/suriyun-production/turnbase-rpg-docs/files/5248965/Video.zip)
no add Character?

**Comment by c3068296098** [comment]
It's solved. Thank you

**Comment by insthync** [comment]
IF you are going to use sqlite, play `LoginSceneSQLite` the `LoginScene` will uses LiteDB, that is why when you delete `tbRpgDb.sqlite3` then start game, it won't update.
