### ISSUE TITLE
Revive Skill

### ISSUE THREAD

**Issue by TheMightyHades** [suriyun-production/turnbase-rpg-docs#88]
Hi mate, sorry to bother again.
I'm wondering how i would go about setting up a revive skill? Is it possible so that when a team member dies, they can be brought back?

**Comment by TheMightyHades** [comment]
In addition to this it would be nice to get skills that apply when hit...
As in, on event character hit, increase damage output 20%     or      on event character hit, has 20% chance to boost allies HP 20%

**Comment by insthync** [comment]
I will add it.
