### ISSUE TITLE
Choice Language in the menu.

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#89]
Hello! How to implement the choice of languages, for example, in the game menu?

**Comment by TheMightyHades** [comment]
Correct me if im wrong, but i would create as many menus as you have languages (copy paste) and then on the splash screen have flags instead of a click to continue button that links to each indiviual menu. You dont need to rewrite any scripts, just change the size of the click box on the splash screen so the player is forced to click a language type.

**Comment by brabaris** [comment]
->Wowis  
Correcting ...
 In Turnbase RPG Template even in the script there is no language switching implementation!
And in MMORPG KIT (2D / 3D / Survival) the choice of languages is fully implemented.

**Comment by TheMightyHades** [comment]
Ok, well i've just tested it and implimented both greek and english languages into mine, so i can tell you it works. (sorry they're the only languages i know.)

**Comment by brabaris** [comment]
I can also add, but how can a player change the language?! The question was not how to add a new language, but how to choose a language!
In MMORPG KIT (2D / 3D / Survival) OnClickChangeLanguage.cs and OnToggleChangeLanguage.cs to replace the language, in Turnbase RPG Template the user cannot change the language!

**Comment by brabaris** [comment]
I just can't screw LanguageManager.cs and OnClickChangeLanguage.cs  
Suriyun need help! Here is the source for LanguageManager.cs. There are no errors, but change language I can not!

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
#endif

public class LanguageManager : MonoBehaviour
{

    public static readonly Dictionary<string, Dictionary<string, string>> Languages = new Dictionary<string, Dictionary<string, string>>();
    private static Dictionary<string, string> texts = new Dictionary<string, string>();
    public static Dictionary<string, string> Texts { get { return texts; } }
    private static string currentLanguageKey = string.Empty;
    public static string CurrentLanguageKey { get { return currentLanguageKey; } }
    private static string currentPlayerPrefsKey = string.Empty;

    [Header("Language Manager Configs")]
    public string defaultLanguageKey = "ENG";
    public string playerPrefsKey = "USER_LANG";
    public List<Language> languageList = new List<Language>();

    [Header("Add New Language")]
    [Tooltip("You can add new language by `Add New Language` context menu")]
    public string newLanguageKey;
    [InspectorButton("AddNewLanguage")]
    public bool addNewLanguage;

    private void Awake()
    {
        currentPlayerPrefsKey = playerPrefsKey;
        currentLanguageKey = PlayerPrefs.GetString(currentPlayerPrefsKey, defaultLanguageKey);
        Languages.Clear();
        Dictionary<string, string> tempNewData;
        foreach (Language language in languageList)
        {
            tempNewData = new Dictionary<string, string>();
            foreach (LanguageData data in language.dataList)
            {
                if (tempNewData.ContainsKey(data.key))
                {
                    Debug.LogWarning("[LanguageManager] Language " + language.languageKey + " already contains " + data.key);
                    continue;
                }
                tempNewData.Add(data.key, data.value);   
            }
            Languages[language.languageKey] = tempNewData; 
        }
        ChangeLanguage(defaultLanguageKey);
    }

    public Language GetLanguageFromList(string languageKey)
    {
        foreach (Language language in languageList)
        {
            if (language.languageKey == languageKey)
                return language;
        }
        return null;
    }

    [ContextMenu("Add New Language")]
    public void AddNewLanguage()
    {
        if (string.IsNullOrEmpty(newLanguageKey))
        {
            Debug.LogWarning("`New Language Key` is null or empty");
            return;
        }

        Language newLang = GetLanguageFromList(newLanguageKey);
        if (newLang == null)
        {
            newLang = new Language();
            newLang.languageKey = newLanguageKey;
            languageList.Add(newLang);
        }

        foreach (KeyValuePair<string, string> pair in DefaultLocale.Texts)
        {
            if (newLang.ContainKey(pair.Key))
                continue;

            newLang.dataList.Add(new LanguageData()
            {
                key = pair.Key,
                value = pair.Value,
            });
        }
    }


    public static void ChangeLanguage(string languageKey)
    {
        if (!Languages.ContainsKey(languageKey))
            return;

        currentLanguageKey = languageKey;
        texts = Languages[languageKey];
        PlayerPrefs.SetString(currentPlayerPrefsKey, currentLanguageKey);
        PlayerPrefs.Save();
    }

    public static string GetText(string key, string defaultValue = "")
    {
        if (Texts.ContainsKey(key))
            return Texts[key];
        if (DefaultLocale.Texts.ContainsKey(key))
            return DefaultLocale.Texts[key];
        return defaultValue;
    }

    public static string ReplaceFormat(string key, string replacingText)
    {
        return ReplaceFormat("{" + key + "}", Texts[key], replacingText);
    }

    public static string ReplaceFormat(string key, string value, string replacingText)
    {
        return replacingText.Replace("{" + key + "}", value);
    }

    public static string FormatNumber(int value, bool asPercent = false)
    {
        return asPercent ? (value * 100).ToString("N0") + "%" : value.ToString("N0");
    }

    public static string FormatNumber(float value, bool asPercent = false)
    {
        return asPercent ? (value * 100).ToString("N0") + "%" : value.ToString("N0");
    }

    public static string FormatInfo(string key, int value, bool asPercent = false)
    {
        return string.Format(Texts[GameText.FORMAT_INFO], Texts[key], FormatNumber(value, asPercent));
    }

    public static string FormatInfo(string key, float value, bool asPercent = false)
    {
        return string.Format(Texts[GameText.FORMAT_INFO], Texts[key], FormatNumber(value, asPercent));
    }

    public static string FormatAttribute(string key, int value, int bonusValue, bool asPercent = false)
    {
        return string.Format(Texts[GameText.FORMAT_ATTRIBUTE], Texts[key], FormatNumber(value, asPercent), FormatBonus(value, asPercent));
    }

    public static string FormatAttribute(string key, float value, float bonusValue, bool asPercent = false)
    {
        return string.Format(Texts[GameText.FORMAT_ATTRIBUTE], Texts[key], FormatNumber(value, asPercent), FormatBonus(value, asPercent));
    }

    public static string FormatBonus(int value, bool asPercent = false)
    {
        if (value > 0)
            return string.Format(Texts[GameText.FORMAT_BONUS], "+", FormatNumber(value, asPercent));
        else if (value < 0)
            return string.Format(Texts[GameText.FORMAT_BONUS], "-", FormatNumber(value, asPercent));
        else
            return "";
    }

    public static string FormatBonus(float value, bool asPercent = false)
    {
        if (value > 0)
            return string.Format(Texts[GameText.FORMAT_BONUS], "+", FormatNumber(value, asPercent));
        else if (value < 0)
            return string.Format(Texts[GameText.FORMAT_BONUS], "-", FormatNumber(value, asPercent));
        else
            return "";
    }

    public static string ReplaceFormatAsFormatBonus(string key, int value, string replacingText, bool asPercent = false)
    {
        return replacingText.Replace("{" + key + "}", FormatBonus(value, asPercent));
    }

    public static string ReplaceFormatAsFormatBonus(string key, float value, string replacingText, bool asPercent = false)
    {
        return replacingText.Replace("{" + key + "}", FormatBonus(value, asPercent));
    }
}

**Comment by brabaris** [comment]
Here is the source for LanguageManager.cs

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class OnClickChangeLanguage : MonoBehaviour
{
    public string languageKey;
    public void OnClick()
    {
        LanguageManager.ChangeLanguage(languageKey);
    }
}
