### ISSUE TITLE
Avatar for acoount ask

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#9]
I wonder how it works for friends and I would also like to know how I can add the avatar of the account in the sand I see that it takes a sprite but I do not know how it could be customized, I know how to put the image of the frame and that it looks only in the main, but how could I put the avatar of the account.. sorry for my english i was use google traduc

**Comment by dclgamingtr** [comment]
![image](https://user-images.githubusercontent.com/61230304/75288155-caa77980-582c-11ea-8a78-a1de4413bf6f.png)

**Comment by surycr** [comment]
how u are did that

**Comment by surycr** [comment]
creo que hablas español

**Comment by dclgamingtr** [comment]
İspanyolca bilmiyorum üzgünüm.

surycr <notifications@github.com>, 26 Şub 2020 Çar, 00:58 tarihinde şunu
yazdı:

**Comment by surycr** [comment]
i try but i cant did that

**Comment by dclgamingtr** [comment]
I created this after 3 hours of code writing. If you don't know how to
code, you have to wait for Suriyun.

>

**Comment by dclgamingtr** [comment]
I also made a leaderboard. I think I can save them all and put them on sale
as an additional package. I am thinking of selling the things I do as a
single package.

>

**Comment by surycr** [comment]
aa ok

**Comment by surycr** [comment]
look nice iwant

**Comment by surycr** [comment]
how to much

**Comment by dclgamingtr** [comment]
7 dollars

surycr <notifications@github.com>, 26 Şub 2020 Çar, 08:46 tarihinde şunu
yazdı:

**Comment by dclgamingtr** [comment]
Including all updates in the future.

3Hill Studio <dclgamingtr@gmail.com>, 26 Şub 2020 Çar, 19:12 tarihinde şunu
yazdı:

**Comment by surycr** [comment]
nice
