### ISSUE TITLE
Game tutorial or story

### ISSUE THREAD

**Issue by TheMightyHades** [suriyun-production/turnbase-rpg-docs#90]
I would love to have to set a few of the stages to not start automatically and be able to use a UI to display text for either a tutorial or further on a story line. It would add a lot of depth to the game i believe.

Just an idea i had, i know you have a lot on your plate.

Also, for future notice, are you hireable as a freelance if needed?

**Comment by insthync** [comment]
I can do the demo for it, but tutorial stuff can be very varying, up to UIs, so I don't think it will be useful for other projects.

**Comment by TheMightyHades** [comment]
Yes, i suppose thats very true. For now i've done it all through UI on the management screen and has worked out ok. Thanks for the reply!
