### ISSUE TITLE
environment object/stage issue

### ISSUE THREAD

**Issue by TheMightyHades** [suriyun-production/turnbase-rpg-docs#91]
I'm having an issue with how the environment object is showing up on the battle section. Any ideas why this is happening?
![refrence1](https://user-images.githubusercontent.com/60259329/94556880-794de580-0266-11eb-8624-ce5721047803.png)

**Comment by TheMightyHades** [comment]
I've set the object collider to fit over the whole terrain so the characters should spawn in the center right?

**Comment by TheMightyHades** [comment]
So basically it doesn't seem to work with terrains, any way to fix this?

**Comment by insthync** [comment]
Did you found solution?, I am going to ask about attached collider which must cover your environment.

**Comment by TheMightyHades** [comment]
Yes, i found the soloution. Created a cube to cover the same volume as the terrain and then removed the cubes mesh. I assigned the cube as the Environment object and the terrain as a child and its working perfectly. I should have spent a few more hours troubleshooting before asking the query. My bad.
