### ISSUE TITLE
Extended Documentation - PHP Web Service

### ISSUE THREAD

**Issue by MystaraCorvus** [suriyun-production/turnbase-rpg-docs#92]
I really love the asset and I have a lot of fun working with it. But I now want to try it out online and I find the documentation is a little empty when it comes to that. I saw the GitHub page and I have the config.ini file setup and I have a server where I work with "PhpMyAdmin" for my tables. The thing that I am missing is what do I do now? Where do I put the config.ini and the sql-importer.php file? I am not really experienced with these kinds of things and want to humbly ask for a bit of assist to get it up and running or if you could just send me a link where I can find more information. I don't know currently what knowledge I am missing.

**Comment by surycr** [comment]
i have the same question

**Comment by insthync** [comment]
Browse `sql-importer.php` I means to open your web-browser (Google Chrome, Microsoft Edge, Apple Safari or something) 
to your web where you placed website scripts for example, if I placed it to `htdocs/service` I have to open my web by the URL like as : `https://www.mywebsite.com/service/sql-importer.php` to import tables to database.

That is it.
