### ISSUE TITLE
Attack Animation

### ISSUE THREAD

**Issue by Atsushi0514811** [suriyun-production/turnbase-rpg-docs#93]
How do I set an effect for Attack Animation?
I would like to use it for attacks such as magic.

**Comment by insthync** [comment]
You may use Unity's animation event https://docs.unity3d.com/Manual/script-AnimationWindowEvent.html

You will have to create new component, which will be attached to the same game object with `Animator` component

**Comment by Atsushi0514811** [comment]
I know the animation settings.
I would like to know how to set particles such as flame and light.

**Comment by insthync** [comment]
https://suriyun-production.github.io/turnbase-rpg-docs/#/pages/027-character-effect-data-and-game-effect
