### ISSUE TITLE
IAP Errors

### ISSUE THREAD

**Issue by eldevinho** [suriyun-production/turnbase-rpg-docs#94]
Hello, im having some problems with IAP i try to find a solution but i have the same error. The payment is working, so the player can buy and pay but don't receive the rewards. I need some help. Trying to find solution on Discord few months but no answers so i try here now.

Everything is updated

![iap_error](https://user-images.githubusercontent.com/72809617/95875406-46314900-0d72-11eb-9237-c9f4b7cacd65.PNG)

**Comment by insthync** [comment]
Did you set public key which can get from `your app console > Development tools > Services & APIs > `

![Screenshot_99](https://user-images.githubusercontent.com/2697550/97701948-c5e44500-1ae0-11eb-8cc0-b4dd5d0b3ca7.png)


To config.ini > play_public_key ?
