### ISSUE TITLE
Too much error can't update the game

### ISSUE THREAD

**Issue by Hexone33** [suriyun-production/turnbase-rpg-docs#95]
Get too much error after update the game, too much game change and script change so can't update without breaking every things

**Comment by insthync** [comment]
Still cannot update?

**Comment by Hexone33** [comment]
Yes still, my game is very customized by you and impossible to update

**Comment by insthync** [comment]
The new big update is coming soon, when I done I will help you with the update later.

**Comment by Hexone33** [comment]
Oh nice, what gona be in ?

**Comment by insthync** [comment]
Things relate to clan system and raid boss.

**Comment by Hexone33** [comment]
Okay nice where we can contact when you'r gona help me out ?

**Comment by dclgamingtr** [comment]
When will the update be? Please include the clan chat in the chat options. And most importantly please add leaderboard.

**Comment by insthync** [comment]
Yeah, I will add it but all of the updates will be done lately, clan with donation system, level, custom currencies types are pretty big thing.

**Comment by Hexone33** [comment]
@insthync I see that the update is out any help for setuping it ?

**Comment by insthync** [comment]
Next weekend, I will connect to you by TeamViewer and help you do that, okay?

**Comment by Hexone33** [comment]
@insthync  Okay sure we can talk by this email : marlon.33@live.fr

**Comment by insthync** [comment]
Contact me: ittipon.bay@gmail.com

**Comment by Hexone33** [comment]
@insthync I have contacted you but no response
