### ISSUE TITLE
i was use game spark and i need change for php need integration 

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#96]
i was change for php but i try find u page and i cant found (ERROR 404)

**Comment by insthync** [comment]
Yes, it was discontinued,
Do you need database migration or not ?

**Comment by surycr** [comment]
No just how restar in php

**Comment by surycr** [comment]
U guide is off

**Comment by surycr** [comment]
i was try use php i have account in infinityfree i have sql database and i upload sql files but i dont know how use json file with database and integration in php, i think i cant use for test i am new in php because i am use gamespark and iwas easy for use
![image](https://user-images.githubusercontent.com/43394702/96038938-2313a180-0e25-11eb-8ebd-cdbfddad72ed.png)
