### ISSUE TITLE
Animation bugs?

### ISSUE THREAD

**Issue by TheMightyHades** [suriyun-production/turnbase-rpg-docs#98]
Hey,
I've been struggling with this over the weekend. Theres not console errors, ive tried changing the capsule collider size, adding constraints, changing the animations etc. I can't seem to find a fix to the issue.

Any ideas?

https://www.youtube.com/watch?v=0pEQjLcClxo&feature=youtu.be

**Comment by insthync** [comment]
Not sure in your character -> Animator component, root motion is enabled or not. If enabled, try to disable it.

**Comment by TheMightyHades** [comment]
Yeah i have done this also. It unfortuantely doesnt change anything...

I've also turned off 'loop animation' and tried shortening the animation length to the same frames as the existing animations in the demo. These fixed nothing also.

**Comment by TheMightyHades** [comment]
I've also tried with Mixamo animations, RPG mechanim pack and the standard animations you provide. For some reason, characters are bouncing off each other all over the place...

**Comment by TheMightyHades** [comment]
Discovered the issue a while back, but forgot to share with others incase people have the same issues. Weapons placed in the soldiers hands had thier own mesh colliders. It was causing all sorts of funny bugs. Once the mesh colliders were removed, the game acted normally again.
