### ISSUE TITLE
Future Updates

### ISSUE THREAD

**Issue by Ragingsura** [suriyun-production/turnbase-rpg-docs#99]
Hey @insthync  for the future update could you add these features. even if it 1-2 each update
also the custom currency I need a guide on how to create it

1. **Account profile**
- currently, the player account has no profile 1 is need for basic account information, settings, and few extra settings. Example 
  below
![Bluestacks_3DlYIyNH9h](https://user-images.githubusercontent.com/52991546/98675951-f02bd300-2328-11eb-9ad4-41ead699039f.png)
![Bluestacks_mEbexTbBx1](https://user-images.githubusercontent.com/52991546/98675960-f326c380-2328-11eb-9c8a-abad3fe6ede6.png)
![Bluestacks_mcAolURoMQ](https://user-images.githubusercontent.com/52991546/98675963-f5891d80-2328-11eb-81bc-23acb6dedadb.png)

2. **Level Usefulness**
- the ability to use the account level to lock/hide/Restrict content until the player reaches a set level such as ( Story, chapter, 
  Arena, Dungeon, Equipment Crafting, etc what gear can players craft or equip on character, the max upgrade for characters 
  base on account level that includes character level armor and skill level.
![Bluestacks_3DlYIyNH9h](https://user-images.githubusercontent.com/52991546/98678862-2ff4b980-232d-11eb-8937-0a902ebeab5f.png)
![Bluestacks_QQmvuWbWnM](https://user-images.githubusercontent.com/52991546/98678872-32efaa00-232d-11eb-9eaa-9677f2a4ab12.png)

3. **Overall Ranking**
- hold ranking for account level, player overall power, numbers of stages cleared, arena rank, guild level, guild power, etc
![Bluestacks_tUh7vwOlW9](https://user-images.githubusercontent.com/52991546/98676004-02a60c80-2329-11eb-90f1-6e37c2555904.png)

4. **Skill Upgrade**
- improve skill stats with gold or items base on the account level
![Bluestacks_JZGgmqWK8A](https://user-images.githubusercontent.com/52991546/98676021-06d22a00-2329-11eb-9e5a-fd79c9808f95.png)

5. **Friendship**
- currently, friendship serves no purpose please add the options to send gold and stamina as gift daily to friends
![Bluestacks_VfzryDSJZN](https://user-images.githubusercontent.com/52991546/98676044-0f2a6500-2329-11eb-96bd-059720a34681.png)

6. **chat improve**
- add more chat option private, clan chat,  friend chat,
![Bluestacks_Q3h9sqXRvn](https://user-images.githubusercontent.com/52991546/98676086-210c0800-2329-11eb-889e-a85a1985a474.png)
![Bluestacks_7gVY794mfZ](https://user-images.githubusercontent.com/52991546/98676094-249f8f00-2329-11eb-9293-e2b6559a78ca.png)

7. **daily login rewards and online rewards**
-  login rewards and stayed online rewards
![Bluestacks_iIcQX0ECWb](https://user-images.githubusercontent.com/52991546/98676109-29fcd980-2329-11eb-9f4f-f83ad56bd601.png)

8. **Missions/quest**
- from the achievement add an option for daily, weekly, and monthly achievement, quest/mission
![Bluestacks_X9OvhqZJDQ](https://user-images.githubusercontent.com/52991546/98676129-31bc7e00-2329-11eb-9efc-8a82f3b24ecc.png)
![Bluestacks_puOiRjg3nl](https://user-images.githubusercontent.com/52991546/98676323-73e5bf80-2329-11eb-9031-415e2c1e480c.png)

9. **Raid**
-option to raid the already cleared stage for resources  raid x1, x3, or x10 times and only stages with 3 stars clear can be raided 
![Bluestacks_Tc6C2hFQBS](https://user-images.githubusercontent.com/52991546/98676343-7a743700-2329-11eb-8d1e-f3b170d801e6.png)
![Bluestacks_TzvHqADyYK](https://user-images.githubusercontent.com/52991546/98676358-7fd18180-2329-11eb-875b-a539993820ff.png)

10. **Loot box / summon**
use a custom item/ currency to summon 
have daily free summon 
![Bluestacks_lYy0ginQbX](https://user-images.githubusercontent.com/52991546/98676387-8cee7080-2329-11eb-9bd6-8cd9ba205940.jpg)

11. clan improvement
improve clan level to unlock features and level can be improved from members' daily donation with clan quest, soft or hard. 
features include clan skills, clan shop [custom clan currency can be obtained from donations, clan missions, or clan dungeons]
clan dungeon, clan boss, clan wars

12. chest items
chest/bag that would contain several items when opening
![Bluestacks_ZC6ki1Pt6W](https://user-images.githubusercontent.com/52991546/98677434-020e7580-232b-11eb-8faa-b7d2ca7b2849.png)
![Bluestacks_ncrW2TfPWZ](https://user-images.githubusercontent.com/52991546/98677446-06d32980-232b-11eb-9e4d-02aab888b627.png)
![Bluestacks_j8m17jV1lO](https://user-images.githubusercontent.com/52991546/98677458-09358380-232b-11eb-8333-fcae4db9d297.png)

13. character, items, and gear fragments
collect fragment of a character, item, or gear to make it whole
![Bluestacks_4A06RPtA2m](https://user-images.githubusercontent.com/52991546/98678189-2dde2b00-232c-11eb-9c73-ca9a40ac86f0.png)
![Bluestacks_1zr8W9M8fO](https://user-images.githubusercontent.com/52991546/98678193-30408500-232c-11eb-9a32-e67de03edd56.png)
![Bluestacks_t7KjKEuVow](https://user-images.githubusercontent.com/52991546/98678408-80b7e280-232c-11eb-8f78-1650734e9e59.png)
![Bluestacks_MoToOZLH96](https://user-images.githubusercontent.com/52991546/98678410-8281a600-232c-11eb-9d76-bbe96c2fd368.png)

14. universal fragment
an item use to piece or replace missing fragment for items, character, and gear
![Bluestacks_uzx3LIwyrJ](https://user-images.githubusercontent.com/52991546/98678684-f328c280-232c-11eb-8df0-6d9943efe2d6.png)
![Bluestacks_JdawRAGK94](https://user-images.githubusercontent.com/52991546/98678688-f459ef80-232c-11eb-995e-b7e174db6438.png)
![Bluestacks_iK2jevcuiW](https://user-images.githubusercontent.com/52991546/98678700-f623b300-232c-11eb-9488-917ad4895474.png)
![Bluestacks_ESvCX9eyhE](https://user-images.githubusercontent.com/52991546/98678706-f754e000-232c-11eb-9ff1-7e0b404f1cf1.png)

**Comment by insthync** [comment]
Let's start with clan improvement, please write more detail about it, I want to know how clan gets EXP for Levelling up, Amount of currency required for donation is it fixed or can be increased by the amount of donation per day, Whats clan skills can do?

**Comment by Ragingsura** [comment]
this is more or less an in-depth look into the complete clan system @insthync 

A player can either join an existing Clan or create their own Clan.

Joining an established Clan can be simple or difficult depending on the Clan's requirements. Some don't have requirements and can be joined instantly, while others have level requirements, cp requirements, or needs the approval of a Clan leader.

Creating a Clan requires a set amount of currency and account level

Up to 30 players can join in a level 1 clan. but as the clan levels up the member amount goes up
Level 1- 30 members, level 2 40, levels 3- 50  so on

Guild will consist of Clan Leader / Co-Leader / Elder / Clan member. with each having a different level of powers in the clan
if a clan leader is inactive for a set amount of time a co-leader can take the leader position thru a clan vote and if both leader and co-leader are inactive then the elder with the highest contributing will initiate the vote for them to take the position of leader.

You can check the Clan members / Clan information/history of the Guild members on the Guild page.
![Bluestacks_NNdg53kqQF](https://user-images.githubusercontent.com/52991546/98675024-b0182080-2327-11eb-8b18-0f2dd31aaf12.png)
![Bluestacks_PnoVAyMB7T](https://user-images.githubusercontent.com/52991546/98675036-b4443e00-2327-11eb-86a7-6d197d42b974.png)


When you leave a clan, you will face a penalty that you won't be able to join another clan for 24s, and the number of clans you leave the penalty goes up. you will only receive a one time 24 penalty if you got kicked instead

**Clan Facilities/ systems**
a clan will consist of different facilities depending on the level of the clan which will include  Clan dungeon, Clan Boss, Clan Mission, Clan Skill center, Clan training center, Clan Gifting center, clan wars, and clan crafting station

**Clan Dungeon Unlock at clan level 1**
just like adventure/story but for the guild, each member can fight a dungeon 5 times a day clearing each dungeon will give clan exp, Clancoins, clan funds, crafting materials, and other items. As these facilities get leveled up reward improves
![Bluestacks_CM5BtPwoh9](https://user-images.githubusercontent.com/52991546/98675118-d0e07600-2327-11eb-8568-79896eb7c781.jpg)

**Clan boss unlock at clan level 4**
just like dungeon build boss will be a bit different members will have 3 chance a day to fight the clan boss and the boss will have 100% overall health for the entire clan after the clan fight the boss and it health hit 0% rewards will be given base on damage, last hit and overall reward for killing the boss rewards include Clan coins, clan exp, clan funds, crafting materials, and other items. As these facilities get leveled up reward improves.
![Bluestacks_JpC4SnUFUY](https://user-images.githubusercontent.com/52991546/101435906-26825100-38db-11eb-8f3f-30f7a06ab5c7.png)


**Clan Skill center unlock at clan level 2** 
 where you manage Clan Buff Skills such as EXP, Gold buffs, and more.
Clan skills can be upgraded as much as your current Skill Center level.
You can raise the Guild Skill level by using clan coins
all buff will be lost if you leave the clan. and regain once you join another clan

Increase Attack
 | Lv1 | Lv2 | Lv3 | Lv4 | Lv5 | Lv6 | Lv7 | Lv8 | Lv9 | Lv10
1% | 2% | 3% | 4% | 5% | 6% | 7% | 8% | 9% | 10%
Increase Defense
Increase Gold gain
Increase XP gain
Boost to clan dunegon ATK
Boost to clan dungeon DEF
Increase clan dungeon Max HP 
Increase Guild Raid Crit DMG
Boost to clan Boss ATK
Boost to clan Boss DEF
Increase clan BossMax HP 
Increase clan Boss Crit DMG
etc etc

**Clan training center unlock at the clan level 1**
a place where members could put characters to train and gain exp over a set period. Exp gained will be determined by the level of the Facilities. The level of the facilities will determine the number of characters that members can send to the train.
![Bluestacks_XQQR4pDNg4](https://user-images.githubusercontent.com/52991546/98675159-de95fb80-2327-11eb-8466-dfa4f116e544.png)

Clan Gifting center unlock at the clan level 3
Where members can request other members for items and other members gift those items if they have it this will be limited to certain items only

**clan crafting station unlocks at the clan level 3**
rare items that can only be crafted in the clan, it requires clan coin and other items. The item crafted can only be used while in a clan and the items that can be crafted will depend on the level of the facility.

**Clan mission unlock at the clan level 1**
daily set of quest done by the clan members  that reset every day and gives clan exp, clan coins, clan funds, and other items

**clan wars unlock at the clan level 2**
not sure how you would implement this

**Clan contributions**
the clan member can donate hard or soft currency  5 times a day with 4 levels of donations  2 soft currency and 2 hard currency and you will gain clan exp, clan coins, and clan funds
![Bluestacks_23cE4C4w12](https://user-images.githubusercontent.com/52991546/98671372-24e85c00-2322-11eb-989a-8de1e9317aeb.png)


**clan funds and clan coins**
Clan funds can be obtained from donations, dungeons, boss fights. mission and clan wars which can be used to further improve clan facilities and level them up

Clain coins can be obtained from donations dungeon, boss fights, mission, and clan wars which can be used to improve clan skills and buy items from the clan shop
![Bluestacks_23cE4C4w12](https://user-images.githubusercontent.com/52991546/98675258-05ecc880-2328-11eb-80e3-fc61fda1c3d1.png)
![Bluestacks_ADiJlPr94N](https://user-images.githubusercontent.com/52991546/98675293-10a75d80-2328-11eb-9b39-889b086a29e1.png)

**Comment by insthync** [comment]
Your requests will be done slowly because there are lots of things to do.

**Comment by TheMightyHades** [comment]
Agree 100% on this. would love to see more development on this product. Fragments are a must in this kind of game. Would be cool to see them be able to be bought from an ingame store. For example, when you win arena (pvp) battles you keep the trophies and can then spend them in the store on champion fragments.

**Comment by Ragingsura** [comment]
> Your requests will be done slowly because there are lots of things to do.

No Problem as long as the assets get more features to work with.
 sorry for the late reply been away from home for a while.
